function FixedJSON = FixJSON(InputJSON)
    
    for i =1:1:max(size(InputJSON))
        FixedJSON(i) = strsubst(InputJSON(i),"\/","/")
    end        

    // add items in the JSON file that require a double instead of an int to the doubleVars 
    // array. This will likely need to be expanded as the JSON file
    //progresses
    doubleVars = [  "burn_rate_factor", ...
                    "time_delay", ...
                    "temperature", ...
                    "flame_spread_time",...
                    "diameter", ...
                    "dome_height", ...
                    "reference_burn_rate", ...
                    "heat",...
                    "volume", ...
                    "burn_rate_exponent", ...
                    "thickness", ...
                    "heat_flux",...
                    "heat_transfer_coefficient", ...
                    "scale_factor", ...
                    "Cd_value", ...
                    "mass", ...
                    "amount", ...
                    "viscous_flow_factor", ...
                    "coefficient"]
   csvWrite(FixedJSON, "debug.json")
   FixedJSON = ConvertIntsToDoublesJSON(FixedJSON, doubleVars)
    
endfunction
