function p52InitializeFoundationState(appRoot)
    global P2_APP_ROOT P2_REQUEST_COUNT P2_LIBRARY_ACTIVE;
    global P2_TX_ACTIVE P2_TX_ID P2_TX_VIEWPORT_ID P2_TX_BATCH_COUNT P2_TX_VALUE_COUNT P2_TX_WINDOW_SIZE P2_TX_NEXT_BATCH P2_TX_ACKED P2_TX_CANCELLED;
    global P2_HOST_LOG_LINES;
    global P2_GX_ACTIVE P2_GX_ID P2_GX_REQUEST_ID P2_GX_EXPECTED_CHUNKS P2_GX_EXPECTED_SIZE P2_GX_CHECKSUM P2_GX_TIMEOUT_MS P2_GX_STARTED_S P2_GX_CHUNKS P2_GX_RECEIVED P2_GX_COMMITTED;
    P2_APP_ROOT=appRoot; P2_REQUEST_COUNT=0; P2_LIBRARY_ACTIVE=%t;
    P2_TX_ACTIVE=%f; P2_TX_ID=""; P2_TX_VIEWPORT_ID=0; P2_TX_BATCH_COUNT=0; P2_TX_VALUE_COUNT=0; P2_TX_WINDOW_SIZE=2; P2_TX_NEXT_BATCH=0; P2_TX_ACKED=0; P2_TX_CANCELLED=%f;
    P2_HOST_LOG_LINES=[];
    P2_GX_ACTIVE=%f; P2_GX_ID=""; P2_GX_REQUEST_ID=""; P2_GX_EXPECTED_CHUNKS=0; P2_GX_EXPECTED_SIZE=0; P2_GX_CHECKSUM=0; P2_GX_TIMEOUT_MS=0; P2_GX_STARTED_S=0; P2_GX_CHUNKS=[]; P2_GX_RECEIVED=[]; P2_GX_COMMITTED="";
endfunction

function p52InitializePlottingState()
    global P3_DATASET_ACTIVE P3_DATASET_ID P3_CURVE_COUNT P3_POINTS_PER_CURVE P3_X_MIN P3_X_MAX P3_DATASET_SEED P3_VIEWPORT_CACHE_KEYS P3_VIEWPORT_CACHE_VALUES;
    global P35113_ENCODING_IDS P35113_ENCODING_MS P35113_ENCODING_CHARS;
    global P34_NATIVE_FRAME P34_NATIVE_AXES P34_NATIVE_LINES P34_NATIVE_CURVE_IDS P34_NATIVE_ACTIVE P34_NATIVE_RENDER_COUNT;
    global P342_PREPARED_ID P342_PREPARED_IDS P342_PREPARED_X P342_PREPARED_Y P342_PREPARED_META;
    P3_DATASET_ACTIVE=%f;P3_DATASET_ID="";P3_CURVE_COUNT=0;P3_POINTS_PER_CURVE=0;P3_X_MIN=0;P3_X_MAX=1;P3_DATASET_SEED=1;P3_VIEWPORT_CACHE_KEYS=[];P3_VIEWPORT_CACHE_VALUES=list();
    P35113_ENCODING_IDS=[];P35113_ENCODING_MS=[];P35113_ENCODING_CHARS=[];
    p3510AiftReset();p358PyramidReset();
    P34_NATIVE_FRAME=[];P34_NATIVE_AXES=[];P34_NATIVE_LINES=list();P34_NATIVE_CURVE_IDS=[];P34_NATIVE_ACTIVE=%f;P34_NATIVE_RENDER_COUNT=0;
    P342_PREPARED_ID="";P342_PREPARED_IDS=[];P342_PREPARED_X=list();P342_PREPARED_Y=list();P342_PREPARED_META=[];
endfunction
