"use strict";
P4.register({id:"BR-PRO-001",name:"Envelope validation accepts valid message",layer:"browser",requirements:["PRO-001","PRO-002","PRO-003"],tier:"smoke",run(){const m=P2.client.envelope("diagnostic.echo.request",{});P4.assert.true(P2.validation.envelope(m).pass);return{type:m.type};}});
P4.register({id:"BR-PRO-002",name:"Envelope validation rejects missing type",layer:"browser",requirements:["PRO-001","TST-003"],tier:"smoke",run(){const m=P2.client.envelope("diagnostic.echo.request",{});delete m.type;P4.assert.true(!P2.validation.envelope(m).pass);}});
P4.register({id:"BR-REQ-001",name:"Request registry settles and cleans",layer:"browser",requirements:["PRO-003","PRO-009"],tier:"standard",async run(){const r=new P2.RequestRegistry();let value=null;const p=new Promise((resolve,reject)=>r.register({requestId:"r1",settled:false,resolve,reject,timer:setTimeout(()=>{},1000)})).then(v=>value=v);P4.assert.true(r.settle("r1",{ok:true,value:7}));await p;P4.assert.equal(value,7);P4.assert.equal(r.size,0);}});
P4.register({id:"BR-REQ-002",name:"Duplicate request ID rejected",layer:"browser",requirements:["PRO-003","TST-003"],tier:"standard",run(){const r=new P2.RequestRegistry(),s={requestId:"dup",settled:false,resolve(){},reject(){},timer:setTimeout(()=>{},1000)};r.register(s);P4.assert.throws(()=>r.register({...s}),"DUPLICATE_REQUEST_ID");clearTimeout(s.timer);}});
P4.register({id:"BR-REQ-003",name:"Timeout settlement removes pending state",layer:"browser",requirements:["PRO-009"],tier:"standard",async run(){const r=new P2.RequestRegistry();let code="";const p=new Promise((resolve,reject)=>{const id="timeout";r.register({requestId:id,settled:false,resolve,reject,timer:setTimeout(()=>r.settle(id,{ok:false,error:new P2.TimeoutError(id,20)}),20)});});try{await p;}catch(e){code=e.code;}P4.assert.equal(code,"REQUEST_TIMEOUT");P4.assert.equal(r.size,0);}});
P4.register({id:"BR-PLOT-001",name:"Mock plot adapter lifecycle",layer:"browser",requirements:["PLT-002","PLT-010"],tier:"standard",run(){const c=document.createElement("div");Object.defineProperty(c,"clientWidth",{value:640});Object.defineProperty(c,"clientHeight",{value:320});const a=new P3.ReferenceCanvasAdapter().initialize(c);a.setViewport({xMin:0,xMax:1});a.setSeries([{id:"c1",x:[0,.5,1],y:[0,1,0]}]);P4.assert.equal(a.getMetrics().seriesCount,1);a.destroy();P4.assert.equal(c.childElementCount,0);}});
P4.register({id:"BR-PLOT-002",name:"Adapter base rejects unimplemented methods",layer:"browser",requirements:["PLT-002"],tier:"standard",run(){P4.assert.throws(()=>new P3.PlotAdapter().initialize());}});
P4.register({id:"BR-UI-001",name:"Critical test controls are reachable",layer:"browser",requirements:["TST-007"],tier:"smoke",run(){for(const id of ["runSelectedButton","runAcceptanceButton","exportButton","resultsBody"])P4.assert.true(!!document.getElementById(id),`Missing ${id}`);}});
