"use strict";
P4.integration={
 async expectError(fn,code){try{await fn();throw new Error(`Expected ${code}`);}catch(e){if(e.message===`Expected ${code}`)throw e;P4.assert.equal(e.code,code);return{code:e.code,message:e.message};}},
 async genericSession(text,chunkSize=5,options={}){const chunks=P2.generic.split(text,chunkSize);return P2.generic.start(text,{chunks,...options});},
 async waitTransferCleanup(timeout=7000){const start=performance.now();while(P2.transfers.size>0&&performance.now()-start<timeout)await new Promise(r=>setTimeout(r,25));return P2.transfers.size;}
};
P4.register({id:"INT-START-001",name:"Browser startup and loaded handshake complete",layer:"integration",requirements:["TST-005"],tier:"smoke",run(){P4.assert.true(P2.hostReady);P4.assert.true(P2.hostVersion.includes("2026.1.0"));return{hostReady:P2.hostReady,hostVersion:P2.hostVersion,startupElapsedMs:performance.now()-P4.runtime.startupAt};}});
P4.register({id:"INT-START-002",name:"Explicit protocol handshake agrees with runtime",layer:"integration",requirements:["PRO-002","TST-005"],tier:"smoke",async run(){const r=await P2.client.request("protocol.handshake.request",{});P4.assert.equal(r.payload.scilab_version,P2.hostVersion);P4.assert.equal(r.payload.minimum_scilab_version,"2026.1.0");return r.payload;}});
P4.register({id:"INT-MSG-001",name:"Bidirectional echo preserves request correlation",layer:"integration",requirements:["PRO-003","PRO-004"],tier:"standard",async run(){const id=P2.client.nextId("integration-echo"),r=await P2.client.request("diagnostic.echo.request",{text:"p4.3",value:4294967296},{requestId:id});P4.assert.equal(r.request_id,id);P4.assert.equal(r.payload.value,4294967296);return{requestId:id,responseType:r.type};}});
P4.register({id:"INT-MSG-002",name:"Host-to-browser notification is routed",layer:"integration",requirements:["PRO-007","PRO-008"],tier:"standard",async run(){let received=null;const type="test.host.notification";P2.router.handlers.delete(type);P2.router.register(type,m=>{received=m;P4.runtime.notifications.push(m);});const r=await P2.client.request("test.host.notification.request",{token:"notify-p43"});await new Promise(x=>setTimeout(x,30));P4.assert.equal(r.payload.sent,true);P4.assert.true(!!received,"Notification not received");P4.assert.equal(received.payload.token,"notify-p43");return{notificationType:received.type,token:received.payload.token};}});
P4.register({id:"INT-MSG-003",name:"Unknown type returns structured error",layer:"integration",requirements:["PRO-006","TST-003"],tier:"standard",async run(){return P4.integration.expectError(()=>P2.client.request("test.unknown.operation",{}),"UNSUPPORTED_TYPE");}});
P4.register({id:"INT-MSG-004",name:"Malformed bridge payload returns callback error",layer:"integration",requirements:["PRO-005","TST-003"],tier:"standard",async run(){const raw=await P2.transport.call([123],3000),r=P2.codec.decode(raw);P4.assert.equal(r.status,"error");P4.assert.equal(r.error.code,"HOST_CALLBACK_EXCEPTION");return{code:r.error.code,responseType:r.type};}});
P4.register({id:"INT-MSG-005",name:"Request succeeds after protocol failures",layer:"integration",requirements:["TST-003"],tier:"standard",async run(){const r=await P2.client.request("diagnostic.echo.request",{text:"recovered"});P4.assert.equal(r.payload.text,"recovered");P4.assert.equal(P2.requests.size,0);return{recovered:true};}});
P4.register({id:"INT-XFR-001",name:"Real ordered generic transfer commits atomically",layer:"integration",requirements:["PRO-010","TST-003"],tier:"standard",async run(){const text="p43-ordered-transfer",r=await P2.generic.send(text,{chunkSize:4}),s=await P2.generic.status();P4.assert.equal(r.type,"transfer.generic.completed");P4.assert.equal(s.payload.committed,text);return{size:r.payload.size,checksum:r.payload.checksum};}});
P4.register({id:"INT-XFR-002",name:"Real out-of-order generic transfer commits",layer:"integration",requirements:["PRO-010","TST-003"],tier:"standard",async run(){const text="p43-out-of-order",session=await P4.integration.genericSession(text,4);for(const i of [...session.chunks.keys()].reverse())await P2.generic.sendChunk(session,i);const r=await P2.generic.complete(session);P4.assert.equal(r.type,"transfer.generic.completed");return{chunks:session.chunks.length};}});
P4.register({id:"INT-XFR-003",name:"Real duplicate chunk is rejected and cancelled",layer:"integration",requirements:["PRO-010","TST-003"],tier:"standard",async run(){const s=await P4.integration.genericSession("duplicate-real",4);await P2.generic.sendChunk(s,0);const e=await P4.integration.expectError(()=>P2.generic.sendChunk(s,0),"DUPLICATE_CHUNK");await P2.generic.cancel(s,"cleanup");const status=await P2.generic.status();P4.assert.equal(status.payload.active,false);return e;}});
P4.register({id:"INT-XFR-004",name:"Incomplete transfer cannot replace committed data",layer:"integration",requirements:["PRO-010","TST-003"],tier:"standard",async run(){const before=(await P2.generic.status()).payload.committed,s=await P4.integration.genericSession("incomplete-real",4);await P2.generic.sendChunk(s,0);const e=await P4.integration.expectError(()=>P2.generic.complete(s),"INCOMPLETE_TRANSFER"),after=(await P2.generic.status()).payload;P4.assert.equal(after.committed,before);P4.assert.equal(after.active,false);return{...e,atomicCommitPreserved:true};}});
P4.register({id:"INT-XFR-005",name:"Whole-transfer checksum failure prevents commit",layer:"integration",requirements:["PRO-010","TST-003"],tier:"standard",async run(){const text="checksum-real",chunks=P2.generic.split(text,4),s=await P2.generic.start(text,{chunks,checksum:P2.generic.checksum(text)+1});for(let i=0;i<chunks.length;i++)await P2.generic.sendChunk(s,i);const e=await P4.integration.expectError(()=>P2.generic.complete(s),"TRANSFER_CHECKSUM_MISMATCH"),status=await P2.generic.status();P4.assert.equal(status.payload.active,false);return e;}});
P4.register({id:"INT-XFR-006",name:"Real numeric transfer completes and registries clean",layer:"integration",requirements:["TRN-002","PRO-009"],tier:"standard",async run(){const h=await P2.numeric.start({viewportId:4301,batchCount:2,valueCount:1000,windowSize:1}),r=await h.promise;P4.assert.equal(r.committed,2);await P4.integration.waitTransferCleanup();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.transfers.size,0);return{received:r.received,committed:r.committed};}});
P4.register({id:"INT-LIFE-001",name:"Host shutdown rejects work and restart recovers",layer:"integration",requirements:["PRO-009","TST-003"],tier:"standard",async run(){const shut=await P2.client.request("protocol.shutdown.request",{});P4.assert.equal(shut.payload.active,false);const e=await P4.integration.expectError(()=>P2.client.request("diagnostic.echo.request",{text:"blocked"}),"LIBRARY_INACTIVE");const init=await P2.client.request("protocol.initialize.request",{library_version:P4.version});P4.assert.equal(init.payload.active,true);const echo=await P2.client.request("diagnostic.echo.request",{text:"restart-ok"});P4.assert.equal(echo.payload.text,"restart-ok");return{shutdown:true,rejection:e.code,restarted:true};}});
P4.register({id:"INT-UI-001",name:"Critical actions remain reachable in current JCEF viewport",layer:"integration",requirements:["TST-007"],tier:"standard",run(){const ids=["runSelectedButton","runAcceptanceButton","stopButton","exportButton","clearButton"];const rows=ids.map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return{id,width:r.width,height:r.height,visible:!!(r.width&&r.height)};});P4.assert.true(rows.every(x=>x.visible));return{viewport:{width:innerWidth,height:innerHeight},controls:rows};}});
P4.register({id:"INT-HEALTH-001",name:"Console and protocol final health are clean",layer:"integration",requirements:["TST-008"],tier:"standard",async run(){await P4.integration.waitTransferCleanup();const gs=await P2.generic.status(),ns=await P2.client.request("transfer.status.request",{});P4.assert.equal(P4.runtime.errors.length,0,`Runtime errors: ${JSON.stringify(P4.runtime.errors)}`);P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.transfers.size,0);P4.assert.equal(gs.payload.active,false);P4.assert.equal(ns.payload.active,false);return{runtimeErrors:P4.runtime.errors,activeRequests:0,activeTransfers:0,genericActive:false,numericActive:false,notifications:P4.runtime.notifications.length};}});
