"use strict";
P4.register({id:"MF-ST-001",name:"Starter manifest declares canonical production entrypoint",layer:"manifest",requirements:["ARC-001","TST-001"],tier:"standard",run(){P4.assert.equal(P4.starterManifest.canonical_starter_launcher,"app/starter_main.sce");P4.assert.equal(P4.starterManifest.production_bundle,"browser_files/dist/bundle.prod.html");return{launcher:P4.starterManifest.canonical_starter_launcher,bundle:P4.starterManifest.production_bundle};}});
P4.register({id:"MF-ST-002",name:"Starter required module paths exist",layer:"manifest",requirements:["ARC-010","TST-006"],tier:"standard",async run(){const r=await P2.client.request("test.build.artifact.inspect.request",{module_paths_text:P4.starterManifest.required_modules.join("|")},{timeoutMs:10000}),v=r.payload;P4.assert.equal(v.missing_modules.length,0);P4.assert.equal(v.existing_module_count,v.declared_module_count);return{declared:v.declared_module_count,existing:v.existing_module_count,missing:v.missing_modules};}});
P4.register({id:"MF-ST-003",name:"Starter profile disables optional test and plotting layers",layer:"manifest",requirements:["ARC-010","TST-006"],tier:"standard",run(){const p=P4.starterManifest.profile;P4.assert.equal(p.build_mode,"production");P4.assert.equal(p.include_plotting,false);P4.assert.equal(p.include_testing,false);P4.assert.equal(p.jcef_debug,false);return p;}});
P4.register({id:"MF-ST-004",name:"Starter production bundle excludes optional and test source",layer:"manifest",requirements:["TST-004","ARC-007"],tier:"standard",async run(){const v=await P4.inspectArtifact();P4.assert.equal(v.forbidden_matches.length,0);P4.assert.true(v.checks.test_api_absent&&v.checks.test_registration_absent&&v.checks.test_controls_absent);return{artifact:v.artifact,checks:v.checks,forbiddenMatches:v.forbidden_matches};}});
P4.register({id:"BR-ST-001",name:"Starter browser extension point is callable",layer:"browser",requirements:["ARC-005","ARC-010"],tier:"standard",run(){P4.assert.true(!!P2.application&&typeof P2.application.ping==="function");return{extension:"P2.application.ping",callable:true};}});
P4.register({id:"BR-ST-002",name:"Release manifest agrees with active runtime identity",layer:"browser",requirements:["TST-008"],tier:"standard",run(){P4.assert.equal(P4.releaseManifest.version,P2.applicationVersion);P4.assert.equal(P4.releaseManifest.regression_baseline,P4.regressionBaseline);P4.assert.equal(P4.releaseManifest.protocol_version,P2.protocolVersion);return{version:P2.applicationVersion,regressionBaseline:P4.regressionBaseline,protocolVersion:P2.protocolVersion};}});
P4.register({id:"INT-ST-001",name:"Starter example operation completes through live bridge",layer:"integration",requirements:["ARC-005","TST-005"],tier:"standard",async run(){const r=await P2.application.ping();P4.assert.equal(r.payload.message,"pong");P4.assert.equal(r.payload.source,"application-owned-handler");return{operation:P4.starterManifest.smoke_operation,message:r.payload.message,source:r.payload.source};}});
P4.register({id:"INT-ST-002",name:"Starter smoke operation leaves clean protocol state",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",async run(){await P2.application.ping();await P4.integration.waitTransferCleanup();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
