"use strict";
P4.register({id:"MF-REL-001",name:"P6.4 release identity and accepted source are declared",layer:"manifest",requirements:["CMP-001","CMP-004"],tier:"standard",run(){const r=P4.p56ReleaseManifest;P4.assert.equal(r.version,"P6.4.0-0.1");P4.assert.equal(r.accepted_source_baseline,"P5.5.0-0.2");P4.assert.equal(r.accepted_source_result.passed,115);return{version:r.version,source:r.accepted_source_baseline};}});
P4.register({id:"MF-REL-002",name:"P6.4 acceptance target preserves and expands baseline",layer:"manifest",requirements:["TST-001","AIG-004"],tier:"standard",run(){const r=P4.p56ReleaseManifest;P4.assert.equal(r.acceptance_target.declared,135);P4.assert.equal(r.acceptance_target.passed,135);P4.assert.true(r.acceptance_target.declared>r.accepted_source_result.declared);return r.acceptance_target;}});
P4.register({id:"MF-REL-003",name:"Upgrade contract preserves application-owned roots",layer:"manifest",requirements:["AIG-001","AIG-003"],tier:"standard",run(){const u=P4.p56UpgradeManifest;P4.assert.true(u.preserve_roots.includes("application/"));P4.assert.true(u.preserve_roots.includes("browser_files/js/application/"));P4.assert.equal(u.rules.application_identity_preserved,true);return{preserveRoots:u.preserve_roots};}});
P4.register({id:"MF-REL-004",name:"Upgrade contract protects generated and foundation boundaries",layer:"manifest",requirements:["AIG-004","AIG-005"],tier:"standard",run(){const u=P4.p56UpgradeManifest;P4.assert.equal(u.rules.protected_foundation_edits_forbidden,true);P4.assert.equal(u.rules.generated_is_primary_source,false);return u.rules;}});
P4.register({id:"MF-REL-005",name:"Build policy declares deterministic ordering and outputs",layer:"manifest",requirements:["BLD-002","BLD-008","BLD-012"],tier:"standard",run(){const b=P4.p56BuildPolicy;P4.assert.equal(b.source_order,"lexicographic_case_insensitive");P4.assert.true(b.outputs.includes("browser_files/dist/bundle.prod.html"));P4.assert.true(b.outputs.includes("browser_files/dist/bundle.test.html"));return{order:b.source_order,outputs:b.outputs};}});
P4.register({id:"MF-REL-006",name:"Release policy requires offline runtime",layer:"manifest",requirements:["BLD-005","CMP-003"],tier:"standard",run(){P4.assert.equal(P4.p56BuildPolicy.offline_runtime,true);return{offlineRuntime:true};}});
P4.register({id:"MF-REL-007",name:"Rollback package is explicit",layer:"manifest",requirements:["AIG-003","AIG-006"],tier:"standard",run(){P4.assert.equal(P4.p56ReleaseManifest.rollback_package,"scilab_jcef_foundation_p5.5.0_v0.2.zip");P4.assert.equal(P4.p56UpgradeManifest.rollback_package,P4.p56ReleaseManifest.rollback_package);return{rollback:P4.p56ReleaseManifest.rollback_package};}});
P4.register({id:"MF-REL-008",name:"Application manifest declares two extension operations",layer:"manifest",requirements:["ARC-005","ARC-010"],tier:"standard",run(){P4.assert.true(P4.applicationManifest.operations.includes("application.example.ping.request"));P4.assert.true(P4.applicationManifest.operations.includes("application.example.sum.request"));return{operations:P4.applicationManifest.operations};}});
