"use strict";
(function(){if(typeof P4==="undefined"||!P4.register)return;
 P4.register({id:"AIPP-M2-001",layer:"browser",requirements:["ARC-010"],tier:"standard",name:"AIPP pyrolist service and host adapter are registered",run(){P4.assert.equal(P2.application.registry.has("aippPyrolist"),true);P4.assert.true(!!P2.application.aippHostAdapter);return{service:true,adapter:true};}});
 P4.register({id:"AIPP-M2-002",layer:"browser",requirements:["TST-001"],tier:"standard",name:"AIPP M2 pyrolist controls exist",run(){const ids=["aippPyrolistButton","aippPyrolistResult"],missing=ids.filter(id=>!document.getElementById(id));P4.assert.equal(missing.length,0);return{missing};}});
 P4.register({id:"AIPP-M2-003",layer:"integration",requirements:["ARC-005","TST-005"],tier:"standard",name:"AIPP pyrolist metadata loads through live bridge",async run(){const p=await P2.application.aippHostAdapter.load({includeFormulations:false});P4.assert.true(p.count>0);P4.assert.equal(p.names.length,p.count);P4.assert.equal(p.source,"application/data/pyrolist.json");return{count:p.count,source:p.source};}});
 P4.register({id:"AIPP-M2-004",layer:"integration",requirements:["ARC-005","TST-005"],tier:"standard",name:"AIPP host adapter loads formulations and installs legacy contract",async run(){const data=await P2.application.aippHostAdapter.load();P4.assert.equal(data.masterPyroNames.length,data.count);P4.assert.true(!!data.masterPyroList[data.masterPyroNames[0]]);const target={},installed=P2.application.aippHostAdapter.installLegacyGlobals(target);P4.assert.equal(target.masterPyroNames.length,data.count);P4.assert.equal(installed.count,data.count);return{count:data.count,legacyState:target.pyroListLoadState};}});
 P4.register({id:"AIPP-M2-005",layer:"integration",requirements:["PRO-011","TST-003"],tier:"standard",name:"AIPP pyrolist rejects invalid include flag",async run(){return P4.integration.expectError(()=>P2.client.request("application.aipp.pyrolist.request",{include_formulations:"yes"}),"INVALID_APPLICATION_PAYLOAD");}});
 P4.register({id:"AIPP-M2-006",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",name:"AIPP pyrolist workflow leaves protocol state clean",async run(){await P2.application.aippHostAdapter.load({includeFormulations:false});await P4.integration.waitTransferCleanup();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
