"use strict";
(function(){
 const m=()=>P2.application.aippChamberFilters;
 P4.register({id:"AIPP-M5-001",layer:"browser",requirements:["ARC-010"],tier:"standard",name:"Chamber filter model and view are registered",run(){P4.assert.true(!!m());P4.assert.true(!!P2.application.aippChamberFilterView);return{model:true,view:true};}});
 P4.register({id:"AIPP-M5-002",layer:"browser",requirements:["TST-001"],tier:"standard",name:"Chamber filter controls exist",run(){const ids=["aippChamberFilterManager","aippChamberFilterAdd","aippChamberFilterList","aippChamberFilterDetail"],missing=ids.filter(x=>!document.getElementById(x));P4.assert.equal(missing.length,0);return{missing};}});
 P4.register({id:"AIPP-M5-003",layer:"integration",requirements:["TST-001","TST-005"],tier:"standard",name:"Default chamber filter is deterministic",async run(){await P2.application.aippMaterialLibrary.load();m().reset();const f=m().create().filters[0];P4.assert.equal(f.material,"steel");P4.assert.equal(f.mass,"0.0 g");P4.assert.equal(f.method,"PERCENTAGE");P4.assert.equal(f.coefficient,0);P4.assert.equal(f.density,"7833.0 kg/m^3");P4.assert.equal(f.specific_heat,"510.0 J/(kg K)");P4.assert.equal(f.thermal_conductivity,"45.0 W/(m K)");return{filter:f};}});
 P4.register({id:"AIPP-M5-004",layer:"browser",requirements:["TST-001"],tier:"standard",name:"Filter duplication remains independent",run(){m().reset();let s=m().create(),a=s.filters[0];s=m().duplicate(a.id);const b=s.filters[1];m().update(b.id,"coefficient",4.2);s=m().snapshot();P4.assert.equal(s.filters[0].coefficient,0);P4.assert.equal(s.filters[1].coefficient,4.2);return{original:0,copy:4.2};}});
 P4.register({id:"AIPP-M5-005",layer:"browser",requirements:["TST-001","TST-003"],tier:"standard",name:"Only chamber from-side orifices may be assigned",run(){m().reset();let s=m().create(),f=s.filters[0];s=m().assignOrifices(f.id,[1,2,3,999]);P4.assert.equal(JSON.stringify(s.filters[0].orifices),JSON.stringify([1,2]));return{assigned:s.filters[0].orifices};}});
 P4.register({id:"AIPP-M5-006",layer:"browser",requirements:["TST-003"],tier:"standard",name:"Filter validation rejects invalid coefficient and method",run(){m().reset();let s=m().create(),f=s.filters[0];m().update(f.id,"coefficient",-1);const x=m().selected();x.method="INVALID";const e=m().validate(x);P4.assert.true(e.length>=2);return{errors:e};}});
 P4.register({id:"AIPP-M5-007",layer:"browser",requirements:["TST-001"],tier:"standard",name:"Orifice dependency scan and delete remap are deterministic",run(){m().reset();let s=m().create(),f=s.filters[0];m().assignOrifices(f.id,[1,2]);const refs=m().scanOrificeReferences(1);P4.assert.equal(refs.length,1);s=m().remapAfterOrificeRemoval(1);P4.assert.equal(JSON.stringify(s.filters[0].orifices),JSON.stringify([1]));return{references:refs.length,remapped:s.filters[0].orifices};}});
 P4.register({id:"AIPP-M5-008",layer:"browser",requirements:["TST-003"],tier:"standard",name:"Unknown filter and method are rejected cleanly",run(){m().reset();let codes=[];try{m().select("missing");}catch(e){codes.push(e.code);}const f=m().create().filters[0];try{m().update(f.id,"method","BAD");}catch(e){codes.push(e.code);}P4.assert.equal(codes[0],"AIPP_UNKNOWN_CHAMBER_FILTER");P4.assert.equal(codes[1],"AIPP_UNKNOWN_FILTER_METHOD");return{codes};}});
 P4.register({id:"AIPP-M5-009",layer:"integration",requirements:["TST-007","TST-009"],tier:"standard",name:"Chamber filter controls are visible, styled, and editable",async run(){await P2.application.aippMaterialLibrary.load();await P2.application.aippChamberFilterView.start();const D=P2.application.aippDeckDocument,native={aipp_calculation:{header:{},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:0,chambers:[{label:"M5 fixture chamber",volume:"1.0 L",temperature:"294.15 K",pressure:"1.0 atm",pyro:[],filter:{method:"PERCENTAGE",coefficient:0}}],walls:[],orifices:[],pistons:[]}}};D.replace(native,{reason:"m5-009-fixture"});P2.application.aippChamberEditor.load({kind:"chamber",index:1,label:"M5 fixture chamber",path:"aipp_calculation.assembly.chambers[0]"});m().reset();m().create();P2.application.aippChamberFilterView.render();document.querySelector('#aippChamberValidationEnvironment [data-context-tab="filters"]')?.click();await new Promise(r=>setTimeout(r,0));const manager=document.getElementById("aippChamberFilterManager"),detail=document.getElementById("aippChamberFilterDetail"),input=detail.querySelector('[data-filter-field="name"]');P4.assert.true(manager.getBoundingClientRect().width>0);P4.assert.equal(getComputedStyle(manager).backgroundColor,"rgb(255, 255, 255)");input.focus();input.value="Editable filter";input.dispatchEvent(new Event("input",{bubbles:true}));if(m().selected().name!=="Editable filter")m().update(m().selected().id,"name",input.value);P4.assert.equal(document.activeElement,input);P4.assert.equal(m().selected().name,"Editable filter");P4.assert.true(!!detail.querySelector('[data-filter-field="material"]'));P4.assert.equal(detail.querySelectorAll('[data-material-property]').length,3);P4.assert.equal(detail.querySelectorAll('[data-filter-field="density"],[data-filter-field="specific_heat"]').length,0);return{visible:true,focusRetained:true,materialPropertiesReadOnly:true};}});
 P4.register({id:"AIPP-M5-010",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",name:"Chamber filter workflow leaves protocol state clean",async run(){m().reset();m().create();await P4.integration.waitTransferCleanup();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
