"use strict";
(function(){
 const svc=()=>P2.application.aippMaterialLibrary;
 P4.register({id:"AIPP-M531-001",layer:"browser",requirements:["ARC-010"],tier:"standard",name:"Runtime material service is registered",run(){P4.assert.true(!!svc());P4.assert.true(typeof svc().load==="function");P4.assert.true(typeof P2.application.aippMaterials==="function");return{service:true,cache:true};}});
 P4.register({id:"AIPP-M531-002",layer:"integration",requirements:["ARC-005","TST-005"],tier:"standard",name:"Material list loads through live bridge at runtime",async run(){svc().clear();const data=await svc().load();P4.assert.equal(data.source,"application/data/material_list.json");P4.assert.equal(data.count,data.names.length);P4.assert.true(data.names.includes("steel"));P4.assert.true(data.names.includes("aluminum"));P4.assert.true(data.names.includes("copper"));return{source:data.source,count:data.count,names:data.names};}});
 P4.register({id:"AIPP-M531-003",layer:"integration",requirements:["TST-001","TST-005"],tier:"standard",name:"Runtime material records retain every supplied property",async run(){const data=await svc().load();for(const name of data.names){P4.assert.true(!!data.materials[name]&&typeof data.materials[name]==="object");P4.assert.equal(Object.keys(data.materials[name]).length,Object.keys(P2.application.aippChamberFilters.materialProperties(name)).length);}P4.assert.equal(data.materials.copper.thermal_conductivity,"401.0 W/(m K)");return{materials:data.names,propertyCounts:Object.fromEntries(data.names.map(n=>[n,Object.keys(data.materials[n]).length]))};}});
 P4.register({id:"AIPP-M531-004",layer:"integration",requirements:["TST-001","TST-009"],tier:"standard",name:"Material property renderer has no fixed property whitelist",async run(){const data=await svc().load(),original=data.materials.steel;data.materials.steel={...original,user_defined_qualification_property:"dynamic value"};const m=P2.application.aippChamberFilters;m.reset();m.create();P2.application.aippChamberFilterView.render();const node=document.querySelector('[data-material-property="user_defined_qualification_property"]');P4.assert.true(!!node);P4.assert.equal(node.textContent,"dynamic value");data.materials.steel=original;m.reset();m.create();P2.application.aippChamberFilterView.render();return{dynamicPropertyRendered:true};}});
 P4.register({id:"AIPP-M531-005",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",name:"Runtime material workflow leaves protocol state clean",async run(){svc().clear();await svc().load();await P4.integration.waitTransferCleanup();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
 P4.register({id:"AIPP-M531-006",layer:"integration",requirements:["CMP-004","TST-008"],tier:"standard",name:"M5.3.1 application identity agrees across runtime boundaries",async run(){const status=await P2.application.aippStatus(),materials=await svc().load();P4.assert.equal(P4.applicationManifest.application_version,P4.applicationManifest.application_version);P4.assert.equal(status.payload.application_version,P4.applicationManifest.application_version);P4.assert.equal(materials.applicationVersion,P4.applicationManifest.application_version);return{manifest:P4.applicationManifest.application_version,status:status.payload.application_version,materials:materials.applicationVersion};}});
})();
