"use strict";
(function(){const L=()=>P2.application.aippDeckLifecycle,D=()=>P2.application.aippDeckDocument;
function preserve(run){const before=D().snapshot();try{return run();}finally{D().replace(before,{markSaved:!before.meta.dirty,reason:"test.restore"});if(before.meta.dirty)D().mutate("test.restore.dirty",function(){});}}
P4.register({id:"AIPP-M82-001",name:"New deck resets to clean untitled document",layer:"browser",requirements:["TST-001"],tier:"standard",run(){return preserve(()=>{const confirmBefore=window.confirm;window.confirm=()=>true;try{D().mutate("test",d=>d.chambers.push({name:"x"}));L().newDeck();}finally{window.confirm=confirmBefore;}const s=D().snapshot();P4.assert.equal(s.document.name,"untitled.json");P4.assert.equal(s.chambers.length,0);P4.assert.equal(s.meta.dirty,false);const workspace=P2.application.aippWorkspace;const activeBefore=workspace&&typeof workspace.current==="function"?workspace.current():null;try{if(workspace&&typeof workspace.select==="function")workspace.select("editor");const labels={aippDeckNew:"New",aippDeckOpen:"Open JSON",aippDeckSave:"Save JSON",aippDeckSaveAs:"Save As"};Object.keys(labels).forEach(id=>{const e=document.getElementById(id);P4.assert.true(!!e);P4.assert.equal(e.textContent.trim(),labels[id]);P4.assert.true(e.getBoundingClientRect().width>0);P4.assert.true(e.getBoundingClientRect().height>0);});}finally{if(activeBefore&&workspace&&typeof workspace.select==="function")workspace.select(activeBefore);}return{name:s.document.name,toolbarLabels:true};});}});
P4.register({id:"AIPP-M82-002",name:"Candidate validation rejects wrong schema atomically",layer:"browser",requirements:["TST-003"],tier:"standard",run(){const before=D().serialize();let code="";try{L().validateCandidate({schema:"wrong",schemaVersion:1});}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_DECK_SCHEMA");P4.assert.equal(D().serialize(),before);return{code};}});
P4.register({id:"AIPP-M82-003",name:"Open service route is registered",layer:"browser",requirements:["PRO-009"],tier:"standard",run(){P4.assert.true(!!P2.application.aippDeckFiles);P4.assert.true(typeof P2.application.aippDeckFiles.open==="function");return{registered:true};}});
P4.register({id:"AIPP-M82-004",name:"Save service route is registered",layer:"browser",requirements:["PRO-009"],tier:"standard",run(){P4.assert.true(typeof P2.application.aippDeckFiles.save==="function");return{registered:true};}});
P4.register({id:"AIPP-M82-005",name:"Deck serialization excludes runtime meta",layer:"browser",requirements:["BLD-012"],tier:"standard",run(){const obj=JSON.parse(D().serialize());P4.assert.true(!Object.prototype.hasOwnProperty.call(obj,"meta"));P4.assert.true(!!obj.aipp_calculation);return{metaExcluded:true,native:true};}});
P4.register({id:"AIPP-M82-006",name:"M8.2 leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
P4.register({id:"AIPP-M82-007",name:"Native AIPP deck is accepted and preserved",layer:"browser",requirements:["TST-001","TST-003","BLD-012"],tier:"standard",run(){const native={aipp_calculation:{header:{title:"fixture"},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:1,chambers:[{label:"Tank",pyro:[{formulation:"X"}],filter:{material:"steel"}}],walls:[],orifices:[],pistons:[]}}};const c=L().validateCandidate(native);D().replace(c,{markSaved:true,reason:"test.native"});const s=D().snapshot();P4.assert.equal(s.chambers.length,1);P4.assert.equal(s.pyros.length,1);P4.assert.equal(s.filters.length,1);P4.assert.equal(JSON.stringify(JSON.parse(D().serialize())),JSON.stringify(native));return{preserved:true};}});
})();
