"use strict";
(function(){const I=()=>P2.application.aippNativeDeckImporter,D=()=>P2.application.aippDeckDocument;
 function fixture(){return {aipp_calculation:{header:{title:"M8.3 fixture",precision:"60.00 L"},auxiliary_files:{},time_specs:{end_time:"0.050 s"},reaction_specs:{},assembly:{tank_id:7,chambers:[{label:"Primary",future_chamber_value:{retained:true},pyro:[{formulation:"generic_pyro",mass:"1.00 g"}],filter:{method:"PERCENTAGE",coefficient:0}}],walls:[],orifices:[],pistons:[],future_assembly_value:"preserve"}},future_root:{enabled:false}};}
 P4.register({id:"AIPP-M83-001",name:"Native deck importer is registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(typeof I().hydrate==="function");return{registered:true};}});
 P4.register({id:"AIPP-M83-002",name:"Native import hydrates supported editor projections",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const h=I().hydrate(fixture(),{name:"fixture.json"});D().replace(h.native,{markSaved:true,reason:"m83.test"});const s=D().snapshot();P4.assert.equal(s.chambers.length,1);P4.assert.equal(s.pyros.length,1);P4.assert.equal(s.filters.length,1);return{chambers:1,pyros:1,filters:1};}});
 P4.register({id:"AIPP-M83-003",name:"Unknown native properties survive deterministic serialization",layer:"browser",requirements:["BLD-012","TST-001"],tier:"standard",run(){D().replace(fixture(),{markSaved:true});const o=JSON.parse(D().serialize());P4.assert.equal(o.future_root.enabled,false);P4.assert.equal(o.aipp_calculation.assembly.future_assembly_value,"preserve");P4.assert.equal(o.aipp_calculation.assembly.chambers[0].future_chamber_value.retained,true);return{preserved:true};}});
 P4.register({id:"AIPP-M83-004",name:"Native precision text survives untouched round trip",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const f=fixture();D().replace(f,{markSaved:true});const o=JSON.parse(D().serialize());P4.assert.equal(o.aipp_calculation.header.precision,"60.00 L");P4.assert.equal(o.aipp_calculation.time_specs.end_time,"0.050 s");return{precisionPreserved:true};}});
 P4.register({id:"AIPP-M83-005",name:"Native structural comparator ignores object key order only",layer:"browser",requirements:["TST-001","BLD-012"],tier:"standard",run(){const a={b:2,a:{y:1,x:0}},b={a:{x:0,y:1},b:2};P4.assert.true(I().structuralEqual(a,b));b.a.x=1;P4.assert.true(!I().structuralEqual(a,b));return{qualified:true};}});
 P4.register({id:"AIPP-M83-006",name:"Invalid native endpoint is rejected atomically",layer:"browser",requirements:["TST-003"],tier:"standard",run(){D().replace(fixture(),{markSaved:true});const before=D().serialize(),bad=fixture();bad.aipp_calculation.assembly.orifices=[{from:1,to:2}];let code="";try{I().hydrate(bad);}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_ORIFICE_ENDPOINT");P4.assert.equal(D().serialize(),before);return{code};}});
 P4.register({id:"AIPP-M83-007",name:"Native import reports preserved extension fields",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const h=I().hydrate(fixture());P4.assert.true(h.diagnostics.length>=1);return{diagnostics:h.diagnostics.length};}});
 P4.register({id:"AIPP-M83-008",name:"M8.3 native workflow leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
