"use strict";
(function(){const A=()=>P2.application.aippTopologyGraphAdapter,D=()=>P2.application.aippDeckDocument;function fixture(){return {aipp_calculation:{header:{},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:2,chambers:[{label:"Combustion Chamber",init_type:"PVT",future:{keep:true},pyro:[{formulation:"A"}],filter:{material:"steel",orifices:[1,2]}},{label:"Tank",init_type:"PVT"}],orifices:[{from:1,to:2,diameter:"3.0 mm"},{from:1,to:2,diameter:"3.25 mm"}],walls:[{left_connection:{chamber_index:1},right_connection:{chamber_index:2}},{left_connection:{chamber_index:2},right_connection:{type:"CONSTANT_HEAT"}}],pistons:[]}}};}
P4.register({id:"AIPP-M84-001",name:"M8.4 topology graph adapter is registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(!!A());return{registered:true};}});
P4.register({id:"AIPP-M84-002",name:"Native chambers hydrate to deterministic graph nodes",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const g=A().build(fixture());P4.assert.equal(g.nodes.filter(n=>n.data.kind==="chamber").length,2);P4.assert.equal(g.nodes[0].data.id,"chamber-1");return{chambers:2};}});
P4.register({id:"AIPP-M84-003",name:"Parallel native orifices remain distinct inline nodes",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const g=A().build(fixture());P4.assert.equal(g.nodes.filter(n=>n.data.kind==="orifice").length,2);P4.assert.equal(g.edges.filter(e=>e.data.kind==="flow").length,4);return{orifices:2,flowEdges:4};}});
P4.register({id:"AIPP-M84-004",name:"Wall chamber associations become dotted graph edges",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const g=A().build(fixture());P4.assert.equal(g.nodes.filter(n=>n.data.kind==="wall").length,2);P4.assert.equal(g.edges.filter(e=>e.data.kind==="association").length,3);return{walls:2,associations:3};}});
P4.register({id:"AIPP-M84-005",name:"Graph elements retain native document paths",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const g=A().build(fixture());P4.assert.equal(g.nodes.find(n=>n.data.id==="orifice-2").data.documentPath,"aipp_calculation.assembly.orifices[1]");return{mapped:true};}});
P4.register({id:"AIPP-M84-006",name:"Layout geometry is transient and excluded from native serialization",layer:"browser",requirements:["BLD-012"],tier:"standard",run(){D().replace(fixture(),{markSaved:true});const text=D().serialize();P4.assert.true(text.indexOf('"position"')<0);P4.assert.true(text.indexOf('"x"')<0);return{transient:true};}});
P4.register({id:"AIPP-M84-007",name:"Unknown chamber siblings survive topology hydration",layer:"browser",requirements:["TST-001"],tier:"standard",run(){D().replace(fixture(),{markSaved:true});A().build();const o=JSON.parse(D().serialize());P4.assert.true(o.aipp_calculation.assembly.chambers[0].future.keep);return{preserved:true};}});
P4.register({id:"AIPP-M84-008",name:"M8.4 canvas API is registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(!!P2.application.aippTopologyCanvas);return{registered:true};}});
P4.register({id:"AIPP-M84-009",name:"Cytoscape graph runtime initializes headlessly",layer:"browser",requirements:["BLD-005","TST-006"],tier:"standard",run(){const r=P2.application.aippGraphRuntime;P4.assert.true(!!r&&r.available());P4.assert.equal(r.version(),"3.33.4");const cy=r.create({headless:true,elements:[{data:{id:"a"}},{data:{id:"b"}},{data:{id:"ab",source:"a",target:"b"}}],layout:{name:"breadthfirst"}});P4.assert.equal(cy.nodes().length,2);P4.assert.equal(cy.edges().length,1);cy.destroy();return{version:r.version(),headless:true};}});
P4.register({id:"AIPP-M84-010",name:"M8.4 topology workflow leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
