"use strict";
(function(){const N=()=>P2.application.aippTopologyNavigation,C=()=>P2.application.aippTopologyCanvas,D=()=>P2.application.aippDeckDocument;
P4.register({id:"AIPP-M85-001",name:"Topology navigation service is registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(!!N());P4.assert.true(typeof N().selectPath==="function");return{registered:true};}});
P4.register({id:"AIPP-M85-002",name:"Topology native paths are deterministic",layer:"browser",requirements:["TST-001"],tier:"standard",run(){P4.assert.equal(N().pathFor("chamber",2),"aipp_calculation.assembly.chambers[1]");P4.assert.equal(N().pathFor("orifice",1),"aipp_calculation.assembly.orifices[0]");return{deterministic:true};}});
P4.register({id:"AIPP-M85-003",name:"Programmatic graph selection resolves native record",layer:"browser",requirements:["TST-001","TST-007"],tier:"standard",run(){const before=D().snapshot(),fixture=D().blankNative(),path="aipp_calculation.assembly.chambers[0]";fixture.aipp_calculation.assembly.chambers=[{label:"M8.5 fixture chamber"}];let selected=null,unsubscribe=()=>{},host=document.getElementById("aippTopologyCanvas"),temporaryHost=false;try{if(!host){host=document.createElement("div");host.id="aippTopologyCanvas";host.setAttribute("data-test-only","AIPP-M85-003");host.style.cssText="position:absolute;left:-10000px;top:-10000px;width:800px;height:600px";document.body.appendChild(host);temporaryHost=true;}D().replace(fixture,{markSaved:true,reason:"m85-selection-fixture"});P4.assert.true(C().render(true));unsubscribe=C().subscribeSelection(detail=>{selected=detail;});P4.assert.true(C().selectPath(path));P4.assert.equal(C().selectedPath,path);P4.assert.true(!!selected&&!!selected.value);P4.assert.equal(selected.selection.path,path);return{path,label:selected.value.label,temporaryHost};}finally{unsubscribe();C().clearSelection();D().replace(before,{markSaved:!before.meta.dirty,reason:"m85-selection-restore"});C().render(true);if(temporaryHost)host.remove();}}});
P4.register({id:"AIPP-M85-004",name:"Unknown topology path is rejected cleanly",layer:"browser",requirements:["TST-003"],tier:"standard",run(){let code="";try{N().selectPath("missing[0]");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_UNKNOWN_TOPOLOGY_PATH");return{code};}});
P4.register({id:"AIPP-M85-005",name:"Clearing graph selection clears navigation state",layer:"browser",requirements:["TST-001"],tier:"standard",run(){N().clear();P4.assert.equal(N().current(),null);P4.assert.equal(C().selectedPath,"");return{cleared:true};}});
P4.register({id:"AIPP-M85-006",name:"M8.5 navigation leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
