"use strict";
(function(){const L=()=>P2.application.aippTopologyLayout,A=()=>P2.application.aippTopologyGraphAdapter;
 function fixture(){const n=P2.application.aippDeckDocument.blankNative(),a=n.aipp_calculation.assembly;a.tank_id=2;a.chambers=[{label:"Source"},{label:"Tank"}];a.orifices=[{label:"Flow",from:1,to:2}];a.walls=[{label:"Wall A",left_connection:{chamber_index:1},right_connection:{chamber_index:2}}];return n;}
P4.register({id:"AIPP-M86-001",name:"Semantic topology layout service is registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(!!L());P4.assert.true(typeof L().apply==="function");return{registered:true};}});
P4.register({id:"AIPP-M86-002",name:"Tank chamber is selected as semantic root",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const n=fixture(),g=A().build(n);P4.assert.equal(L().tankNodeId(n,g),"chamber-2");P4.assert.equal(L().rootId(g,n),"chamber-2");return{root:"chamber-2"};}});
P4.register({id:"AIPP-M86-003",name:"Fallback semantic positions are deterministic",layer:"browser",requirements:["BLD-012","TST-001"],tier:"standard",run(){const n=fixture(),g=A().build(n),a=L().fallbackPositions(g,n),b=L().fallbackPositions(g,n);P4.assert.equal(JSON.stringify(a),JSON.stringify(b));return{deterministic:true};}});
P4.register({id:"AIPP-M86-004",name:"Tank is rightmost in semantic fallback",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const n=fixture(),g=A().build(n),p=L().fallbackPositions(g,n);P4.assert.true(p["chamber-2"].x>p["chamber-1"].x);return{sourceX:p["chamber-1"].x,tankX:p["chamber-2"].x};}});
P4.register({id:"AIPP-M86-005",name:"Orifice is positioned between connected chambers",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const n=fixture(),g=A().build(n),p=L().fallbackPositions(g,n),x=p["orifice-1"].x;P4.assert.true(x>p["chamber-1"].x&&x<p["chamber-2"].x);return{orificeX:x};}});
P4.register({id:"AIPP-M86-006",name:"Wall anchor identifies associated chamber base",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const n=fixture(),g=A().build(n),p={"chamber-1":{x:100,y:200},"chamber-2":{x:500,y:250}},a=L().wallAnchors(g,p)[0];P4.assert.equal(a.x,300);P4.assert.equal(a.y,250);P4.assert.equal(a.linked,2);return a;}});
P4.register({id:"AIPP-M86-007",name:"Semantic layout calculation does not mutate native deck",layer:"browser",requirements:["BLD-012"],tier:"standard",run(){const n=fixture(),before=JSON.stringify(n),g=A().build(n);L().fallbackPositions(g,n);P4.assert.equal(JSON.stringify(n),before);return{transient:true};}});
P4.register({id:"AIPP-M86-008",name:"M8.6 semantic layout leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
