"use strict";
(function(){const M=()=>P2.application.aippNativePropertyInspector,D=()=>P2.application.aippDeckDocument;
 function fixture(){const n=D().blankNative(),a=n.aipp_calculation.assembly;a.chambers=[{label:"Source",custom_precision:"1.234567890123456789"},{label:"Tank"}];a.orifices=[{label:"Flow",from:1,to:2,diameter:"5 mm",extension:{keep:true}}];a.walls=[{label:"Wall",temperature:"300 K",left_connection:{chamber_index:1}}];return n;}
 function select(kind,index,value){M().load({selection:{kind,index,path:`aipp_calculation.assembly.${kind}s[${index-1}]`,label:value.label},value});}
P4.register({id:"AIPP-M87-001",name:"Native property inspector model and view are registered",layer:"browser",requirements:["ARC-010"],tier:"standard",run(){P4.assert.true(!!M());P4.assert.true(!!P2.application.aippNativePropertyInspectorView);return{registered:true};}});
P4.register({id:"AIPP-M87-002",name:"Inspector loads an isolated working copy",layer:"browser",requirements:["TST-001"],tier:"standard",run(){const v={label:"A",nested:{x:1}};select("chamber",1,v);M().set("label","B");P4.assert.equal(v.label,"A");return{isolated:true};}});
P4.register({id:"AIPP-M87-003",name:"Inspector revert restores selected native record",layer:"browser",requirements:["TST-001"],tier:"standard",run(){select("chamber",1,{label:"A"});M().set("label","B");M().revert();const s=M().snapshot();P4.assert.equal(s.working.label,"A");P4.assert.equal(s.dirty,false);return{reverted:true};}});
P4.register({id:"AIPP-M87-004",name:"Inspector apply commits one native record atomically",layer:"browser",requirements:["TST-001","BLD-012"],tier:"standard",run(){D().replace(fixture());const before=D().snapshot().meta.revision;select("chamber",1,D().snapshot().native.aipp_calculation.assembly.chambers[0]);M().set("label","Edited");M().apply();const s=D().snapshot();P4.assert.equal(s.native.aipp_calculation.assembly.chambers[0].label,"Edited");P4.assert.equal(s.meta.revision,before+1);return{revisionDelta:1};}});
P4.register({id:"AIPP-M87-005",name:"Inspector preserves unknown nested native fields",layer:"browser",requirements:["BLD-012"],tier:"standard",run(){D().replace(fixture());const o=D().snapshot().native.aipp_calculation.assembly.orifices[0];select("orifice",1,o);M().set("label","Edited flow");M().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.orifices[0].extension.keep,true);return{preserved:true};}});
P4.register({id:"AIPP-M87-006",name:"Inspector preserves untouched precision text",layer:"browser",requirements:["BLD-012"],tier:"standard",run(){D().replace(fixture());const c=D().snapshot().native.aipp_calculation.assembly.chambers[0];select("chamber",1,c);M().set("label","Edited");M().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.chambers[0].custom_precision,"1.234567890123456789");return{precisionPreserved:true};}});
P4.register({id:"AIPP-M87-007",name:"Inspector rejects invalid orifice endpoints",layer:"browser",requirements:["TST-003"],tier:"standard",run(){D().replace(fixture());const o=D().snapshot().native.aipp_calculation.assembly.orifices[0];select("orifice",1,o);M().set("to",1);let code="";try{M().apply();}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INSPECTOR_VALIDATION_FAILED");P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.orifices[0].to,2);return{code};}});
P4.register({id:"AIPP-M87-008",name:"Inspector apply marks authoritative deck dirty",layer:"browser",requirements:["TST-001"],tier:"standard",run(){D().replace(fixture(),{markSaved:true});const w=D().snapshot().native.aipp_calculation.assembly.walls[0];select("wall",1,w);M().set("label","Edited wall");M().apply();P4.assert.equal(D().snapshot().meta.dirty,true);return{dirty:true};}});
P4.register({id:"AIPP-M87-009",name:"Inspector raw controls exist in production surface",layer:"browser",requirements:["TST-007","TST-009"],tier:"standard",run(){P4.assert.true(!!document.getElementById("aippInspectorBody")||document.getElementById("aippInspectorJson")===null);return{surfaceDeclared:true};}});
P4.register({id:"AIPP-M87-010",name:"M8.7 inspector workflow leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
