"use strict";
(function(){
 const test=(id,name,run)=>P4.register({id,name,layer:"browser",requirements:["TST-001","TST-007","TST-009"],tier:"standard",run});
 const M=()=>P2.application.aippChamberPyros,V=()=>P2.application.aippChamberPyroView,E=()=>P2.application.aippPyroEditor;
 async function fixture(count=1){if(!E().snapshot().names.length)await E().load();const names=E().snapshot().names||[];P4.assert.true(names.length>=Math.min(count,2),"Formulation fixture did not load");M().reset();for(let i=0;i<count;i++)M().create(names[i%names.length]);V().render();return{names,pyro:M().selected()};}
 const normalized=v=>String(V().canonicalText(v)).trim();
 const visibleValue=()=>String(document.querySelector("#aippChamberPyroFormulation + .ts-wrapper .item")?.textContent??"").trim();
 test("AIPP-M88-001","M8.8 editor upgrades existing chamber pyro surface",()=>{P4.assert.true(!!document.getElementById("aippChamberPyroManager"));P4.assert.true(!document.getElementById("aippM88EditorFrame"));return{direct:true};});
 test("AIPP-M88-002","All M8.8 pyro geometry types install defaults",async()=>{const {pyro}=await fixture();for(const type of ["sphere","tablet","wafer","grain","tabular"]){M().setShape(pyro.id,type);P4.assert.equal(M().selected().shape_type,type);}return{types:5};});
 test("AIPP-M88-003","Tabular geometry maintains matched arrays",async()=>{const {pyro}=await fixture();M().setShape(pyro.id,"tabular");const p=M().selected();P4.assert.equal(p.shape.burn_distance.length,p.shape.surface_area.length);return{rows:p.shape.burn_distance.length};});
 test("AIPP-M88-004","Runner normalization prevents missing requirements join failure",()=>{P4.assert.true(Array.isArray(P4.results));return{runnerGuard:true};});
 test("AIPP-M88-005","Tom Select source controls are hidden after enhancement",async()=>{await fixture();const source=document.getElementById("aippChamberPyroFormulation");P4.assert.true(source.classList.contains("tomselected"));P4.assert.equal(getComputedStyle(source).display,"none");return{className:source.className};});
 test("AIPP-M88-006","Formulation and triggering event each render one enhanced control",async()=>{await fixture();const detail=document.getElementById("aippChamberPyroDetail");P4.assert.equal(detail.querySelectorAll("#aippChamberPyroFormulation + .ts-wrapper").length,1);P4.assert.equal(detail.querySelectorAll("#aippTriggerEvent + .ts-wrapper").length,1);return{wrappers:2};});
 test("AIPP-M88-007","Tom Select instances are replaced without duplicate wrappers",async()=>{await fixture();V().render();V().render();const detail=document.getElementById("aippChamberPyroDetail");P4.assert.equal(detail.querySelectorAll("#aippChamberPyroFormulation + .ts-wrapper").length,1);P4.assert.equal(detail.querySelectorAll("#aippTriggerEvent + .ts-wrapper").length,1);return{stable:true};});
 test("AIPP-M88-008","User formulation selection synchronizes model, source, control, visible item, and summary",async()=>{const {names,pyro}=await fixture();const target=normalized(names.find(x=>normalized(x)!==normalized(pyro.formulation)));P4.assert.true(!!target,"Second formulation required");const active=V().enhancedSelectors().formulation;active.setValue(target);P4.assert.equal(normalized(M().selected().formulation),normalized(target));P4.assert.equal(normalized(document.getElementById("aippChamberPyroFormulation").value),normalized(target));P4.assert.equal(normalized(active.getValue()),normalized(target));P4.assert.equal(normalized(visibleValue()),normalized(target));P4.assert.equal(normalized(document.querySelector(".aipp-pyro-row.selected .aipp-pyro-formulation").textContent),normalized(target));return{target};});
 test("AIPP-M88-009","Formulation remains synchronized after full rerender",async()=>{const {names,pyro}=await fixture();const target=normalized(names.find(x=>normalized(x)!==normalized(pyro.formulation)));V().enhancedSelectors().formulation.setValue(target);V().render();P4.assert.equal(normalized(M().selected().formulation),normalized(target));P4.assert.equal(normalized(V().enhancedSelectors().formulation.getValue()),normalized(target));P4.assert.equal(normalized(visibleValue()),normalized(target));return{target};});
 test("AIPP-M88-010","Different pyros retain independent displayed formulations",async()=>{const {names}=await fixture(2);const records=M().snapshot().pyros;P4.assert.equal(records.length,2);const firstId=records[0].id,secondId=records[1].id,firstValue=String(names[0]).trim(),secondValue=String(names.find(x=>String(x).trim()!==firstValue)).trim();P4.assert.true(!!secondValue,"Distinct formulation required");M().assign(firstId,firstValue);M().assign(secondId,secondValue);let state=M().snapshot();P4.assert.equal(String(state.pyros.find(x=>x.id===firstId).formulation).trim(),firstValue);P4.assert.equal(String(state.pyros.find(x=>x.id===secondId).formulation).trim(),secondValue);M().select(secondId);V().render();P4.assert.equal(visibleValue(),secondValue);M().select(firstId);V().render();P4.assert.equal(visibleValue(),firstValue);M().select(secondId);V().render();P4.assert.equal(visibleValue(),secondValue);return{first:firstValue,second:secondValue};});
 test("AIPP-M88-011","Selected formulation hides while search query is active and restores without mutation",async()=>{await fixture();const active=V().enhancedSelectors().formulation,wrapper=active.wrapper,input=active.control_input,item=wrapper.querySelector(".item"),before=normalized(M().selected().formulation);active.setTextboxValue("B7");P4.assert.true(V().setFormulationSearchState(active,"B7"));P4.assert.true(wrapper.classList.contains("aipp-ts-searching"));P4.assert.equal(getComputedStyle(item).display,"none");P4.assert.equal(normalized(input.value),"B7");P4.assert.equal(normalized(M().selected().formulation),before);V().clearFormulationSearchState(active);P4.assert.true(!wrapper.classList.contains("aipp-ts-searching"));P4.assert.equal(normalized(input.value),"");P4.assert.equal(normalized(M().selected().formulation),before);P4.assert.equal(normalized(visibleValue()),before);return{before,query:"B7",searchingHelper:true};});
})();
