"use strict";
(function(){
 const test=(id,name,run)=>P4.register({id,name,layer:"browser",requirements:["TST-001","TST-003","TST-007","TST-009"],tier:"standard",run});
 const M=()=>P2.application.aippChamberPyros,V=()=>P2.application.aippChamberPyroView,E=()=>P2.application.aippPyroEditor;
 async function fixture(){if(!E().snapshot().names.length)await E().load();M().reset();M().create(E().snapshot().names[0]);V().render();return M().selected();}
 const keys=o=>Object.keys(o).sort().join(",");
 test("AIPP-M88-C051-001","Shape selector contains exactly five documented options",async()=>{await fixture();const values=[...document.querySelectorAll("#aippChamberPyroShape option:not(:disabled)")].map(x=>x.value);P4.assert.equal(values.join(","),"sphere,tablet,grain,wafer,tabular");return{values};});
 test("AIPP-M88-C051-002","Unsupported shapes are not newly selectable",async()=>{await fixture();const values=M().supportedShapes();for(const x of ["cylinder","disk","custom"])P4.assert.true(!values.includes(x));return{unsupported:3};});
 test("AIPP-M88-C051-003","Sphere uses radius instead of diameter",async()=>{const p=await fixture();P4.assert.equal(keys(p.shape),"radius");return{shape:p.shape};});
 test("AIPP-M88-C051-004","Sphere dimensions use separate value and unit controls",async()=>{await fixture();const values=document.querySelectorAll('[data-quantity-value="radius"]'),units=document.querySelectorAll('[data-quantity-unit="radius"]');P4.assert.equal(values.length,1);P4.assert.equal(units.length,1);P4.assert.equal(values[0].type,"number");return{separate:true,valueControls:values.length,unitControls:units.length};});
 test("AIPP-M88-C051-005","Tablet exposes the documented field contract",async()=>{const p=await fixture();M().setShape(p.id,"tablet");P4.assert.equal(keys(M().selected().shape),"diameter,dome_height,total_height");return{fields:3};});
 test("AIPP-M88-C051-006","Grain exposes the documented six-field contract",async()=>{const p=await fixture();M().setShape(p.id,"grain");P4.assert.equal(keys(M().selected().shape),"cylinder_height,fin_diameter,fin_thickness,inner_diameter,num_fins,outer_diameter");return{fields:6};});
 test("AIPP-M88-C051-007","Grain fin count is an integer without units",async()=>{const p=await fixture();M().setShape(p.id,"grain");V().render();P4.assert.true(Number.isInteger(M().selected().shape.num_fins));const input=document.querySelector('[data-p="shape.num_fins"]');P4.assert.true(!!input);P4.assert.equal(input.type,"number");P4.assert.equal(input.step,"1");P4.assert.true(!document.querySelector('[data-quantity-unit="num_fins"]'));return{numFins:M().selected().shape.num_fins,step:input.step};});
 test("AIPP-M88-C051-008","Wafer exposes the documented field contract",async()=>{const p=await fixture();M().setShape(p.id,"wafer");P4.assert.equal(keys(M().selected().shape),"height,inner_radius,outer_radius");return{fields:3};});
 test("AIPP-M88-C051-009","Geometry unit changes preserve physical dimensions",async()=>{const p=await fixture();M().update(p.id,"shape.radius","10 mm");M().changeQuantityUnit(p.id,"radius","cm");P4.assert.equal(M().parseQuantity(M().selected().shape.radius).value,1);return{radius:M().selected().shape.radius};});
 test("AIPP-M88-C051-010","Geometry values persist after pyro switching",async()=>{const p=await fixture();M().update(p.id,"shape.radius","0.123456789 mm");const second=M().create(E().snapshot().names[0]).selectedId;M().select(p.id);P4.assert.equal(M().selected().shape.radius,"0.123456789 mm");return{second};});
 test("AIPP-M88-C051-011","Geometry values persist after full rerender",async()=>{const p=await fixture();M().update(p.id,"shape.radius","0.123456789 mm");V().render();P4.assert.equal(M().selected().shape.radius,"0.123456789 mm");return{preserved:true};});
 test("AIPP-M88-C051-012","Tabular import accepts valid two-column CSV",async()=>{const p=await fixture();M().setShape(p.id,"tabular");M().importCsvText(p.id,"mm,mm^2\n0,100\n0.5,82\n1,0");P4.assert.equal(M().selected().shape.burn_distance.length,3);return{rows:3};});
 test("AIPP-M88-C051-013","CSV cancellation does not modify geometry",async()=>{const p=await fixture();M().setShape(p.id,"tabular");const before=JSON.stringify(M().selected().shape);P4.assert.equal(JSON.stringify(M().selected().shape),before);return{unchanged:true};});
 test("AIPP-M88-C051-014","Malformed CSV is atomic",async()=>{const p=await fixture();M().setShape(p.id,"tabular");const before=JSON.stringify(M().selected().shape);try{M().importCsvText(p.id,"not,csv\na,b");}catch(_){}P4.assert.equal(JSON.stringify(M().selected().shape),before);return{unchanged:true};});
 test("AIPP-M88-C051-015","CSV column-count mismatch is rejected",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"mm,mm^2\n0,1,2\n1,0");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_CSV_COLUMNS");return{code};});
 test("AIPP-M88-C051-016","Incorrect CSV unit dimensionality is rejected",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"burn_distance_mm,surface_area_mm\n0,1\n1,0");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_CSV_UNIT");return{code};});
 test("AIPP-M88-C051-017","CSV units differing from GUI selections are rejected",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"cm,cm^2\n0,1\n0.1,0");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_TABULAR_CSV_UNIT_MISMATCH");return{code};});
 test("AIPP-M88-C051-018","First burn distance must be zero",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"mm,mm^2\n1,10\n2,0");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_GEOMETRY");return{code};});
 test("AIPP-M88-C051-019","Final surface area must be zero",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"mm,mm^2\n0,10\n2,1");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_GEOMETRY");return{code};});
 test("AIPP-M88-C051-020","Tabular arrays remain equal in length",async()=>{const p=await fixture();M().setShape(p.id,"tabular");const s=M().parseCsv("mm,mm^2\n0,10\n2,0","mm","mm^2");P4.assert.equal(s.burn_distance.length,s.surface_area.length);return{rows:s.burn_distance.length};});
 test("AIPP-M88-C051-021","Burn distances must increase monotonically",async()=>{const p=await fixture();M().setShape(p.id,"tabular");let code="";try{M().importCsvText(p.id,"mm,mm^2\n0,10\n2,5\n1,0");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_GEOMETRY");return{code};});
 test("AIPP-M88-C051-022","Imported unsupported geometry is preserved but not selectable",async()=>{const p=await fixture(),legacy={geometry:"cylinder",diameter:"10 mm",length:"20 mm",precision:"1.234567890123456789"};M().preserveImportedShape(p.id,legacy);V().render();P4.assert.equal(M().selected().shape.precision,legacy.precision);P4.assert.true(M().selected().unsupported_imported_shape);P4.assert.true(!M().supportedShapes().includes("cylinder"));return{geometry:"cylinder",preserved:true};});
})();
