"use strict";
(function(){
 const test=(n,name,run)=>P4.register({id:`AIPP-M88-P2-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["ARC-010","BLD-012","TST-001","TST-003","TST-007","TST-009"],tier:"standard",run});
 const M=()=>P2.application.aippChamberEditor,D=()=>P2.application.aippDeckDocument;
 function fixture(){const native={aipp_calculation:{header:{},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:0,chambers:[{label:"Phase 2 chamber",volume:"1.2300e-3 m3",temperature:"298.1500 K",pressure:"101325.000 Pa",custom_extension:{keep:"exact"},pyro:[],filter:{method:"PERCENTAGE",coefficient:0}}],walls:[],orifices:[],pistons:[]}}};D().replace(native,{reason:"phase2-fixture"});const sel={kind:"chamber",index:1,label:"Phase 2 chamber",path:"aipp_calculation.assembly.chambers[0]"};M().load(sel);return sel;}
 test(1,"Chamber-scoped working-copy coordinator is registered",async()=>{fixture();P4.assert.true(!!M());return{registered:true};});
 test(2,"Chamber editor composes interactive Properties Pyros Filters and Raw tabs",async()=>{fixture();const root=document.getElementById("aippChamberValidationEnvironment"),buttons=[...root.querySelectorAll("[data-context-tab]")],tabs=buttons.map(x=>x.dataset.contextTab);P4.assert.equal(tabs.join(","),"properties,pyros,filters,raw");for(const button of buttons){button.click();await new Promise(r=>setTimeout(r,0));const visible=[...root.querySelectorAll("[data-context-pane]")].filter(p=>!p.hidden);P4.assert.equal(visible.length,1);P4.assert.equal(visible[0].dataset.contextPane,button.dataset.contextTab);P4.assert.true(button.classList.contains("is-active"));}return{tabs,interactive:true};});
 test(3,"Coordinator reuses existing pyro and filter services",async()=>{fixture();const s=M().snapshot();P4.assert.true(s.services.pyros&&s.services.filters);return{s:s.services};});
 test(4,"Chamber quantity fields retain original text before editing",async()=>{fixture();P4.assert.equal(M().snapshot().working.volume,"1.2300e-3 m3");P4.assert.equal(M().quantity("volume").valueText,"1.2300e-3");return{volume:M().snapshot().working.volume};});
 test(5,"Editing one controlled quantity marks only that field edited",async()=>{fixture();M().setQuantity("temperature","300.0","K");const s=M().snapshot();P4.assert.true(s.dirty);P4.assert.equal(Object.keys(s.editedFields).join(","),"temperature");return{edited:Object.keys(s.editedFields)};});
 test(6,"Revert restores original field precision text",async()=>{fixture();M().setQuantity("pressure","100000","Pa");M().revert();P4.assert.equal(M().snapshot().working.pressure,"101325.000 Pa");return{pressure:M().snapshot().working.pressure};});
 test(7,"Mixture presets require an explicit action",async()=>{fixture();P4.assert.true(M().snapshot().working.mol_fractions===undefined);M().applyMixturePreset("air");P4.assert.true(!!M().snapshot().working.mol_fractions);return{species:Object.keys(M().snapshot().working.mol_fractions).length};});
 test(8,"Unknown mixture preset is rejected cleanly",async()=>{fixture();let code="";try{M().applyMixturePreset("automatic");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_UNKNOWN_MIXTURE_PRESET");return{code};});
 test(9,"Chamber validation rejects negative controlled quantities",async()=>{fixture();M().setQuantity("volume","-1","m3");const errors=M().validate();P4.assert.true(errors.some(x=>x.includes("non-negative")));return{errors};});
 test(10,"Chamber Apply commits atomically and clears dirty state",async()=>{fixture();const before=D().snapshot().meta.revision;M().setQuantity("temperature","300.0","K");M().apply();const after=D().snapshot();P4.assert.equal(after.meta.revision,before+1);P4.assert.true(!M().snapshot().dirty);return{revisionDelta:after.meta.revision-before};});
 test(11,"Editing one field preserves unknown chamber extensions",async()=>{fixture();M().setQuantity("temperature","300.0","K");M().apply();const c=D().snapshot().native.aipp_calculation.assembly.chambers[0];P4.assert.equal(c.custom_extension.keep,"exact");return{preserved:true};});
 test(12,"One-field native round trip preserves untouched precision text",async()=>{fixture();M().setQuantity("temperature","300.0","K");M().apply();const c=D().snapshot().native.aipp_calculation.assembly.chambers[0];P4.assert.equal(c.volume,"1.2300e-3 m3");P4.assert.equal(c.pressure,"101325.000 Pa");return{volume:c.volume,pressure:c.pressure};});
})();
