"use strict";
(function(){
 const M=()=>P2.application.aippChamberPyros,E=()=>P2.application.aippPyroEditor,V=()=>P2.application.aippChamberPyroView;
 const test=(n,name,run)=>P4.register({id:`AIPP-M88-C0611-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["TST-001","TST-003","TST-007"],tier:"standard",run});
 async function fixture(){await E().load();M().reset();const p=M().create(E().snapshot().names[0]).pyros[0];M().setShape(p.id,"tabular");return M().selected();}
 test(1,"Tabular CSV parser accepts GUI-matching units in row one",async()=>{await fixture();const s=M().parseCsv("mm,mm^2\n0,100\n1,0","mm","mm^2");P4.assert.equal(s.burn_distance.length,2);P4.assert.equal(s.burn_distance[1],1);P4.assert.equal(s.surface_area[0],100);return{rows:2};});
 test(2,"Tabular CSV units must exactly match GUI selections",async()=>{await fixture();let code="";try{M().parseCsv("cm,cm^2\n0,1\n1,0","mm","mm^2");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_TABULAR_CSV_UNIT_MISMATCH");return{code};});
 test(3,"Tabular CSV import is atomic when units mismatch",async()=>{const p=await fixture(),before=JSON.stringify(M().selected().shape);let code="";try{M().importCsvText(p.id,"cm,cm^2\n0,1\n1,0","mm","mm^2");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_TABULAR_CSV_UNIT_MISMATCH");P4.assert.equal(JSON.stringify(M().selected().shape),before);return{code,atomic:true};});
 test(4,"Tabular CSV requires numeric values below units row",async()=>{await fixture();let code="";try{M().parseCsv("mm,mm2\nzero,100\n1,0","mm","mm2");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_INVALID_TABULAR_CSV_VALUE");return{code};});
 test(5,"Tabular editor exposes local CSV file chooser",async()=>{await fixture();V().render();const button=document.getElementById("aippGeometryImportCsv"),input=document.getElementById("aippGeometryCsvFile"),help=document.getElementById("aippChamberPyroDetail").textContent;P4.assert.true(!!button);P4.assert.true(!!input);P4.assert.equal(input.accept,".csv,text/csv");P4.assert.true(help.includes("CSV row 1 must contain exactly the selected units"));return{button:true,fileInput:true};});
 test(6,"Surface-area selector exposes only Quaff legal spellings",async()=>{await fixture();V().render();const select=document.getElementById("aippSurfaceAreaUnits"),values=Array.from(select.options).map(x=>x.value);P4.assert.equal(values.join(","),"mm^2,cm^2,m^2");P4.assert.equal(select.value,"mm^2");P4.assert.equal(M().selected().shape.surface_area_units,"mm^2");return{values,defaultValue:select.value};});
 test(7,"Legacy compact area spelling does not satisfy exact CSV match",async()=>{await fixture();let code="";try{M().parseCsv("mm,mm2\n0,100\n1,0","mm","mm^2");}catch(e){code=e.code;}P4.assert.equal(code,"AIPP_TABULAR_CSV_UNIT_MISMATCH");return{code};});
 test(8,"Imported tabular geometry retains Quaff area-unit spelling",async()=>{const p=await fixture();M().importCsvText(p.id,"cm,cm^2\n0,1\n1,0","cm","cm^2");const shape=M().selected().shape;P4.assert.equal(shape.surface_area_units,"cm^2");P4.assert.equal(shape.burn_distance_units,"cm");return{surfaceAreaUnits:shape.surface_area_units};});
})();
