"use strict";
(function(){const M=()=>P2.application.aippChamberPyros,E=()=>P2.application.aippPyroEditor,V=()=>P2.application.aippChamberPyroView;const test=(n,name,run)=>P4.register({id:`AIPP-M88-C0613-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["TST-001","TST-003","TST-007"],tier:"standard",run});async function fixture(){await E().load();M().reset();return M().create(E().snapshot().names[0]).pyros[0];}
test(1,"Burn-rate model switches between power law and table",async()=>{const p=await fixture();M().setBurnModel(p.id,"table");let x=M().selected().burn_rate_modifications;P4.assert.true(Array.isArray(x.pressure_array));P4.assert.equal(x.pressure_units,"MPa");M().setBurnModel(p.id,"power");x=M().selected().burn_rate_modifications;P4.assert.true(!("pressure_array" in x));return{switched:true};});
test(2,"Override and scale modes are mutually exclusive",async()=>{const p=await fixture();M().setBurnMode(p.id,"burn_rate_exponent","override");let x=M().selected().burn_rate_modifications;P4.assert.true("burn_rate_exponent" in x);M().setBurnMode(p.id,"burn_rate_exponent","scale");x=M().selected().burn_rate_modifications;P4.assert.true(!("burn_rate_exponent" in x));P4.assert.equal(x.burn_rate_exponent_scaling,1);return{exclusive:true};});
test(3,"Burn table rows remain matched",async()=>{const p=await fixture();M().setBurnModel(p.id,"table");M().addBurnRow(p.id);let x=M().selected().burn_rate_modifications;P4.assert.equal(x.pressure_array.length,x.burn_rate_array.length);M().removeBurnRow(p.id,0);x=M().selected().burn_rate_modifications;P4.assert.equal(x.pressure_array.length,x.burn_rate_array.length);return{rows:x.pressure_array.length};});
test(4,"Burn-rate editor renders functional conditional controls",async()=>{await fixture();V().render();P4.assert.true(!!document.getElementById("aippBurnRateModel"));const select=document.querySelector("[data-burn-mode=reference_burn_rate]");select.value="override";select.dispatchEvent(new Event("change",{bubbles:true}));P4.assert.true(!!document.querySelector("[data-burn-value=reference_burn_rate]"));return{overrideVisible:true};});
test(5,"Table editor renders unit and row controls",async()=>{const p=await fixture();M().setBurnModel(p.id,"table");V().render();P4.assert.true(!!document.querySelector("[data-burn-field=pressure_units]"));P4.assert.true(!!document.getElementById("aippAddBurnRow"));return{tableVisible:true};});
test(6,"Pyro lifecycle controls render together at top of editor",async()=>{await fixture();V().render();const toolbar=document.querySelector(".aipp-pyro-action-toolbar"),detail=document.getElementById("aippChamberPyroDetail");P4.assert.true(!!toolbar);["aippChamberPyroAdd","aippChamberPyroDuplicate","aippChamberPyroUp","aippChamberPyroDown","aippChamberPyroRemove"].forEach(id=>P4.assert.true(toolbar.contains(document.getElementById(id))));P4.assert.true(detail.firstElementChild===toolbar);P4.assert.true(!document.querySelector(".aipp-editor-actions"));return{topToolbar:true,controls:5};});
})();
