"use strict";
(function(){
 const test=(n,name,run)=>P4.register({id:`AIPP-M88-C083-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["ARC-010","BLD-012","TST-001","TST-003","TST-007","TST-009"],tier:"standard",run});
 const D=()=>P2.application.aippDeckDocument,M=()=>P2.application.aippChamberEditor,F=()=>P2.application.aippChamberFilters;
 function fixture(){const native={aipp_calculation:{header:{},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:0,chambers:[{label:"Candidate 08.3 chamber",volume:"1.0 L",temperature:"298.15 K",pressure:"101.325 kPa",pyro:[],filter:{mass:"76 g",material:"steel",method:"PERCENTAGE",coefficient:0.532,orifices:[1,2]}}],orifices:[{from:1,to:2},{from:1,to:3}],walls:[],pistons:[]}}};D().replace(native,{reason:"candidate083-fixture"});const selection={kind:"chamber",index:1,label:"Candidate 08.3 chamber",path:"aipp_calculation.assembly.chambers[0]"};M().load(selection);return selection;}
 test(1,"Chamber label edits remain in working copy until Apply",()=>{fixture();M().set("label","Qualified label");P4.assert.equal(M().snapshot().working.label,"Qualified label");P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.chambers[0].label,"Candidate 08.3 chamber");M().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.chambers[0].label,"Qualified label");return{applied:true};});
 test(2,"Chamber label Revert restores original text",()=>{fixture();M().set("label","Temporary label");M().revert();P4.assert.equal(M().snapshot().working.label,"Candidate 08.3 chamber");P4.assert.true(!M().snapshot().dirty);return{reverted:true};});
 test(3,"Typing in chamber label preserves the active input node",async()=>{fixture();P2.application.aippChamberEditorView.render(M().snapshot());const input=document.querySelector('[data-chamber-text="label"]');P4.assert.true(!!input);input.focus();const same=input;input.value="Candidate 08.3 chamber X";input.dispatchEvent(new Event("input",{bubbles:true}));await new Promise(r=>setTimeout(r,0));P4.assert.true(document.querySelector('[data-chamber-text="label"]')===same);P4.assert.true(document.activeElement===same);P4.assert.true(M().snapshot().dirty);return{focusPreserved:true};});
 test(4,"Filter mass exposes Quaff-safe mass units",()=>{fixture();const units=F().massUnits();P4.assert.equal(JSON.stringify(units),JSON.stringify(["kg","g"]));return{units};});
 test(5,"Filter mass unit conversion preserves physical mass",()=>{fixture();F().reset();let s=F().create(),id=s.selectedId;F().updateMassValue(id,"76","g");F().changeMassUnit(id,"kg");P4.assert.equal(F().selected().mass,"0.076 kg");F().changeMassUnit(id,"g");P4.assert.equal(F().selected().mass,"76 g");return{mass:F().selected().mass};});
 test(6,"Filter assignment replaces stale orifice indices",()=>{fixture();F().reset();let s=F().create(),id=s.selectedId;F().assignOrifices(id,[1,2]);P4.assert.equal(JSON.stringify(F().selected().orifices),JSON.stringify([1,2]));F().assignOrifices(id,[1]);P4.assert.equal(JSON.stringify(F().selected().orifices),JSON.stringify([1]));return{orifices:F().selected().orifices};});
 test(7,"Filter checkbox synchronization updates chamber working copy exactly",()=>{fixture();F().reset();const s=F().create(),id=s.selectedId;F().assignOrifices(id,[1]);const f=F().selected();M().set("filter",{mass:f.mass,material:f.material,method:f.method,coefficient:f.coefficient,orifices:f.orifices});P4.assert.equal(JSON.stringify(M().snapshot().working.filter.orifices),JSON.stringify([1]));P4.assert.equal(JSON.stringify(D().snapshot().native.aipp_calculation.assembly.chambers[0].filter.orifices),JSON.stringify([1,2]));M().apply();P4.assert.equal(JSON.stringify(D().snapshot().native.aipp_calculation.assembly.chambers[0].filter.orifices),JSON.stringify([1]));return{orifices:[1],atomic:true};});
 test(8,"Complete Pyro and Filter manager contracts are mounted",()=>{const ids=["aippChamberPyroManager","aippChamberPyroCount","aippChamberPyroList","aippChamberPyroDetail","aippChamberPyroErrors","aippChamberFilterManager","aippChamberFilterCount","aippChamberFilterList","aippChamberFilterDetail","aippChamberFilterErrors"];const missing=ids.filter(id=>!document.getElementById(id));P4.assert.equal(missing.length,0,missing.join(","));return{missing};});
 test(9,"Chamber Pyros surface has no manual formulation-load control",()=>{const pane=document.querySelector('[data-context-pane="pyros"]');P4.assert.true(!!pane);P4.assert.equal(pane.querySelectorAll("#aippPyroEditorLoad").length,0);P4.assert.equal([...pane.querySelectorAll("button")].filter(b=>/load formulations/i.test(b.textContent)).length,0);return{manualLoadControls:0};});
 test(10,"Runtime material service is available to chamber filters",()=>{P4.assert.true(!!P2.application.aippMaterialLibrary);P4.assert.true(typeof P2.application.aippMaterialLibrary.load==="function");P4.assert.true(typeof P2.application.aippMaterialLibrary.current==="function");return{registered:true,cached:!!P2.application.aippMaterialLibrary.current()};});
})();
