"use strict";
(function(){const E=()=>P2.application.aippOrificeEditor,D=()=>P2.application.aippDeckDocument,C=()=>P2.application.aippTopologyCanvas;
 function fixture(){const n=D().blankNative(),a=n.aipp_calculation.assembly;a.chambers=[{label:"Source",filter:{mass:"1 g",material:"steel",method:"PERCENTAGE",coefficient:.4,orifices:[1]}},{label:"Tank"},{label:"Alternate"}];a.orifices=[{label:"O",from:1,to:2,diameter:"5.0000 mm",num_orif:1,open:false,one_way:true,viscous_flow_factor:.2,opens_at:"1.0E5 Pa",discharge_coefficient:{basis:"constant",Cd_value:.7},extension:{keep:true}}];return n;}
 function ensureCanvasHost(){if(!document.getElementById("aippTopologyCanvas")){const host=document.createElement("div");host.id="aippTopologyCanvas";host.setAttribute("data-test-only","AIPP-M891");host.style.cssText="position:absolute;left:-10000px;top:-10000px;width:800px;height:600px";document.body.appendChild(host);}}
 function load(){ensureCanvasHost();D().replace(fixture());C().render(true);const v=D().snapshot().native.aipp_calculation.assembly.orifices[0];E().load({selection:{kind:"orifice",nativeIndex:1,index:1,path:"aipp_calculation.assembly.orifices[0]",label:"O"},value:v});}
 function t(n,name,run){P4.register({id:`AIPP-M891-${String(n).padStart(3,"0")}`,name,layer:(n===15||n===45)?"integration":"browser",requirements:(n===15||n===45)?["PRO-009","TST-008"]:["TST-001"],tier:"standard",run});}
 t(1,"Production orifice editor model and view are registered",()=>{P4.assert.true(!!E());P4.assert.true(!!P2.application.aippOrificeEditorView);return{registered:true};});
 t(2,"Orifice editor uses an isolated working copy",()=>{load();E().set("from",2);P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.orifices[0].from,1);return{isolated:true};});
 t(3,"Revert restores the orifice",()=>{load();E().set("num_orif",3);E().revert();P4.assert.equal(E().snapshot().working.num_orif,1);return{reverted:true};});
 t(4,"Apply commits one authoritative revision",()=>{load();const r=D().snapshot().meta.revision;E().set("num_orif",2);E().apply();P4.assert.equal(D().snapshot().meta.revision,r+1);return{revisionDelta:1};});
 t(5,"Unknown fields and precision survive Apply",()=>{load();E().set("one_way",false);E().apply();const o=D().snapshot().native.aipp_calculation.assembly.orifices[0];P4.assert.equal(o.diameter,"5.0000 mm");P4.assert.true(o.extension.keep);return{preserved:true};});
 t(6,"Self-connected endpoints are rejected",()=>{load();E().set("to",1);P4.assert.true(E().snapshot().errors.length>0);return{rejected:true};});
 t(7,"num_orif is one or more",()=>{load();E().set("num_orif",0);P4.assert.true(E().snapshot().errors.length>0);return{rejected:true};});
 t(8,"Cd range is zero through 1.5",()=>{load();E().set("discharge_coefficient.Cd_value",1.5);P4.assert.equal(E().snapshot().errors.length,0);E().set("discharge_coefficient.Cd_value",1.51);P4.assert.true(E().snapshot().errors.length>0);return{max:1.5};});
 t(9,"Viscous factor range is zero through 1.5",()=>{load();E().set("viscous_flow_factor",1.5);P4.assert.equal(E().snapshot().errors.length,0);E().set("viscous_flow_factor",-1);P4.assert.true(E().snapshot().errors.length>0);return{max:1.5};});
 t(10,"Initially open retains opens_at",()=>{load();E().set("open",true);E().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.orifices[0].opens_at,"1.0E5 Pa");return{retained:true};});
 t(11,"Opening pressure is nonnegative",()=>{load();E().replace("opens_at","-1 Pa");P4.assert.true(E().snapshot().errors.length>0);return{rejected:true};});
 t(12,"Lookup arrays validate ordering",()=>{load();E().replace("discharge_coefficient",{basis:"time",time_units:"s",time_array:[0,1],Cd_array:[.7,.6],continuity:"interpolate"});P4.assert.equal(E().snapshot().errors.length,0);E().set("discharge_coefficient.time_array",[1,0]);P4.assert.true(E().snapshot().errors.length>0);return{validated:true};});
 t(13,"Event inventory is model-derived",()=>{load();const e=E().events();P4.assert.true(e.includes("SimStart"));P4.assert.true(e.includes("O1_opened"));return{events:e.length};});
 t(14,"Endpoint change resolves invalid filter assignment",()=>{load();E().set("from",3);P4.assert.equal(E().snapshot().impacts.length,1);E().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.chambers[0].filter.orifices.length,0);return{resolved:true};});
 t(15,"M8.9.1 leaves protocol state clean",()=>{P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};});
 t(16,"Orifice selection exposes dedicated production tabs",()=>{load();const d={selection:{kind:"orifice",nativeIndex:1,index:1,path:"aipp_calculation.assembly.orifices[0]",label:"O"},value:D().snapshot().native.aipp_calculation.assembly.orifices[0]};P2.application.aippOrificeEditorView.render(E().snapshot());const tabs=["opening","discharge"].map(x=>document.querySelector(`[data-context-tab="${x}"]`));P4.assert.true(tabs.every(Boolean));return{tabs:tabs.length};});
 t(17,"Mounted Properties pane uses separate diameter value and unit controls",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector('[data-orifice-quantity-value="diameter"]'));P4.assert.true(!!document.querySelector('[data-orifice-quantity-unit="diameter"]'));return{mounted:true};});
 t(18,"Mounted Opening pane contains opening mode and pressure controls",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector('[data-orifice-opening-mode]'));P4.assert.true(!!document.querySelector('[data-orifice-quantity-value="opens_at"]'));return{mounted:true};});
 t(19,"Mounted Discharge pane contains basis control",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector('[data-orifice-field="discharge_coefficient.basis"]'));return{mounted:true};});

 t(20,"Endpoint selectors show chamber number and label",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());const texts=[...document.querySelector('[data-orifice-field="from"]').options].map(o=>o.textContent);P4.assert.true(texts.includes("1: Source"));P4.assert.true(texts.includes("2: Tank"));return{options:texts};});
 t(21,"Orifice editor mounts shared visual-parity classes",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());const surface=document.querySelector(".aipp-orifice-section.aipp-editor-surface"),grid=surface?.querySelector(".aipp-editor-grid");P4.assert.true(!!surface);P4.assert.true(!!grid);return{surface:true,grid:true};});
 t(22,"Context routing identifies the Orifice editor",()=>{const title=document.getElementById("aippContextTitle");P4.assert.true(!!title);return{titleContract:"Orifice editor"};});

 t(23,"Time-dependent Cd renders a structured editable table",()=>{load();E().set("discharge_coefficient.basis","time");P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector(".aipp-cd-table"));P4.assert.true(!!document.querySelector("[data-orifice-cd-add]"));P4.assert.true(!!document.querySelector("[data-orifice-cd-import]"));P4.assert.true(!document.querySelector("[data-orifice-table]"));return{table:true};});
 t(24,"Cd table rows can be added edited and removed",()=>{load();E().set("discharge_coefficient.basis","time");const n=E().snapshot().working.discharge_coefficient.time_array.length;E().addTableRow();P4.assert.equal(E().snapshot().working.discharge_coefficient.time_array.length,n+1);E().setTableCell(n,"cd",0.7);P4.assert.equal(E().snapshot().working.discharge_coefficient.Cd_array[n],0.7);E().removeTableRow(n);P4.assert.equal(E().snapshot().working.discharge_coefficient.time_array.length,n);return{rows:n};});
 t(25,"Time Cd CSV import is atomic and unit matched",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.time_units","s");E().importCsvText("s,Cd\n0,0.2\n1,0.8");const d=E().snapshot().working.discharge_coefficient;P4.assert.equal(d.time_array.join(","),"0,1");P4.assert.equal(d.Cd_array.join(","),"0.2,0.8");return{rows:2};});
 t(26,"Pressure Cd CSV import uses pressure units",()=>{load();E().set("discharge_coefficient.basis","pressure");E().set("discharge_coefficient.pressure_units","MPa");E().importCsvText("MPa,Cd\n0,0.1\n10,0.9");P4.assert.equal(E().snapshot().working.discharge_coefficient.pressure_array[1],10);return{rows:2};});
 t(27,"Cd CSV mismatch and invalid rows preserve working copy",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.time_units","s");const before=JSON.stringify(E().snapshot().working.discharge_coefficient);let failures=0;for(const csv of ["ms,Cd\n0,0.2\n1,0.8","s,Cd\n1,0.2\n0,0.8","s,Cd\n0,0.2\n1,2"]){try{E().importCsvText(csv);}catch(_){failures++;}P4.assert.equal(JSON.stringify(E().snapshot().working.discharge_coefficient),before);}P4.assert.equal(failures,3);return{failures};});
 t(28,"Cd CSV requires exactly two columns and two data rows",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.time_units","s");let failures=0;for(const csv of ["s,Cd\n0,0.2","s,Cd,extra\n0,0.2,1\n1,0.8,2"]){try{E().importCsvText(csv);}catch(_){failures++;}}P4.assert.equal(failures,2);return{failures};});

 t(29,"Pyro and Cd tables expose the shared tabular CSS contract",()=>{load();E().set("discharge_coefficient.basis","time");P2.application.aippOrificeEditorView.render(E().snapshot());const cd=document.querySelector(".aipp-cd-table.aipp-tabular-table"),tools=document.querySelector(".aipp-cd-table-tools.aipp-tabular-toolbar");P4.assert.true(!!cd);P4.assert.true(!!tools);return{sharedTable:true,sharedToolbar:true};});
 t(30,"Cd table header and CSV help use the selected unit",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.time_units","s");P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(document.querySelector(".aipp-cd-table th").textContent.includes("Time (s)"));P4.assert.true(document.querySelector(".aipp-tabular-help").textContent.includes("s,Cd"));return{unit:"s"};});
 t(31,"Workspace exposes viewport-filling flex layout contract",()=>{const w=document.getElementById("aippWorkspace"),panel=document.getElementById("aippPanelEditor"),frame=document.getElementById("aippEditorFrame");P4.assert.true(!!w&&!!panel&&!!frame);return{workspace:w.className,panel:panel.className,frame:frame.className};});
 t(32,"Shared tabular controls retain accessible labels and buttons",()=>{load();E().set("discharge_coefficient.basis","pressure");P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector('[data-orifice-cd-cell="x"][aria-label]'));P4.assert.true(!!document.querySelector("[data-orifice-cd-add]"));P4.assert.true(!!document.querySelector("[data-orifice-cd-import]"));return{accessible:true};});

 t(33,"Dependent Cd basis initializes continuity and valid rows atomically",()=>{load();E().set("discharge_coefficient.basis","pressure");const d=E().snapshot().working.discharge_coefficient;P4.assert.equal(d.continuity,"discrete");P4.assert.equal(d.pressure_array.length,2);P4.assert.equal(d.Cd_array.length,2);P4.assert.equal(E().snapshot().errors.length,0);return{continuity:d.continuity,rows:2};});
 t(34,"Loaded dependent Cd data normalizes a missing continuity value",()=>{const detail={selection:{kind:"orifice",nativeIndex:1,path:"aipp_calculation.assembly.orifices[0]",label:"Orf 1"},value:{from:1,to:2,diameter:"3 mm",num_orif:1,open:false,one_way:false,viscous_flow_factor:1,opens_at:"0 Pa",discharge_coefficient:{basis:"pressure",pressure_units:"MPa",pressure_array:[0,1],Cd_array:[.2,.4]}}};E().load(detail);const s=E().snapshot();P4.assert.equal(s.working.discharge_coefficient.continuity,"discrete");P4.assert.equal(s.original.discharge_coefficient.continuity,"discrete");P4.assert.equal(s.dirty,false);return{continuity:"discrete",dirty:false};});
 t(35,"Visible continuity selection agrees with coordinator state",()=>{load();E().set("discharge_coefficient.basis","time");P2.application.aippOrificeEditorView.render(E().snapshot());const select=document.querySelector('[data-orifice-field="discharge_coefficient.continuity"]');P4.assert.equal(select.value,E().snapshot().working.discharge_coefficient.continuity);return{value:select.value};});

 t(36,"Pressure-dependent Cd Apply persists the complete native contract",()=>{load();E().set("discharge_coefficient.basis","pressure");E().set("discharge_coefficient.pressure_units","MPa");E().set("discharge_coefficient.continuity","interpolate");E().setTableCell(0,"x",0);E().setTableCell(0,"cd",.25);E().setTableCell(1,"x",10);E().setTableCell(1,"cd",.85);E().apply();const d=D().snapshot().native.aipp_calculation.assembly.orifices[0].discharge_coefficient;P4.assert.equal(d.basis,"pressure");P4.assert.equal(d.pressure_units,"MPa");P4.assert.equal(d.continuity,"interpolate");P4.assert.equal(d.pressure_array.join(","),"0,10");P4.assert.equal(d.Cd_array.join(","),"0.25,0.85");return{basis:d.basis,rows:d.Cd_array.length};});
 t(37,"Time-dependent Cd CSV import survives Apply and reload",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.time_units","s");E().importCsvText("s,Cd\n0,0.1\n0.01,0.9");E().apply();const o=D().snapshot().native.aipp_calculation.assembly.orifices[0];E().load({selection:{kind:"orifice",nativeIndex:1,index:1,path:"aipp_calculation.assembly.orifices[0]",label:"O"},value:o});const d=E().snapshot().working.discharge_coefficient;P4.assert.equal(d.time_array.join(","),"0,0.01");P4.assert.equal(d.Cd_array.join(","),"0.1,0.9");P4.assert.equal(E().snapshot().dirty,false);return{reloaded:true};});
 t(38,"Invalid dependent Cd rows disable the rendered Apply action",()=>{load();E().set("discharge_coefficient.basis","pressure");E().setTableCell(1,"x",0);P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(E().snapshot().errors.includes("Lookup coordinates must be finite and strictly increasing."));const buttons=[...document.querySelectorAll("[data-orifice-apply]")];P4.assert.true(buttons.length>0);P4.assert.true(buttons.every(b=>b.disabled));return{blocked:true};});
 t(39,"Constant Cd remains available after dependent-basis editing",()=>{load();E().set("discharge_coefficient.basis","time");E().set("discharge_coefficient.basis","constant");E().set("discharge_coefficient.Cd_value",.66);P4.assert.equal(E().snapshot().errors.length,0);E().apply();const d=D().snapshot().native.aipp_calculation.assembly.orifices[0].discharge_coefficient;P4.assert.equal(d.basis,"constant");P4.assert.equal(d.Cd_value,.66);return{Cd:d.Cd_value};});
 t(40,"Dependent Cd remove row preserves matched-array lengths",()=>{load();E().set("discharge_coefficient.basis","time");E().addTableRow();E().removeTableRow(1);const d=E().snapshot().working.discharge_coefficient;P4.assert.equal(d.time_array.length,d.Cd_array.length);P4.assert.true(d.time_array.length>=1);return{rows:d.time_array.length};});
 t(41,"Orifice endpoint options retain one-based native values",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());const select=document.querySelector('[data-orifice-field="from"]'),opts=[...select.options];P4.assert.equal(opts[0].value,"0");P4.assert.equal(opts[1].value,"1");P4.assert.equal(opts[1].textContent,"1: Source");P4.assert.equal(opts[2].value,"2");P4.assert.equal(opts[2].textContent,"2: Tank");return{values:opts.map(o=>o.value)};});
 t(42,"Orifice surfaces expose all accepted contextual panes",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector("#aippInspectorBody .aipp-orifice-section"));P4.assert.true(!!document.querySelector("#aippOrificeOpeningPane .aipp-orifice-section"));P4.assert.true(!!document.querySelector("#aippOrificeDischargePane .aipp-orifice-section"));return{properties:true,opening:true,discharge:true};});
 t(43,"CSV errors are reported inline without changing editor state",()=>{load();E().set("discharge_coefficient.basis","pressure");E().set("discharge_coefficient.pressure_units","MPa");const before=JSON.stringify(E().snapshot().working);let code="";try{E().importCsvText("kPa,Cd\n0,.1\n1,.2");}catch(err){code=err.code||"";}P4.assert.equal(code,"AIPP_ORIFICE_CD_CSV_UNIT_MISMATCH");P4.assert.equal(JSON.stringify(E().snapshot().working),before);return{code};});
 t(44,"Apply and Revert state follows dirty and validation state",()=>{load();P2.application.aippOrificeEditorView.render(E().snapshot());let apply=[...document.querySelectorAll("[data-orifice-apply]")],revert=[...document.querySelectorAll("[data-orifice-revert]")];P4.assert.true(apply.every(b=>b.disabled));P4.assert.true(revert.every(b=>b.disabled));E().set("num_orif",2);P2.application.aippOrificeEditorView.render(E().snapshot());apply=[...document.querySelectorAll("[data-orifice-apply]")];revert=[...document.querySelectorAll("[data-orifice-revert]")];P4.assert.true(apply.some(b=>!b.disabled));P4.assert.true(revert.some(b=>!b.disabled));return{dirtyControls:true};});
 t(45,"Completed Orifice workflow leaves document and protocol state clean",()=>{load();E().set("num_orif",2);E().apply();P4.assert.equal(E().snapshot().dirty,false);P4.assert.equal(E().snapshot().errors.length,0);P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{dirty:false,activeRequests:0,activeTransfers:0};});

 t(46,"Qualification document remains vertically scrollable",()=>{const bodyStyle=getComputedStyle(document.body),htmlStyle=getComputedStyle(document.documentElement);P4.assert.true(bodyStyle.overflowY!=="hidden"&&bodyStyle.overflow!=="hidden");P4.assert.true(htmlStyle.overflowY!=="hidden"&&htmlStyle.overflow!=="hidden");return{bodyOverflow:bodyStyle.overflowY||bodyStyle.overflow,htmlOverflow:htmlStyle.overflowY||htmlStyle.overflow};});
 t(47,"Production workspace retains viewport containment without locking the document",()=>{const w=document.getElementById("aippWorkspace");P4.assert.true(!!w);const style=getComputedStyle(w);P4.assert.equal(style.overflow,"hidden");P4.assert.true(parseFloat(style.height)>0);P4.assert.true(getComputedStyle(document.body).overflow!=="hidden");return{workspaceOverflow:style.overflow,height:style.height};});
 t(48,"Qualification workspace fixture mounts the complete Orifice pane contract",()=>{const ids=["aippWorkspace","aippEditorFrame","aippInspectorBody","aippOrificeOpeningPane","aippOrificeDischargePane","aippInspectorJson"];const missing=ids.filter(id=>!document.getElementById(id));P4.assert.equal(missing.length,0);P4.assert.equal(document.querySelectorAll('[data-context-tab="opening"],[data-context-tab="discharge"]').length,2);return{missing,tabs:2};});
 t(49,"Endpoint dependency cleanup uses a valid alternate chamber",()=>{load();E().set("from",3);const s=E().snapshot();P4.assert.equal(s.errors.length,0);P4.assert.equal(s.impacts.length,1);E().apply();P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.chambers[0].filter.orifices.length,0);return{from:3,cleaned:true};});

})();
