"use strict";
(function(){const E=()=>P2.application.aippWallEditor,D=()=>P2.application.aippDeckDocument,cp=v=>JSON.parse(JSON.stringify(v));
 function native(){const n=D().blankNative(),a=n.aipp_calculation.assembly;a.chambers=[{label:"Combustion Chamber"},{label:"Tank"}];a.walls=[{label:"Wall 1",temperature:"294.150000 K",area:"9.6770000E+1 cm^2",thickness:"2.000000 mm",material:"steel",left_connection:{type:"VARIABLE_COEFFICIENT",chamber_index:1,scale_factor:2.9,custom_correlation:"internal"},right_connection:{type:"CONSTANT_COEFFICIENT",chamber_index:2,heat_transfer_coefficient:"50 W/(m^2 K)"},vendor_extension:{model:"custom"}},{label:"Wall 2",temperature:"300 K",area:"100 cm^2",thickness:"3 mm",material:"aluminum",left_connection:{type:"WALL",wall_index:1},right_connection:{type:"CONSTANT_TEMPERATURE",temperature:"294.15 K"}},{label:"Wall 3",temperature:"300 K",area:"100 cm^2",thickness:"4 mm",material:"steel",left_connection:{type:"WALL",wall_index:2},right_connection:{type:"CONSTANT_HEAT",heat:"0 W"}}];return n}
 function detail(i=1){const w=D().snapshot().native.aipp_calculation.assembly.walls[i-1];return{selection:{kind:"wall",nativeIndex:i,index:i,path:`aipp_calculation.assembly.walls[${i-1}]`,label:w.label},value:w}}
 function load(i=1){D().replace(native(),{markSaved:true});return E().load(detail(i))}
 function reopen(name="roundtrip.json"){const parsed=JSON.parse(D().serialize()),h=P2.application.aippNativeDeckImporter.hydrate(parsed,{name,path:"/tmp/"+name});D().replace(h.native,{markSaved:true,reason:"test.reopen"});const walls=D().snapshot().native.aipp_calculation.assembly.walls;P4.assert.true(Array.isArray(walls),"Reopened native deck must contain a Wall array.");P4.assert.true(walls.length>0,"Reopened native deck must retain Wall records.");return walls}
 function reg(i,name,run,layer="browser"){P4.register({id:`AIPP-M892-${String(i).padStart(3,"0")}`,name,layer,requirements:layer==="integration"?["PRO-009","TST-008"]:["TST-001","TST-003","TST-007","BLD-012"],tier:"standard",run})}
 reg(1,"Wall editor coordinator and view are registered",()=>{P4.assert.true(!!E());P4.assert.true(!!P2.application.aippWallEditorView);return{registered:true}});
 reg(2,"Wall editor uses isolated working copies",()=>{load();E().set("material","aluminum");P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.walls[0].material,"steel");return{isolated:true}});
 reg(3,"Wall Apply preserves unknown fields and precision",()=>{load();E().set("material","aluminum");E().apply();let w=D().snapshot().native.aipp_calculation.assembly.walls[0];P4.assert.equal(w.temperature,"294.150000 K");P4.assert.true(w.vendor_extension.model==="custom");return{preserved:true}});
 reg(4,"Wall Apply commits one revision",()=>{load();let r=D().snapshot().meta.revision;E().set("material","aluminum");E().apply();P4.assert.equal(D().snapshot().meta.revision,r+1);return{delta:1}});
 reg(5,"Wall Revert restores complete working copy",()=>{load();E().setConnectionType("left","CONSTANT_HEAT");E().revert();P4.assert.equal(E().snapshot().working.left_connection.type,"VARIABLE_COEFFICIENT");return{reverted:true}});
 reg(6,"Five Wall boundary types are supported",()=>{load();for(const t of E().types()){E().setConnectionType("right",t);P4.assert.equal(E().snapshot().working.right_connection.type,t)}return{types:5}});
 reg(7,"Wall quantities accept Quaff units",()=>{load();P4.assert.equal(E().snapshot().errors.length,0);return{valid:true}});
 reg(8,"Wall geometry rejects nonpositive values",()=>{load();E().set("thickness","0 mm");P4.assert.true(E().snapshot().errors.length>0);return{rejected:true}});
 reg(9,"Wall self reference is rejected",()=>{load();E().setConnectionType("left","WALL");E().set("left_connection.wall_index",1);P4.assert.true(E().snapshot().errors.some(x=>x.includes("cannot reference")));return{rejected:true}});
 reg(10,"Wall cycles are rejected",()=>{load();E().setConnectionType("left","WALL");E().set("left_connection.wall_index",2);P4.assert.true(E().snapshot().errors.some(x=>x.includes("cycle")));return{rejected:true}});
 reg(11,"Wall view renders three simultaneous cards",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());P4.assert.equal(document.querySelectorAll(".aipp-wall-grid>.aipp-wall-card").length,3);return{cards:3}});
 reg(12,"Wall view exposes both boundary controls",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());P4.assert.equal(document.querySelectorAll("[data-wall-connection-type]").length,2);return{boundaries:2}});
 reg(13,"Wall references are numbered",()=>{load();E().setConnectionType("right","WALL");P2.application.aippWallEditorView.render(E().snapshot());P4.assert.true(document.body.textContent.includes("2: Wall 2"));return{numbered:true}});
 reg(14,"Wall raw working copy is expandable",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());P4.assert.true(document.querySelector(".aipp-wall-raw pre").textContent.includes("left_connection"));return{raw:true}});
 reg(15,"Wall workflow leaves protocol state clean",()=>{load();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{clean:true}},"integration");
 reg(16,"Wall mode hides redundant contextual chrome",()=>{load();let c=document.getElementById("aippContextEditor");c.classList.add("is-wall-mode");try{P4.assert.equal(getComputedStyle(c.querySelector(".aipp-context-tabs")).display,"none");}finally{c.classList.remove("is-wall-mode");}return{hidden:true}});
 reg(17,"Wall editor omits duplicate thermal path strip",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());P4.assert.true(!document.querySelector(".aipp-wall-flow"));return{omitted:true}});
 reg(18,"Expandable Raw is the sole Wall raw surface",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());P4.assert.true(!!document.querySelector(".aipp-wall-raw"));return{sole:true}});
 reg(19,"Quaff power conversion supports Wall units",()=>{let u=P2.application.aippQuaffUnits;P4.assert.true(Math.abs(u.convert("power",100,"W","BTU/h")-341.2141633)<1e-5);P4.assert.true(Math.abs(u.convert("power",1,"MBTU/h","W")-293071.0701722222)<1e-8);return{power:true}});
 reg(20,"Quaff coefficient conversion supports imperial units",()=>{let u=P2.application.aippQuaffUnits;P4.assert.true(Math.abs(u.convert("heat_transfer_coefficient",50,"W/(m^2 K)","BTU/(hr ft^2 F)")-8.80550919)<1e-6);return{coefficient:true}});
 reg(21,"Left boundary heat unit change converts displayed value",()=>{load();E().setConnectionType("left","CONSTANT_HEAT");E().set("left_connection.heat","100 W");P2.application.aippWallEditorView.render(E().snapshot());let x=document.querySelector('[data-wall-quantity-unit="left_connection.heat"]');x.value="BTU/h";x.onchange();P4.assert.true(E().snapshot().working.left_connection.heat.startsWith("341.214"));return{converted:true}});
 reg(22,"Right boundary coefficient unit change converts displayed value",()=>{load();P2.application.aippWallEditorView.render(E().snapshot());let x=document.querySelector('[data-wall-quantity-unit="right_connection.heat_transfer_coefficient"]');x.value="BTU/(hr ft^2 F)";x.onchange();P4.assert.true(E().snapshot().working.right_connection.heat_transfer_coefficient.startsWith("8.8055"));return{converted:true}});
 reg(23,"Complete Wall edits survive serialize and reopen",()=>{load();E().set("temperature","310 K");E().set("area","120 cm^2");E().set("thickness","2.5 mm");E().set("material","aluminum");E().setConnectionType("left","CONSTANT_HEAT");E().set("left_connection.heat","25 W");E().setConnectionType("right","CONSTANT_TEMPERATURE");E().set("right_connection.temperature","320 K");E().apply();let w=reopen()[0];P4.assert.equal(w.temperature,"310 K");P4.assert.equal(w.area,"120 cm^2");P4.assert.equal(w.thickness,"2.5 mm");P4.assert.equal(w.material,"aluminum");P4.assert.equal(w.left_connection.heat,"25 W");P4.assert.equal(w.right_connection.temperature,"320 K");return{roundTrip:true}});
 reg(24,"All boundary subtypes survive serialization",()=>{for(const t of E().types()){if(t==="WALL"){const n=native();n.aipp_calculation.assembly.walls[1].left_connection={type:"CONSTANT_TEMPERATURE",temperature:"300 K"};D().replace(n,{markSaved:true});E().load(detail(1))}else load();E().setConnectionType("right",t);if(t==="WALL")E().set("right_connection.wall_index",2);E().apply();P4.assert.equal(reopen()[0].right_connection.type,t)}return{types:5}});
 reg(25,"Converted heat rate survives reopen",()=>{load();E().setConnectionType("left","CONSTANT_HEAT");E().set("left_connection.heat","341.2141633 BTU/h");E().apply();let v=reopen()[0].left_connection.heat;P4.assert.equal(v,"341.2141633 BTU/h");return{value:v}});
 reg(26,"Converted coefficient survives reopen",()=>{load();E().set("right_connection.heat_transfer_coefficient","8.80550919 BTU/(hr ft^2 F)");E().apply();let v=reopen()[0].right_connection.heat_transfer_coefficient;P4.assert.equal(v,"8.80550919 BTU/(hr ft^2 F)");return{value:v}});
 reg(27,"Untouched quantity precision survives reopen",()=>{load();E().set("material","aluminum");E().apply();let w=reopen()[0];P4.assert.equal(w.temperature,"294.150000 K");P4.assert.equal(w.area,"9.6770000E+1 cm^2");P4.assert.equal(w.thickness,"2.000000 mm");return{precision:true}});
 reg(28,"Unknown nested Wall extensions survive reopen",()=>{load();E().set("material","aluminum");E().apply();let w=reopen()[0];P4.assert.equal(w.vendor_extension.model,"custom");P4.assert.equal(w.left_connection.custom_correlation,"internal");return{extensions:true}});
 reg(29,"Multiple Walls remain independent after reopen",()=>{load(1);E().set("material","aluminum");E().apply();E().load(detail(2));E().set("material","steel");E().apply();let w=reopen();P4.assert.equal(w[0].material,"aluminum");P4.assert.equal(w[1].material,"steel");P4.assert.equal(w[0].label,"Wall 1");P4.assert.equal(w[1].label,"Wall 2");return{independent:true}});
 reg(30,"Composite Wall references survive reopen",()=>{load();let w=reopen();P4.assert.equal(w[1].left_connection.wall_index,1);P4.assert.equal(w[2].left_connection.wall_index,2);P4.assert.equal(P2.application.aippWallEditor.validate(w[0],1).length,0);return{chain:[1,2]}});
 reg(31,"Reverted Wall edits are not serialized",()=>{load();E().set("material","aluminum");E().revert();let w=reopen()[0];P4.assert.equal(w.material,"steel");return{notPersisted:true}});
 reg(32,"Discarded unapplied Wall edits are not serialized",()=>{load();E().set("material","aluminum");D().replace(D().snapshot().native,{markSaved:true,reason:"discard"});let w=reopen()[0];P4.assert.equal(w.material,"steel");return{discarded:true}});
 reg(33,"Cancelled save is atomic for Wall document state",async()=>{load();E().set("material","aluminum");E().apply();let before=D().serialize(),old=P2.application.aippDeckFiles;P2.application.aippDeckFiles={save:async()=>({payload:{cancelled:true}})};try{let ok=await P2.application.aippDeckLifecycle.saveDeck(false);P4.assert.equal(ok,false);P4.assert.equal(D().serialize(),before);P4.assert.equal(D().snapshot().meta.dirty,true);return{cancelled:true,atomic:true}}finally{P2.application.aippDeckFiles=old}});
 reg(34,"Persistence workflow leaves request and transfer state clean",()=>{load();E().set("material","aluminum");E().apply();reopen();P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0}},"integration");
})();
