"use strict";
(function(){
 const H=()=>P2.application.aippTopologyHoverCard,D=()=>P2.application.aippDeckDocument,C=()=>P2.application.aippTopologyCanvas;
 function fixture(){const n=D().blankNative(),a=n.aipp_calculation.assembly;a.tank_id=2;a.chambers=[{label:"A very long combustion chamber label used to verify wrapping",pyro:Array.from({length:8},(_,i)=>({label:`Pyro ${i+1}`,formulation:`FORMULATION_${i+1}_WITH_A_LONG_NAME`,mass:`${i+1}.000 g`,piles:i+1,ignition_time:{triggering_event:"SimStart",time_delay:`${i} ms`}})),filter:{label:"Long filter label",material:"steel",mass:"76 g",method:"PERCENTAGE",orifices:[1,2]}},{label:"Tank"}];a.orifices=[{label:"Constant Cd",from:1,to:2,diameter:"3.25 mm",num_orif:6,open:false,one_way:false,viscous_flow_factor:1,opens_at:"15 MPa",discharge_coefficient:{basis:"constant",Cd_value:.8}},{label:"Pressure table",from:1,to:2,diameter:"2 mm",num_orif:2,open:true,one_way:true,viscous_flow_factor:.5,opens_at:"SimStart + 0 ms",discharge_coefficient:{basis:"pressure",pressure:["1 MPa","5 MPa","10 MPa"],Cd_value:[.2,.6,.9]}}];a.walls=[{label:"All chamber boundaries",temperature:"294.15 K",area:"0.025 m^2",thickness:"1.2 mm",material:"steel",left_connection:{type:"VARIABLE_COEFFICIENT",chamber_index:1,scale_factor:1.5},right_connection:{type:"CONSTANT_COEFFICIENT",chamber_index:2,heat_transfer_coefficient:"200 W/(m^2 K)"}},{label:"Terminal boundaries",temperature:"300 K",area:"0.1 m^2",thickness:"2 mm",material:"aluminum",left_connection:{type:"CONSTANT_TEMPERATURE",temperature:"294.15 K"},right_connection:{type:"CONSTANT_HEAT",heat:"0 W"}},{label:"Wall reference",temperature:"300 K",area:"0.1 m^2",thickness:"3 mm",material:"steel",left_connection:{type:"WALL",wall_index:2},right_connection:{type:"CONSTANT_HEAT",heat:"10 W"}}];return n}
 function reg(n,name,run){P4.register({id:`AIPP-M810-CLOSE-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["TST-001","TST-007","TST-009","BLD-012"],tier:"standard",run})}
 reg(1,"One reusable hover-card DOM instance is enforced",()=>{H().close();document.querySelectorAll("#aippTopologyHoverCard").forEach(x=>x.remove());H().bind();const d=H().diagnostics();P4.assert.true(d.cardCount<=1);return d});
 reg(2,"Long Chamber content and many Pyros render without native mutation",()=>{D().replace(fixture());const before=D().serialize(),a=D().snapshot().native.aipp_calculation.assembly,html=H().content("chamber",a.chambers[0],1);P4.assert.true(html.includes("Pyro 8"));P4.assert.true(html.includes("Long filter label"));P4.assert.equal(D().serialize(),before);return{pyros:8,unchanged:true}});
 reg(3,"Constant and tabular Orifice summaries are compact",()=>{D().replace(fixture());const a=D().snapshot().native.aipp_calculation.assembly,c=H().content("orifice",a.orifices[0],1),t=H().content("orifice",a.orifices[1],2);P4.assert.true(c.includes("0.8"));P4.assert.true(t.includes("Table points"));P4.assert.true(t.includes("3"));return{constant:true,tablePoints:3}});
 reg(4,"All supported Wall boundary summaries resolve",()=>{D().replace(fixture());const a=D().snapshot().native.aipp_calculation.assembly,html=a.walls.map((w,i)=>H().content("wall",w,i+1)).join(" ");for(const token of ["Variable Coefficient","Constant Coefficient","Constant Temperature","Constant Heat","Wall 2: Terminal boundaries"])P4.assert.true(html.includes(token),token);return{boundaryTypes:5}});
 reg(5,"Presentation switch closes the reusable hover card",()=>{window.dispatchEvent(new CustomEvent("aipp:topology-presentation-changed",{detail:{mode:"current"}}));P4.assert.equal(H().diagnostics().visible,false);return{closed:true}});
 reg(6,"Document replacement closes stale hover content",()=>{D().replace(fixture());P4.assert.equal(H().diagnostics().visible,false);return{closed:true}});
 reg(7,"Hover summary generation preserves serialization revision and dirty state",()=>{D().replace(fixture(),{markSaved:true});const pre=D().snapshot(),before=D().serialize(),a=pre.native.aipp_calculation.assembly;H().content("chamber",a.chambers[0],1);H().content("orifice",a.orifices[0],1);H().content("wall",a.walls[0],1);const post=D().snapshot();P4.assert.equal(D().serialize(),before);P4.assert.equal(post.meta.revision,pre.meta.revision);P4.assert.equal(post.meta.dirty,pre.meta.dirty);return{serialization:true,revision:true,dirty:true}});
 reg(8,"Hover service exposes deterministic lifecycle diagnostics",()=>{const d=H().diagnostics();P4.assert.true(typeof d.openCount==="number");P4.assert.true(typeof d.closeCount==="number");P4.assert.true(d.cardCount<=1);return d});
})();
