"use strict";
(function(){const A=P2.application,D=()=>A.aippDeckDocument,E=()=>A.aippPistonEditor,G=()=>A.aippTopologyGraphAdapter;function fixture(){const d=D().blankNative();d.aipp_calculation.assembly.chambers=[{label:"Left"},{label:"Right"}];d.aipp_calculation.assembly.pistons=[{label:"Primary",mass:{basis:"constant",mass:"100.00 g"},left_connection:{chamber_idx:1,area_law:{basis:"constant",surface_area:"100.0 mm^2"},max_displacement:"100.0 mm"},right_connection:{chamber_idx:2,area_law:{basis:"constant",surface_area:"100.0 mm^2"},max_displacement:"100.0 mm"},left_damping_force:{},right_damping_force:{},body_forces:[],travel_units:"mm",travel_targets:[],future_extension:{keep:true}}];D().replace(d,{markSaved:true});return d;}function load(){fixture();return E().load({selection:{kind:"piston",nativeIndex:1,index:1,path:"aipp_calculation.assembly.pistons[0]"}});}function reg(id,name,layer,req,run){P4.register({id,name,layer,requirements:req,tier:"standard",run});}
reg("AIPP-P21-001","P2.1 piston editor coordinator and view are registered","browser",["ARC-010","TST-001"],()=>{P4.assert.true(!!E());P4.assert.true(!!A.aippPistonEditorView);return{registered:true}});
reg("AIPP-P21-002","Piston graph projection creates inline node and directional links","browser",["TST-001"],()=>{const g=G().build(fixture());P4.assert.equal(g.nodes.filter(x=>x.data.kind==="piston").length,1);P4.assert.equal(g.edges.filter(x=>x.data.kind==="piston-link").length,2);return{pistons:1,links:2}});
reg("AIPP-P21-003","Piston graph node retains deterministic native path","browser",["TST-001","BLD-012"],()=>{const n=G().build(fixture()).nodes.find(x=>x.data.kind==="piston");P4.assert.equal(n.data.documentPath,"aipp_calculation.assembly.pistons[0]");return{path:n.data.documentPath}});
reg("AIPP-P21-004","Piston editor loads isolated working copy","browser",["TST-001","BLD-012"],()=>{load();E().set("label","Working");P4.assert.equal(D().snapshot().native.aipp_calculation.assembly.pistons[0].label,"Primary");return{isolated:true}});
reg("AIPP-P21-005","Piston Revert restores complete native working record","browser",["TST-001"],()=>{load();E().set("label","Working");E().revert();P4.assert.equal(E().snapshot().working.label,"Primary");return{reverted:true}});
reg("AIPP-P21-006","Piston Apply commits one authoritative revision","browser",["TST-001","BLD-012"],()=>{load();const n=D().snapshot().meta.revision;E().set("label","Applied");E().apply();P4.assert.equal(D().snapshot().meta.revision-n,1);return{revisionDelta:1}});
reg("AIPP-P21-007","Piston Apply preserves unknown fields and untouched precision","browser",["TST-001","BLD-012"],()=>{load();E().set("label","Applied");E().apply();const p=D().snapshot().native.aipp_calculation.assembly.pistons[0];P4.assert.equal(p.mass.mass,"100.00 g");P4.assert.equal(p.future_extension.keep,true);return{preserved:true}});
reg("AIPP-P21-008","Mounted piston shell exposes three columns and raw working copy","browser",["TST-007","TST-009"],()=>{load();A.aippPistonEditorView.render();P4.assert.true(!!document.querySelector(".p22-columns"));P4.assert.equal(document.querySelectorAll(".p22-columns> *").length,3);P4.assert.true(!!document.querySelector(".aipp-piston-raw"));return{columns:3,raw:true}});
reg("AIPP-P21-009","Piston collection actions retain stable editor identities","browser",["TST-001"],()=>{load();const id=E().snapshot().selectedId;E().duplicate();E().move(-1);P4.assert.true(!!E().snapshot().items.some(x=>x.id===id));return{stable:true}});
reg("AIPP-P21-010","P2.1 leaves protocol state clean","integration",["PRO-009","TST-008"],()=>{P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0}});})();
