"use strict";
(function(){
 const P=()=>P2.application.aippChamberPyros,F=()=>P2.application.aippChamberFilters;
 function pyros(){return [1,2,3].map(i=>({id:`native-pyro-${String(i).padStart(4,"0")}`,name:`Pyro ${i}`,formulation:`FORM_${i}`,quantity_type:"mass",mass_g:i,mass_unit:"g",number:1,piles:i,ignition:{triggering_event:"SimStart",delay_s:0,delay_unit:"s"},shape_type:"sphere",shape:{radius:"0.1 mm"},burn_rate_modifications:{},unknown:{i}}));}
 P4.register({id:"AIPP-PREP2-C03-001",name:"Hydrated pyro selection remains interactive",layer:"browser",requirements:["TST-001"],tier:"standard",run(){P().replaceProjection(pyros(),"chamber-1");P().select("native-pyro-0002");P4.assert.equal(P().selected().formulation,"FORM_2");P().select("native-pyro-0003");P4.assert.equal(P().selected().formulation,"FORM_3");return{selected:P().snapshot().selectedId};}});
 P4.register({id:"AIPP-PREP2-C03-002",name:"Imported formulation is retained as a selectable value",layer:"browser",requirements:["TST-001"],tier:"standard",run(){P().replaceProjection(pyros(),"chamber-1");P4.assert.equal(P().selected().formulation,"FORM_1");return{formulation:P().selected().formulation};}});
 P4.register({id:"AIPP-PREP2-C03-003",name:"Duplicate preserves selection and adds one pyro",layer:"browser",requirements:["TST-001"],tier:"standard",run(){P().replaceProjection(pyros(),"chamber-1");const before=P().snapshot().pyros.length;P().duplicate(P().snapshot().selectedId);P4.assert.equal(P().snapshot().pyros.length,before+1);P4.assert.true(!!P().selected());return{count:before+1};}});
 P4.register({id:"AIPP-PREP2-C03-004",name:"Filter add and duplicate remain interactive",layer:"browser",requirements:["TST-001"],tier:"standard",run(){F().replaceProjection(null,"chamber-1",1,[]);F().create();const id=F().snapshot().selectedId;F().duplicate(id);P4.assert.equal(F().snapshot().filters.length,2);P4.assert.true(!!F().selected());return{count:2};}});
 P4.register({id:"AIPP-PREP2-C03-005",name:"Working selection does not mutate master JSON",layer:"browser",requirements:["ARC-010","BLD-012"],tier:"standard",run(){const before=P2.application.aippDeckDocument.serialize();P().replaceProjection(pyros(),"chamber-1");P().select("native-pyro-0003");P4.assert.equal(P2.application.aippDeckDocument.serialize(),before);return{masterUnchanged:true};}});
 P4.register({id:"AIPP-PREP2-C03-006",name:"Candidate 03 leaves protocol state clean",layer:"integration",requirements:["PRO-009","TST-008"],tier:"standard",run(){P4.assert.equal(P2.requests.size,0);P4.assert.equal(P2.diagnostics.snapshot().activeTransfers,0);return{activeRequests:0,activeTransfers:0};}});
})();
