"use strict";
(function(){
 const test=(n,name,run)=>P4.register({id:`AIPP-C06-FORM-${String(n).padStart(3,"0")}`,name,layer:"browser",requirements:["ARC-010","BLD-012","TST-001","TST-003","TST-007","TST-009"],tier:"standard",run});
 const E=()=>P2.application.aippPyroEditor,M=()=>P2.application.aippChamberPyros,V=()=>P2.application.aippChamberPyroView,C=()=>P2.application.aippChamberEditor,D=()=>P2.application.aippDeckDocument;
 const wait=()=>new Promise(r=>setTimeout(r,0));
 async function library(){const s=await E().load();P4.assert.equal(s.names.length,79);return s.names;}
 async function fixture(imported=false){const names=await library(),pyros=names.slice(0,3).map((formulation,i)=>({formulation,number:i+1,piles:1,ignition:{triggering_event:"SimStart",delay:"0 s"},shape:{type:"sphere",diameter:"1 mm"}}));if(imported)pyros[2].formulation="Imported_Unmatched_Formulation_C06";const native={aipp_calculation:{header:{},auxiliary_files:{},time_specs:{},reaction_specs:{},assembly:{tank_id:1,chambers:[{label:"Candidate 06 selector chamber",volume:"1e-3 m3",temperature:"298.15 K",pressure:"101325 Pa",pyro:pyros}],walls:[],orifices:[],pistons:[]}}};D().replace(native,{reason:"candidate06-formulation-selector-fixture"});C().load({kind:"chamber",index:1,id:"chamber-0001",label:"Candidate 06 selector chamber",path:"aipp_calculation.assembly.chambers[0]"});V().render();await wait();return{names};}
 function active(){const x=V().enhancedSelectors().formulation;P4.assert.true(!!x);return x;}
 async function search(query){const x=active();x.focus();x.open();x.setTextboxValue(query);x.control_input.dispatchEvent(new Event("input",{bubbles:true}));x.refreshOptions(true);await wait();return{x,options:[...x.dropdown_content.querySelectorAll("[data-selectable]")].filter(o=>getComputedStyle(o).display!=="none")};}
 test(1,"Mounted selector exposes every protected formulation",async()=>{const {names}=await fixture();const x=active(),optionValues=new Set(Object.keys(x.options));for(const name of names)P4.assert.true(optionValues.has(name),"Missing protected formulation: "+name);P4.assert.equal(names.length,79);P4.assert.true(optionValues.size===79||optionValues.size===80,"Selector may add only the current unmatched imported formulation");return{protectedOptions:names.length,totalOptions:optionValues.size};});
 test(2,"Actual row clicks switch three pyros without reducing protected inventory",async()=>{const {names}=await fixture();P4.assert.equal(document.querySelectorAll("[data-select-pyro]").length,3);for(let i=0;i<3;i++){const pyro=M().snapshot().pyros[i],row=document.querySelector(`[data-select-pyro="${pyro.id}"]`);P4.assert.true(!!row,"Live pyro row required for "+pyro.id);row.click();await wait();P4.assert.equal(M().snapshot().selectedId,pyro.id);P4.assert.equal(String(active().getValue()),String(pyro.formulation));const optionValues=new Set(Object.keys(active().options));for(const name of names)P4.assert.true(optionValues.has(name),"Protected inventory reduced after row click");}return{clicked:3,protectedOptions:names.length};});
 test(3,"Typed case-insensitive partial search renders PNP results",async()=>{await fixture();const {x,options}=await search("pNp");P4.assert.true(options.length>0);P4.assert.true(options.some(o=>/pnp/i.test(o.textContent)));P4.assert.true(!/no results found/i.test(x.dropdown_content.textContent));return{matches:options.length};});
 test(4,"Clicking search result changes only selected pyro before Apply",async()=>{await fixture();const master=JSON.stringify(D().snapshot().native),before=M().snapshot().pyros.map(p=>p.formulation);document.querySelectorAll("[data-select-pyro]")[1].click();await wait();const id=M().snapshot().selectedId,{options}=await search("pnp"),target=options.find(o=>String(o.dataset.value||o.textContent).trim()!==before[1]);P4.assert.true(!!target);target.click();await wait();const after=M().snapshot().pyros;P4.assert.equal(after[0].formulation,before[0]);P4.assert.equal(after[2].formulation,before[2]);P4.assert.equal(JSON.stringify(D().snapshot().native),master);P4.assert.equal(C().snapshot().working.pyro[1].formulation,after[1].formulation);return{selected:id,masterUnchanged:true};});
 test(5,"Apply and reopen persist ordered pyro array",async()=>{await fixture();document.querySelectorAll("[data-select-pyro]")[2].click();await wait();const {options}=await search("pnp");options[0].click();await wait();const working=M().snapshot().pyros.map(p=>p.formulation);C().apply();P4.assert.equal(JSON.stringify(D().snapshot().native.aipp_calculation.assembly.chambers[0].pyro.map(p=>p.formulation)),JSON.stringify(working));const saved=JSON.parse(D().serialize());D().replace(saved,{reason:"candidate06-reopen"});C().load({kind:"chamber",index:1,id:"chamber-0001",label:"Candidate 06 selector chamber",path:"aipp_calculation.assembly.chambers[0]"});P4.assert.equal(JSON.stringify(M().snapshot().pyros.map(p=>p.formulation)),JSON.stringify(working));return{persisted:true};});
 test(6,"Clearing search preserves selection and one enhanced control",async()=>{await fixture();const before=String(active().getValue()),{x}=await search("pnp");x.setTextboxValue("");x.control_input.dispatchEvent(new Event("input",{bubbles:true}));V().clearFormulationSearchState(x);P4.assert.equal(String(x.getValue()),before);V().render();V().render();P4.assert.equal(document.querySelectorAll("#aippChamberPyroFormulation + .ts-wrapper").length,1);P4.assert.equal(Object.keys(active().options).length,79);return{wrappers:1};});
 test(7,"Unmatched imported formulation coexists with protected inventory",async()=>{await fixture(true);document.querySelectorAll("[data-select-pyro]")[2].click();await wait();P4.assert.equal(String(active().getValue()),"Imported_Unmatched_Formulation_C06");P4.assert.equal(Object.keys(active().options).length,80);const {x,options}=await search("pnp");P4.assert.true(options.length>0);P4.assert.true(!/no results found/i.test(x.dropdown_content.textContent));return{protected:79,total:80};});
 test(8,"Inventory refresh is selection-safe and preserves active edits",async()=>{await fixture();document.querySelectorAll("[data-select-pyro]")[1].click();await wait();const id=M().selected().id;M().update(id,"piles",7);P4.assert.true(V().refreshFormulationInventory(id));P4.assert.equal(M().snapshot().selectedId,id);P4.assert.equal(M().selected().piles,7);P4.assert.equal(V().refreshFormulationInventory("stale-pyro-id"),false);return{piles:7,staleRejected:true};});
})();
