"use strict";
(function(root){
  const P7=root.P7,MAX_LINES=200;
  function stable(value){if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`;}
  function fnv1a(text){let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0;}return h.toString(16).padStart(8,"0");}
  function jsonl(rows){return rows.slice(-MAX_LINES).map(x=>JSON.stringify(x)).join("\n");}
  function asciiSafe(value){return String(value??"").replace(/[^\x00-\x7F]/g,ch=>`\\u${ch.charCodeAt(0).toString(16).padStart(4,"0")}`);}function source(name,content,status="collected",note=""){const text=asciiSafe(content);return{name,content:text,status,note,size_chars:text.length,hash_algorithm:"fnv1a32",content_hash:fnv1a(text)};}
  const exporter={active:false,lastResult:null,
    async collect(context={}){const collection=[];let hostLogs=[];try{const r=await P2.client.request("diagnostic.host_log.request",{}, {timeoutMs:5000});hostLogs=r.payload?.records||r.payload?.lines||[];collection.push({source:"host_logs",status:"collected"});}catch(error){collection.push({source:"host_logs",status:"unavailable",error_code:error.code||"HOST_LOG_UNAVAILABLE"});}
      P7.performance?.syncRuntime?.();const diagnostics=P2.diagnostics?.snapshot?.()||{},identity={foundation_version:P2.applicationVersion,application_version:P2.application?.version||"0.1.0",pillar7_implementation_version:P7.implementationVersion,protocol_version:P2.protocolVersion,scilab_version:P2.hostVersion,build_profile:context.build_profile||"development"};
      const compatibility={minimum_scilab_version:"2026.1.0",protocol_name:P2.protocolName,protocol_version:P2.protocolVersion,offline_runtime:true};
      const runtime={startup:P7.startup?.snapshot?.()||null,diagnostics,performance:P7.performance?.snapshot?.()||null,pending_requests:P2.requests?.size??0,active_transfers:diagnostics.activeTransfers??0};
      const browserLogs=P7.logger?.snapshot?.()||[];const metrics=P7.performance?.snapshot?.().records||[];const operations=(browserLogs.filter(x=>["file_io","state","transport","protocol","plot","render"].includes(x.category))).slice(-MAX_LINES);
      const buildManifest=root.P4?.buildManifest||root.P4?.releaseManifest||{foundation_version:P2.applicationVersion,manifest_hash:context.build_manifest_hash||"unavailable"};
      const testContext={build_mode:context.build_profile||"development",test_run_active:!!root.P4?.running,test_result_count:root.P4?.results?.length||0,generated_from:"live_runtime"};
      const files=[source("identity.json",JSON.stringify(identity,null,2)),source("compatibility.json",JSON.stringify(compatibility,null,2)),source("runtime_snapshot.json",JSON.stringify(runtime,null,2)),source("browser_logs.jsonl",jsonl(browserLogs)),source("host_logs.jsonl",hostLogs.length?jsonl(hostLogs):"",hostLogs.length?"collected":"unavailable",hostLogs.length?"":"Host log source unavailable"),source("performance_metrics.jsonl",jsonl(metrics)),source("recent_operations.json",JSON.stringify(operations,null,2)),source("build_manifest.json",JSON.stringify(buildManifest,null,2)),source("test_context.json",JSON.stringify(testContext,null,2)),source("README.txt","Scilab-JCEF diagnostic package. Payload bodies are excluded by default. Hashes use FNV-1a 32-bit over UTF-16 code units and are intended for package integrity verification, not cryptographic authentication.\n")];
      return{schema_version:"1.0",package_kind:"scilab-jcef-diagnostic",created_utc:new Date().toISOString(),correlation_id:context.correlation_id||P2.client.nextId("diagnostic-export"),retention_limit:MAX_LINES,payload_bodies_included:false,collection,files};},
    async run(context={}){if(this.active)throw new P2.ProtocolError("EXPORT_ACTIVE","A diagnostic export is already active.");this.active=true;const requestId=context.correlation_id||P2.client.nextId("diagnostic-export");P7.logger?.info("file_io","file_io.operation_started",{request_id:requestId},{operation:"diagnostic_package_export",stage:"collect"});try{const pkg=await this.collect({...context,correlation_id:requestId});const result=await P2.client.request("diagnostic.package.export.request",pkg,{requestId,timeoutMs:15000});this.lastResult=result.payload;P7.logger?.info("file_io","file_io.operation_completed",{request_id:requestId},{operation:"diagnostic_package_export",stage:"commit",path:result.payload?.path});return result.payload;}catch(error){P7.logger?.error("file_io","file_io.operation_failed",{request_id:requestId},{operation:"diagnostic_package_export",stage:"commit",error_code:error.code||"EXPORT_FAILED"});throw error;}finally{this.active=false;}},
    snapshot(){return{active:this.active,last_result:this.lastResult};},fnv1a,stable,source
  };P7.diagnosticExport=exporter;
})(window);
