"use strict";
(function(){
 const copy=v=>JSON.parse(JSON.stringify(v));
 let state={phase:"idle",names:[],master:null,selectedName:"",sourceFormulation:null,workingFormulation:null,isDirty:false,validationErrors:[]};
 const listeners=new Set();let loadPromise=null;
 function notify(event){for(const listener of [...listeners]){try{listener(snapshot(),event);}catch(_){}}}
 function subscribe(listener){if(typeof listener!=="function")return()=>{};listeners.add(listener);return()=>listeners.delete(listener);}
 function snapshot(){return copy(state);}
 function validate(name,value){const e=[];if(!name||typeof name!=="string")e.push("Formulation name is required.");if(!value||typeof value!=="object"||Array.isArray(value))e.push("Formulation must be an object.");if(value&&typeof value==="object"){["Temperature","Density","reference_burn_rate","HEX"].forEach(k=>{if(!(k in value))e.push(k+" is required.");});if("burn_rate_exponent" in value&&(!Number.isFinite(value.burn_rate_exponent)))e.push("burn_rate_exponent must be finite.");if(!value.gas_yields||typeof value.gas_yields!=="object")e.push("gas_yields is required.");}return e;}
 async function load(){if(state.names.length&&state.master){state.phase="ready";state.validationErrors=[];notify("ready");return snapshot();}if(loadPromise)return loadPromise;state.phase="loading";notify("loading");loadPromise=(async()=>{try{const data=await P2.application.aippHostAdapter.load();state.names=[...new Set((data.masterPyroNames||[]).map(x=>String(x??"").trim()).filter(Boolean))];state.master=data.masterPyroList;state.phase="ready";notify("ready");return snapshot();}catch(error){state.phase="error";notify("error");throw error;}finally{loadPromise=null;}})();return loadPromise;}
 function select(name){if(!state.master||!Object.prototype.hasOwnProperty.call(state.master,name)){state.phase="error";state.validationErrors=["Unknown formulation: "+name];throw new P2.ProtocolError("AIPP_UNKNOWN_FORMULATION",name);}const source=copy(state.master[name]),errors=validate(name,source);state.selectedName=name;state.sourceFormulation=source;state.workingFormulation=copy(source);state.validationErrors=errors;state.isDirty=false;state.phase=errors.length?"invalid":"selected";return snapshot();}
 function update(path,value){if(!state.workingFormulation)throw new P2.ProtocolError("AIPP_FORMULATION_NOT_SELECTED","Select a formulation first.");const parts=String(path).split(".");let node=state.workingFormulation;for(let i=0;i<parts.length-1;i++){if(!node[parts[i]]||typeof node[parts[i]]!=="object")node[parts[i]]={};node=node[parts[i]];}node[parts.at(-1)]=value;state.validationErrors=validate(state.selectedName,state.workingFormulation);state.isDirty=JSON.stringify(state.workingFormulation)!==JSON.stringify(state.sourceFormulation);state.phase=state.validationErrors.length?"invalid":state.isDirty?"modified":"selected";return snapshot();}
 function reset(){if(!state.sourceFormulation)return snapshot();state.workingFormulation=copy(state.sourceFormulation);state.isDirty=false;state.validationErrors=[];state.phase="selected";return snapshot();}
 P2.application.aippPyroEditor={load,select,update,reset,snapshot,validate,copy,subscribe};
})();
