"use strict";
(function(){
 const q=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
 const definitions=[
  {title:"Thermochemical properties",fields:[["Density","Density"],["HEX","Heat of explosion (HEX)"],["Temperature","Flame temperature"],["reference_burn_rate","Reference burn rate"],["burn_rate_exponent","Burn-rate exponent"],["burn_rate_temperature_sensitivity","Temperature sensitivity"]]},
  {title:"Gas yields",object:"gas_yields",labels:{H2O:"Water vapor (H2O)",CO2:"Carbon dioxide (CO2)",N2:"Nitrogen (N2)",H2:"Hydrogen (H2)",CO:"Carbon monoxide (CO)"}},
  {title:"Wild-card gas",object:"wild_card",labels:{"Cp/R":"Heat-capacity ratio (Cp/R)",molar_mass:"Molar mass",wc_gas_yield:"Gas yield"}}
 ];
 function field(path,label,value){return `<label class="aipp-property"><span class="aipp-property-label">${esc(label)}</span><input data-pyro-path="${esc(path)}" value="${esc(value)}" aria-label="${esc(label)}"></label>`;}
 function renderFields(obj){return definitions.map(g=>{let body="";if(g.fields)body=g.fields.filter(([k])=>k in obj).map(([k,l])=>field(k,l,obj[k])).join("");else{const values=obj[g.object]||{};body=Object.keys(values).sort().map(k=>field(g.object+"."+k,g.labels[k]||k,values[k])).join("");}return `<section class="aipp-property-group"><h3>${esc(g.title)}</h3><div class="aipp-property-grid">${body||'<p class="aipp-empty">No values supplied.</p>'}</div></section>`;}).join("");}
 function render(s){const phase=q("aippPyroEditorState"),fields=q("aippPyroFields"),dirty=q("aippPyroDirty"),errors=q("aippPyroErrors"),reset=q("aippPyroReset");if(phase)phase.textContent=s.phase;if(dirty){dirty.textContent=s.isDirty?"Modified":"Unmodified";dirty.className="aipp-state-chip "+(s.isDirty?"modified":"clean");}if(reset)reset.disabled=!s.workingFormulation||!s.isDirty;if(errors){errors.textContent=s.validationErrors.join("\n");errors.hidden=!s.validationErrors.length;}if(fields)fields.innerHTML=s.workingFormulation?renderFields(s.workingFormulation):'<div class="aipp-editor-welcome"><strong>No formulation selected</strong><span>Load the formulation library and choose a formulation to inspect or edit.</span></div>';}
 async function load(){const s=await P2.application.aippPyroEditor.load(),select=q("aippPyroSelect");select.innerHTML='<option value="">Choose a formulation...</option>'+s.names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");select.disabled=false;render(s);return s;}
 function start(){const loadBtn=q("aippPyroEditorLoad"),select=q("aippPyroSelect"),fields=q("aippPyroFields"),reset=q("aippPyroReset");if(loadBtn)loadBtn.addEventListener("click",async()=>{loadBtn.disabled=true;loadBtn.textContent="Loading...";try{await load();loadBtn.textContent="Reload formulations";}catch(e){q("aippPyroErrors").hidden=false;q("aippPyroErrors").textContent=e.message;loadBtn.textContent="Try again";}finally{loadBtn.disabled=false;}});if(select)select.addEventListener("change",()=>{if(select.value)render(P2.application.aippPyroEditor.select(select.value));});if(fields)fields.addEventListener("change",e=>{const p=e.target.dataset.pyroPath;if(p){let v=e.target.value;if(v!==""&&Number.isFinite(Number(v))&&!/[a-zA-Z/]/.test(v))v=Number(v);render(P2.application.aippPyroEditor.update(p,v));}});if(reset)reset.addEventListener("click",()=>render(P2.application.aippPyroEditor.reset()));render(P2.application.aippPyroEditor.snapshot());}
 P2.application.aippPyroEditorView={load,render};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();
