"use strict";
(function(){
 const copy=value=>JSON.parse(JSON.stringify(value));
 const canonicalText=value=>String(Array.isArray(value)?(value[0]??""):(value??"")).trim();
 const supportedShapes=["sphere","tablet","grain","wafer","tabular"];
 const shapes={
  sphere:{radius:"0.3 mm"},
  tablet:{diameter:"3.9 mm",total_height:"1.9 mm",dome_height:"0.076 mm"},
  grain:{inner_diameter:"7.0 mm",outer_diameter:"13.0 mm",fin_diameter:"10.0 mm",num_fins:8,fin_thickness:"3.0 mm",cylinder_height:"4.0 mm"},
  wafer:{inner_radius:"4.0 mm",outer_radius:"6.0 mm",height:"2.0 mm"},
  tabular:{burn_distance_units:"mm",surface_area_units:"mm^2",burn_distance:[0,1],surface_area:[100,0]}
 };
 const lengthUnits={mm:1,cm:10,m:1000,in:25.4};
 const areaUnits={mm2:1,cm2:100,m2:1000000,in2:645.16};
 let seq=0,state={chamberId:"chamber-1",pyros:[],selectedId:"",validationErrors:[]};const idAliases=new Map();
 const nextId=()=>"pyro-"+String(++seq).padStart(4,"0");
 const formulationNames=()=>{const s=P2.application.aippPyroEditor.snapshot();return Array.isArray(s.names)?s.names.map(canonicalText).filter(Boolean):[];};
 const master=name=>{const key=canonicalText(name),s=P2.application.aippPyroEditor.snapshot();return s.master&&s.master[key]?copy(s.master[key]):null;};
 function normalizeUnit(unit){return canonicalText(unit).replace(/²/g,"2").replace(/\^2/g,"2").replace(/\s+/g,"");}
 function unitDimension(unit){unit=normalizeUnit(unit);if(lengthUnits[unit])return"length";if(areaUnits[unit])return"area";return"";}
 function convertValue(value,fromUnit,toUnit){fromUnit=normalizeUnit(fromUnit);toUnit=normalizeUnit(toUnit);const dim=unitDimension(fromUnit);if(!dim||dim!==unitDimension(toUnit))throw new P2.ProtocolError("AIPP_INCOMPATIBLE_GEOMETRY_UNITS",`${fromUnit}->${toUnit}`);const map=dim==="length"?lengthUnits:areaUnits;return Number(value)*map[fromUnit]/map[toUnit];}
 function parseQuantity(text){const match=canonicalText(text).match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*([^\s]+)$/);if(!match||!Number.isFinite(Number(match[1])))return null;return{valueText:match[1],value:Number(match[1]),unit:normalizeUnit(match[2])};}
 function changeQuantityUnit(id,key,toUnit){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);const q=parseQuantity(p.shape[key]);if(!q)throw new P2.ProtocolError("AIPP_INVALID_GEOMETRY_QUANTITY",key);const converted=convertValue(q.value,q.unit,toUnit);p.shape[key]=`${Number(converted.toPrecision(15))} ${normalizeUnit(toUnit)}`;return snapshot();}
 function validateTabular(shape){const errors=[],x=shape?.burn_distance,y=shape?.surface_area;if(!Array.isArray(x)||!Array.isArray(y)){errors.push("Tabular geometry arrays are required.");return errors;}if(x.length!==y.length)errors.push("Tabular geometry arrays must have equal lengths.");if(x.length<2)errors.push("Tabular geometry requires at least two rows.");if(!lengthUnits[normalizeUnit(shape.burn_distance_units)])errors.push("Burn-distance units must be length units.");if(!areaUnits[normalizeUnit(shape.surface_area_units)])errors.push("Surface-area units must be area units.");if(x.some(v=>!Number.isFinite(Number(v)))||y.some(v=>!Number.isFinite(Number(v))))errors.push("Every tabular cell must be finite and numeric.");if(x.some(v=>Number(v)<0))errors.push("Burn distances must be non-negative.");if(y.some(v=>Number(v)<0))errors.push("Surface areas must be non-negative.");if(x.length&&Number(x[0])!==0)errors.push("First burn distance must be zero.");if(y.length&&Number(y[y.length-1])!==0)errors.push("Final surface area must be zero.");for(let i=1;i<x.length;i++)if(Number(x[i])<=Number(x[i-1])){errors.push("Burn distances must be monotonically increasing.");break;}return errors;}
 function validateShape(p){const errors=[];if(!supportedShapes.includes(p.shape_type)){if(p.unsupported_imported_shape)return errors;errors.push("Known shape is required.");return errors;}const required={sphere:["radius"],tablet:["diameter","total_height","dome_height"],grain:["inner_diameter","outer_diameter","fin_diameter","fin_thickness","cylinder_height"],wafer:["inner_radius","outer_radius","height"]}[p.shape_type]||[];for(const key of required){const q=parseQuantity(p.shape?.[key]);if(!q||unitDimension(q.unit)!=="length"||q.value<0)errors.push(`${key} must be a non-negative length quantity.`);}if(p.shape_type==="grain"&&(!Number.isInteger(p.shape?.num_fins)||p.shape.num_fins<1))errors.push("num_fins must be a positive integer.");if(p.shape_type==="tabular")errors.push(...validateTabular(p.shape));return errors;}
 function validatePyro(p){const errors=[];if(!p.id)errors.push("Pyro ID is required.");if(!p.formulation||!master(p.formulation))errors.push("A known formulation is required.");if(!["mass","number"].includes(p.quantity_type))errors.push("Quantity type must be mass or number.");else if(p.quantity_type==="mass"&&(!Number.isFinite(p.mass_g)||p.mass_g<0))errors.push("Mass must be a non-negative finite number.");else if(p.quantity_type==="number"&&(!Number.isInteger(p.number)||p.number<1))errors.push("Number must be a positive integer.");if(!Number.isInteger(p.piles)||p.piles<1)errors.push("Piles must be a positive integer.");if(!p.ignition?.triggering_event)errors.push("Triggering event is required.");if(!Number.isFinite(p.ignition?.delay_s)||p.ignition.delay_s<0)errors.push("Ignition delay must be non-negative.");errors.push(...validateShape(p));return errors;}
 function snapshot(){state.validationErrors=state.pyros.flatMap((p,i)=>validatePyro(p).map(x=>`Pyro ${i+1}: ${x}`));return copy(state);}
 function create(formulation){const names=formulationNames(),name=canonicalText(formulation)||names[0]||"generic_pyro",source=master(name);if(!source)throw new P2.ProtocolError("AIPP_UNKNOWN_FORMULATION",name);const p={id:nextId(),name:"Pyro "+(state.pyros.length+1),formulation:name,formulation_working_copy:copy(source),quantity_type:"mass",mass_g:0,mass_unit:"g",number:1,piles:1,ignition:{triggering_event:"SimStart",delay_s:0,delay_unit:"s"},shape_type:"sphere",shape:copy(shapes.sphere),burn_rate_modifications:{}};state.pyros.push(p);state.selectedId=p.id;return snapshot();}
 const resolveId=id=>state.pyros.some(p=>p.id===id)?id:(idAliases.get(id)||id);
 const selected=()=>state.pyros.find(p=>p.id===resolveId(state.selectedId))||null;
 function select(id){const resolved=resolveId(id);if(!state.pyros.some(p=>p.id===resolved))throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);state.selectedId=resolved;return snapshot();}
 function update(id,path,value){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);const parts=path.split(".");let target=p;while(parts.length>1)target=target[parts.shift()];target[parts[0]]=value;return snapshot();}
 function assign(id,name){name=canonicalText(name);const p=state.pyros.find(x=>x.id===resolveId(id)),source=master(name);if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);if(!source)throw new P2.ProtocolError("AIPP_UNKNOWN_FORMULATION",name);p.formulation=name;p.formulation_working_copy=copy(source);return snapshot();}
 function setShape(id,type){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);if(!supportedShapes.includes(type))throw new P2.ProtocolError("AIPP_UNKNOWN_PYRO_SHAPE",type);p.shape_type=type;p.shape=copy(shapes[type]);delete p.unsupported_imported_shape;return snapshot();}
 function preserveImportedShape(id,shape){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);const type=canonicalText(shape?.geometry);if(supportedShapes.includes(type)){p.shape_type=type;p.shape=copy(shape);delete p.shape.geometry;delete p.unsupported_imported_shape;}else{p.shape_type=type||"unknown";p.shape=copy(shape||{});p.unsupported_imported_shape=true;}return snapshot();}
 function duplicate(id){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);const n=copy(p);n.id=nextId();n.name=p.name+" copy";state.pyros.splice(state.pyros.indexOf(p)+1,0,n);state.selectedId=n.id;return snapshot();}
 function remove(id){const i=state.pyros.findIndex(x=>x.id===resolveId(id));if(i<0)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);state.pyros.splice(i,1);state.selectedId=state.pyros[Math.min(i,state.pyros.length-1)]?.id||"";return snapshot();}
 function move(id,delta){const i=state.pyros.findIndex(x=>x.id===resolveId(id)),j=i+delta;if(i<0)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);if(j<0||j>=state.pyros.length)return snapshot();[state.pyros[i],state.pyros[j]]=[state.pyros[j],state.pyros[i]];return snapshot();}
 function parseCsv(text,selectedLengthUnit,selectedAreaUnit){const lines=String(text??"").replace(/^\uFEFF/,"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length<3)throw new P2.ProtocolError("AIPP_INVALID_TABULAR_CSV","CSV requires one units row and at least two numeric data rows.");const cells=line=>line.split(",").map(x=>x.trim());const units=cells(lines.shift());if(units.length!==2)throw new P2.ProtocolError("AIPP_INVALID_TABULAR_CSV_COLUMNS","CSV must contain exactly two columns.");const selectedLengthText=canonicalText(selectedLengthUnit),selectedAreaText=canonicalText(selectedAreaUnit),csvLengthText=canonicalText(units[0]),csvAreaText=canonicalText(units[1]),lengthUnit=normalizeUnit(selectedLengthText),areaUnit=normalizeUnit(selectedAreaText),csvLengthUnit=normalizeUnit(csvLengthText),csvAreaUnit=normalizeUnit(csvAreaText);if(unitDimension(lengthUnit)!=="length"||unitDimension(areaUnit)!=="area")throw new P2.ProtocolError("AIPP_INVALID_TABULAR_EDITOR_UNIT","Editor units are invalid.");if(unitDimension(csvLengthUnit)!=="length"||unitDimension(csvAreaUnit)!=="area")throw new P2.ProtocolError("AIPP_INVALID_TABULAR_CSV_UNIT","CSV units must be length and area units.");if(csvLengthText!==selectedLengthText||csvAreaText!==selectedAreaText)throw new P2.ProtocolError("AIPP_TABULAR_CSV_UNIT_MISMATCH",`CSV units must exactly match the GUI selections: ${selectedLengthText},${selectedAreaText}.`);const rows=lines.map((line,index)=>{const row=cells(line);if(row.length!==2)throw new P2.ProtocolError("AIPP_INVALID_TABULAR_CSV_COLUMNS",`Data row ${index+1}`);const x=Number(row[0]),y=Number(row[1]);if(!Number.isFinite(x)||!Number.isFinite(y))throw new P2.ProtocolError("AIPP_INVALID_TABULAR_CSV_VALUE",`Data row ${index+1}`);return[x,y];});const result={burn_distance_units:selectedLengthText,surface_area_units:selectedAreaText,burn_distance:rows.map(r=>r[0]),surface_area:rows.map(r=>r[1])};const errors=validateTabular(result);if(errors.length)throw new P2.ProtocolError("AIPP_INVALID_TABULAR_GEOMETRY",errors.join(" "));return result;}
 function importCsvText(id,text,selectedLengthUnit,selectedAreaUnit){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);if(p.shape_type!=="tabular")throw new P2.ProtocolError("AIPP_TABULAR_GEOMETRY_REQUIRED",p.shape_type);const candidate=parseCsv(text,selectedLengthUnit??p.shape.burn_distance_units,selectedAreaUnit??p.shape.surface_area_units);p.shape=candidate;return snapshot();}
 const burnParams={reference_burn_rate:{scale:"reference_burn_rate_scaling",fallback:"1 mm/s"},burn_rate_exponent:{scale:"burn_rate_exponent_scaling",fallback:1},temperature_sensitivity:{scale:"temperature_sensitivity_scaling",fallback:"0 1/K"}};
 function burnRecord(id){const p=state.pyros.find(x=>x.id===resolveId(id));if(!p)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_PYRO",id);p.burn_rate_modifications=p.burn_rate_modifications||{};return p;}
 function burnModel(id){const b=burnRecord(id).burn_rate_modifications;return ["pressure_units","burn_rate_units","pressure_array","burn_rate_array"].some(k=>Object.prototype.hasOwnProperty.call(b,k))?"table":"power";}
 function burnMode(id,key){const b=burnRecord(id).burn_rate_modifications,c=burnParams[key];if(!c)throw new P2.ProtocolError("AIPP_UNKNOWN_BURN_PARAMETER",key);const over=Object.prototype.hasOwnProperty.call(b,key),scale=Object.prototype.hasOwnProperty.call(b,c.scale);return over&&scale?"conflict":over?"override":scale?"scale":"default";}
 function formulationBurnValue(p,key){const f=p.formulation_working_copy||{};if(key==="temperature_sensitivity")return f.temperature_sensitivity??f.burn_rate_temperature_sensitivity??burnParams[key].fallback;return f[key]??burnParams[key].fallback;}
 function setBurnModel(id,model){const p=burnRecord(id),b=p.burn_rate_modifications;if(model==="table"){delete b.reference_burn_rate;delete b.reference_burn_rate_scaling;delete b.burn_rate_exponent;delete b.burn_rate_exponent_scaling;b.pressure_units=b.pressure_units||"MPa";b.burn_rate_units=b.burn_rate_units||"mm/s";b.pressure_array=Array.isArray(b.pressure_array)?b.pressure_array:[1,2];b.burn_rate_array=Array.isArray(b.burn_rate_array)?b.burn_rate_array:[1,1];}else if(model==="power"){delete b.pressure_units;delete b.burn_rate_units;delete b.pressure_array;delete b.burn_rate_array;}else throw new P2.ProtocolError("AIPP_UNKNOWN_BURN_MODEL",model);return snapshot();}
 function setBurnMode(id,key,mode){const p=burnRecord(id),b=p.burn_rate_modifications,c=burnParams[key];if(!c)throw new P2.ProtocolError("AIPP_UNKNOWN_BURN_PARAMETER",key);if(mode==="default"){delete b[key];delete b[c.scale];}else if(mode==="override"){delete b[c.scale];if(!Object.prototype.hasOwnProperty.call(b,key))b[key]=copy(formulationBurnValue(p,key));}else if(mode==="scale"){delete b[key];if(!Object.prototype.hasOwnProperty.call(b,c.scale))b[c.scale]=1;}else throw new P2.ProtocolError("AIPP_UNKNOWN_BURN_MODE",mode);return snapshot();}
 function setBurnValue(id,key,value){const p=burnRecord(id),b=p.burn_rate_modifications;if(!burnParams[key]&&!Object.values(burnParams).some(x=>x.scale===key)&&!["pressure_units","burn_rate_units"].includes(key))throw new P2.ProtocolError("AIPP_UNKNOWN_BURN_FIELD",key);b[key]=value;return snapshot();}
 function addBurnRow(id){const b=burnRecord(id).burn_rate_modifications;b.pressure_array=Array.isArray(b.pressure_array)?b.pressure_array:[];b.burn_rate_array=Array.isArray(b.burn_rate_array)?b.burn_rate_array:[];b.pressure_array.push(b.pressure_array.length?Number(b.pressure_array.at(-1))+1:0);b.burn_rate_array.push(b.burn_rate_array.length?Number(b.burn_rate_array.at(-1)):0);return snapshot();}
 function removeBurnRow(id,index){const b=burnRecord(id).burn_rate_modifications;if(!Array.isArray(b.pressure_array)||!Array.isArray(b.burn_rate_array))return snapshot();b.pressure_array.splice(index,1);b.burn_rate_array.splice(index,1);return snapshot();}
 function setBurnTableCell(id,column,index,value){const b=burnRecord(id).burn_rate_modifications,key=column==="pressure"?"pressure_array":"burn_rate_array";if(!Array.isArray(b[key]))b[key]=[];b[key][index]=Number(value);return snapshot();}
 function validateBurn(p){const errors=[],b=p.burn_rate_modifications||{},model=["pressure_units","burn_rate_units","pressure_array","burn_rate_array"].some(k=>Object.prototype.hasOwnProperty.call(b,k))?"table":"power";for(const [k,c] of Object.entries(burnParams)){if(Object.prototype.hasOwnProperty.call(b,k)&&Object.prototype.hasOwnProperty.call(b,c.scale))errors.push(`${k} cannot contain both override and scale.`);if(Object.prototype.hasOwnProperty.call(b,c.scale)&&!Number.isFinite(Number(b[c.scale])))errors.push(`${c.scale} must be numeric.`);}if(model==="table"){if(!["Pa","kPa","MPa"].includes(b.pressure_units))errors.push("Pressure units are invalid.");if(!["mm/s","cm/s","m/s"].includes(b.burn_rate_units))errors.push("Burn-rate units are invalid.");if(!Array.isArray(b.pressure_array)||!Array.isArray(b.burn_rate_array)||b.pressure_array.length!==b.burn_rate_array.length)errors.push("Pressure and burn-rate arrays must have equal lengths.");}return errors;}
 function replaceProjection(rows,chamberId){const previous=state.pyros.slice(),previousSelected=state.selectedId,next=copy(Array.isArray(rows)?rows:[]);previous.forEach((p,i)=>{if(next[i]?.id&&p?.id&&p.id!==next[i].id)idAliases.set(p.id,next[i].id);});state={chamberId:String(chamberId||"chamber-1"),pyros:next,selectedId:"",validationErrors:[]};const mapped=idAliases.get(previousSelected);state.selectedId=state.pyros.some(p=>p.id===mapped)?mapped:(state.pyros[0]?.id||"");seq=state.pyros.length;return snapshot();}
 function reset(){seq=0;idAliases.clear();state={chamberId:"chamber-1",pyros:[],selectedId:"",validationErrors:[]};return snapshot();}
 P2.application.aippChamberPyros={snapshot,selected,select,create,update,assign,canonicalText,setShape,preserveImportedShape,duplicate,remove,move,reset,replaceProjection,shapeDefaults:()=>copy(shapes),supportedShapes:()=>supportedShapes.slice(),parseQuantity,normalizeUnit,unitDimension,convertValue,changeQuantityUnit,parseCsv,importCsvText,validateTabular,burnModel,burnMode,formulationBurnValue,setBurnModel,setBurnMode,setBurnValue,addBurnRow,removeBurnRow,setBurnTableCell,validateBurn,validate:validatePyro};
})();
