"use strict";
(function(){
 const copy=v=>JSON.parse(JSON.stringify(v)); let seq=0;
 const idAliases=new Map();
 const fresh=()=>({chamberId:"chamber-1",chamberIndex:1,filters:[],selectedId:"",orifices:[{index:1,label:"Outlet 1",from:1,to:2},{index:2,label:"Outlet 2",from:1,to:3},{index:3,label:"Return",from:2,to:1}]}); let state=fresh();
 const lib=()=>P2.application.aippMaterialLibrary.current()?.materials||{}, materialNames=()=>Object.keys(lib()), materialProperties=name=>copy(lib()[name]||{});
 const nextId=()=>`filter-${String(++seq).padStart(4,"0")}`;
 const parseMass=text=>{const m=String(text??"").trim().match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*(.*)$/);return m?{value:Number(m[1]),valueText:m[1],unit:P2.application.aippQuaffUnits.canonicalSymbol(m[2]||"g")}:null;};
 const massUnits=()=>P2.application.aippQuaffUnits.catalogs().mass.slice();
 const defaults=()=>{const material=materialNames()[0]||"steel";return {id:nextId(),name:`Filter ${seq}`,material,...materialProperties(material),mass:"0.0 g",method:"PERCENTAGE",coefficient:0,orifices:[]};};
 const snapshot=()=>copy(state),resolveId=id=>state.filters.some(x=>x.id===id)?id:(idAliases.get(id)||id),selected=()=>copy(state.filters.find(x=>x.id===resolveId(state.selectedId))||null);
 function allowedOrifices(){return copy(state.orifices.filter(x=>x.from===state.chamberIndex));}
 function create(){const f=defaults();state.filters.push(f);state.selectedId=f.id;return snapshot();}
 function select(id){const resolved=resolveId(id);if(!state.filters.some(x=>x.id===resolved))throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);state.selectedId=resolved;return snapshot();}
 function update(id,key,value){const f=state.filters.find(x=>x.id===resolveId(id));if(!f)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);if(key==="method"&&!['PERCENTAGE','KNTU'].includes(value))throw new P2.ProtocolError("AIPP_UNKNOWN_FILTER_METHOD",value);if(key==="material"){if(!Object.prototype.hasOwnProperty.call(lib(),value))throw new P2.ProtocolError("AIPP_UNKNOWN_FILTER_MATERIAL",value);f.material=value;Object.assign(f,materialProperties(value));return snapshot();}if(["density","specific_heat","thermal_conductivity"].includes(key))throw new P2.ProtocolError("AIPP_READ_ONLY_MATERIAL_PROPERTY",key);f[key]=value;return snapshot();}
 function updateMassValue(id,valueText,unit){const n=Number(valueText),u=P2.application.aippQuaffUnits.canonicalSymbol(unit);if(!Number.isFinite(n)||n<0)throw new P2.ProtocolError("AIPP_INVALID_FILTER_MASS",String(valueText));if(!massUnits().includes(u))throw new P2.ProtocolError("AIPP_INVALID_QUAFF_UNIT",`mass: ${unit}`);return update(id,"mass",`${valueText} ${u}`);}
 function changeMassUnit(id,toUnit){const f=state.filters.find(x=>x.id===resolveId(id));if(!f)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);const q=parseMass(f.mass);if(!q)throw new P2.ProtocolError("AIPP_INVALID_FILTER_MASS",String(f.mass));const to=P2.application.aippQuaffUnits.canonicalSymbol(toUnit);if(!massUnits().includes(to))throw new P2.ProtocolError("AIPP_INVALID_QUAFF_UNIT",`mass: ${toUnit}`);const value=q.unit===to?q.value:P2.application.aippQuaffUnits.convert("mass",q.value,q.unit,to);return updateMassValue(id,String(Number(value.toPrecision(12))),to);}
 function assignOrifices(id,indices){const f=state.filters.find(x=>x.id===resolveId(id));if(!f)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);const allowed=new Set(allowedOrifices().map(x=>x.index));f.orifices=[...new Set(indices.map(Number))].filter(x=>allowed.has(x)).sort((a,b)=>a-b);return snapshot();}
 function duplicate(id){const f=state.filters.find(x=>x.id===resolveId(id));if(!f)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);const n=copy(f);n.id=nextId();n.name=f.name+" copy";state.filters.splice(state.filters.indexOf(f)+1,0,n);state.selectedId=n.id;return snapshot();}
 function remove(id){const i=state.filters.findIndex(x=>x.id===resolveId(id));if(i<0)throw new P2.ProtocolError("AIPP_UNKNOWN_CHAMBER_FILTER",id);state.filters.splice(i,1);state.selectedId=state.filters[Math.min(i,state.filters.length-1)]?.id||"";return snapshot();}
 function validate(f){const e=[];if(!String(f.material||"").trim())e.push(`${f.name}: Material is required.`);else if(!Object.prototype.hasOwnProperty.call(lib(),f.material))e.push(`${f.name}: Material ${f.material} is not present in material_list.json.`);if(!String(f.mass||"").trim())e.push(`${f.name}: Mass is required.`);if(!['PERCENTAGE','KNTU'].includes(f.method))e.push(`${f.name}: Method must be PERCENTAGE or KNTU.`);if(!Number.isFinite(Number(f.coefficient))||Number(f.coefficient)<0)e.push(`${f.name}: Coefficient must be a non-negative finite number.`);const allowed=new Set(allowedOrifices().map(x=>x.index));f.orifices.filter(x=>!allowed.has(x)).forEach(x=>e.push(`${f.name}: Orifice ${x} does not originate from chamber ${state.chamberIndex}.`));return e;}
 function scanOrificeReferences(index){return state.filters.filter(f=>f.orifices.includes(index)).map(f=>({filterId:f.id,filterName:f.name,chamberId:state.chamberId,orificeIndex:index}));}
 function remapAfterOrificeRemoval(index){state.filters.forEach(f=>f.orifices=f.orifices.filter(x=>x!==index).map(x=>x>index?x-1:x));state.orifices=state.orifices.filter(x=>x.index!==index).map(x=>({...x,index:x.index>index?x.index-1:x.index}));return snapshot();}
 function replaceProjection(nativeFilter,chamberId,chamberIndex,orifices){const previous=state.filters.slice(),previousSelected=state.selectedId;state=fresh();state.chamberId=String(chamberId||`chamber-${chamberIndex||1}`);state.chamberIndex=Number(chamberIndex||1);state.orifices=copy(Array.isArray(orifices)?orifices:[]);const list=nativeFilter&&typeof nativeFilter==="object"&&!Array.isArray(nativeFilter)?[nativeFilter]:[];state.filters=list.map((f,i)=>Object.assign(copy(f),{id:`native-filter-${String(i+1).padStart(4,"0")}`,name:f.name||`Filter ${i+1}`,orifices:Array.isArray(f.orifices)?copy(f.orifices):[]}));previous.forEach((f,i)=>{if(state.filters[i]?.id&&f?.id&&f.id!==state.filters[i].id)idAliases.set(f.id,state.filters[i].id);});const mapped=idAliases.get(previousSelected);state.selectedId=state.filters.some(f=>f.id===mapped)?mapped:(state.filters[0]?.id||"");seq=state.filters.length;return snapshot();}
 function reset(){seq=0;idAliases.clear();state=fresh();return snapshot();}
 P2.application.aippChamberFilters={snapshot,selected,allowedOrifices,materialNames,materialProperties,create,select,update,parseMass,massUnits,updateMassValue,changeMassUnit,assignOrifices,duplicate,remove,validate,scanOrificeReferences,remapAfterOrificeRemoval,reset,replaceProjection};
})();
