"use strict";
(function(){
 const esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]));
 const SVG_NS="http:"+"//www.w3.org/2000/svg";
 const dataSvg=svg=>"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg);
 const svgRoot=(width,height,viewBox)=>`<svg xmlns="${SVG_NS}" width="${width}" height="${height}" viewBox="${viewBox}">`;
 function nativeOf(input){return input&&input.aipp_calculation?input:P2.application.aippDeckDocument.snapshot().native;}
 function chamberImage(c,index,isTank){
  const pyros=Array.isArray(c&&c.pyro)?c.pyro:[],filter=c&&c.filter&&typeof c.filter==="object"?c.filter:null,label=String(c&&c.label||`${isTank?"Tank":"Chamber"} ${index}`),stroke=isTank?"#107c10":"#1769e0",fill=isTank?"#edf9f0":"#f5f9ff",ink=isTank?"#0b5e0b":"#17365d";
  const badges=[];
  if(pyros.length)badges.push(`<g transform="translate(24 100)"><rect width="70" height="32" rx="10" fill="#fff3e8" stroke="#d14b00" stroke-width="2"/><path d="M18 24c-7-5-6-11-1-16 1 5 5 5 6 10 3-3 4-7 3-11 8 7 9 14 2 19-4 3-7 2-10-2z" fill="#d14b00"/><text x="39" y="21" font-family="Segoe UI Emoji,Segoe UI,Arial" font-size="15" font-weight="700" fill="#8a3100">× ${pyros.length}</text></g>`);
  if(filter)badges.push(`<g transform="translate(${pyros.length?106:24} 100)"><rect width="70" height="32" rx="10" fill="#f1f0ff" stroke="#5b5fc7" stroke-width="2"/><path d="M12 8h18l-7 8v8l-4 3v-11z" fill="#5b5fc7"/><text x="39" y="21" font-family="Segoe UI Emoji,Segoe UI,Arial" font-size="15" font-weight="700" fill="#3f3f94">× 1</text></g>`);
  return dataSvg(`${svgRoot(300,150,"0 0 300 150")}<rect x="5" y="5" width="290" height="140" rx="24" fill="${fill}" stroke="${stroke}" stroke-width="5"/><path d="M24 46H276" stroke="${stroke}" stroke-opacity=".22" stroke-width="2"/><text x="24" y="31" font-family="Segoe UI,Arial" font-size="17" font-weight="700" fill="${ink}">${isTank?"TANK":"CHAMBER"} ${index}</text><text x="24" y="78" font-family="Segoe UI,Arial" font-size="20" font-weight="700" fill="#172d46">${esc(label)}</text>${badges.join("")}</svg>`);
 }
 function orificeImage(o,index){const label=String(o&&o.label||`Orifice ${index}`),show=label.toLowerCase()!==`orifice ${index}`.toLowerCase();return dataSvg(`${svgRoot(190,100,"0 0 190 100")}<rect x="5" y="5" width="180" height="90" rx="15" fill="#eef7ff" stroke="#0078d4" stroke-width="4"/><path d="M28 34h38l20 16-20 16H28l20-16zM162 34h-38l-20 16 20 16h38l-20-16z" fill="#cbe8ff" stroke="#0078d4" stroke-width="2"/><circle cx="95" cy="50" r="9" fill="#0078d4"/><text x="95" y="22" text-anchor="middle" font-family="Segoe UI,Arial" font-size="13" font-weight="700" fill="#0b4f79">ORIFICE ${index}</text>${show?`<text x="95" y="87" text-anchor="middle" font-family="Segoe UI,Arial" font-size="12" font-weight="600" fill="#36566f">${esc(label)}</text>`:""}</svg>`)}
 function wallImage(w,index){const label=String(w&&w.label||`Wall ${index}`),show=label.toLowerCase()!==`wall ${index}`.toLowerCase();return dataSvg(`${svgRoot(210,110,"0 0 210 110")}<rect x="5" y="5" width="200" height="100" rx="16" fill="#fff7ec" stroke="#d97706" stroke-width="4"/><path d="M28 40h154M28 51h154M28 62h154" stroke="#d97706" stroke-width="5" stroke-linecap="round" opacity=".72"/><text x="105" y="25" text-anchor="middle" font-family="Segoe UI,Arial" font-size="13" font-weight="700" fill="#824800">WALL ${index}</text>${show?`<text x="105" y="91" text-anchor="middle" font-family="Segoe UI,Arial" font-size="12" font-weight="600" fill="#6f4d24">${esc(label)}</text>`:""}</svg>`)}
 function pistonImage(p,index){const label=String(p&&p.label||`Piston ${index}`);return dataSvg(`${svgRoot(210,110,"0 0 210 110")}<rect x="5" y="5" width="200" height="100" rx="18" fill="#f2f0ff" stroke="#5b5fc7" stroke-width="4"/><path d="M35 55h35m70 0h35M70 30v50m70-50v50M78 40h54v30H78z" fill="#dddaf8" stroke="#5b5fc7" stroke-width="4"/><text x="105" y="22" text-anchor="middle" font-family="Segoe UI,Arial" font-size="13" font-weight="700" fill="#3f3f94">PISTON ${index}</text><text x="105" y="96" text-anchor="middle" font-family="Segoe UI,Arial" font-size="12" font-weight="600" fill="#494879">${esc(label)}</text></svg>`)}
 function build(input){
  const native=nativeOf(input),a=native.aipp_calculation.assembly||{},nodes=[],edges=[],tankIndex=Number(a.tank_id)||0;
  (a.chambers||[]).forEach((c,i)=>{const n=i+1,isTank=n===tankIndex;nodes.push({data:{id:`chamber-${n}`,kind:"chamber",nativeIndex:n,typeLabel:isTank?"Tank":"Chamber",indexLabel:`${n}`,label:String(c.label||`Chamber ${n}`),displayLabel:`${isTank?"TANK":"CHAMBER"} ${n}\n${String(c.label||`Chamber ${n}`)}`,pyroCount:Array.isArray(c.pyro)?c.pyro.length:0,filterCount:c.filter&&typeof c.filter==="object"?1:0,nodeImage:chamberImage(c,n,isTank),summary:`init: ${c.init_type||"—"}`,documentPath:`aipp_calculation.assembly.chambers[${i}]`},classes:"aipp-chamber"})});
  (a.orifices||[]).forEach((o,i)=>{const n=i+1,id=`orifice-${n}`;nodes.push({data:{id,kind:"orifice",nativeIndex:n,typeLabel:"Orifice",indexLabel:`${n}`,label:String(o.label||`Orifice ${n}`),displayLabel:`ORIFICE ${n}\n${String(o.label||`Orifice ${n}`)}`,nodeImage:orificeImage(o,n),summary:"",documentPath:`aipp_calculation.assembly.orifices[${i}]`},classes:"aipp-orifice"});if(o.from)edges.push({data:{id:`flow-${n}-from`,kind:"flow",relationshipLabel:"from",source:`chamber-${o.from}`,target:id},classes:"aipp-flow"});if(o.to)edges.push({data:{id:`flow-${n}-to`,kind:"flow",relationshipLabel:"to",source:id,target:`chamber-${o.to}`},classes:"aipp-flow"})});
  (a.pistons||[]).forEach((p,i)=>{const n=i+1,id=`piston-${n}`,left=Number(p?.left_connection?.chamber_idx),right=Number(p?.right_connection?.chamber_idx);nodes.push({data:{id,kind:"piston",nativeIndex:n,typeLabel:"Piston",indexLabel:`${n}`,label:String(p.label||`Piston ${n}`),displayLabel:`PISTON ${n}\n${String(p.label||`Piston ${n}`)}`,nodeImage:pistonImage(p,n),summary:"moving boundary",documentPath:`aipp_calculation.assembly.pistons[${i}]`},classes:"aipp-piston"});if(left>0)edges.push({data:{id:`piston-${n}-left`,kind:"piston-link",relationshipLabel:"left",source:`chamber-${left}`,target:id},classes:"aipp-piston-link"});if(right>0)edges.push({data:{id:`piston-${n}-right`,kind:"piston-link",relationshipLabel:"right",source:id,target:`chamber-${right}`},classes:"aipp-piston-link"})});
  (a.walls||[]).forEach((w,i)=>{const n=i+1,id=`wall-${n}`;nodes.push({data:{id,kind:"wall",nativeIndex:n,typeLabel:"Wall",indexLabel:`${n}`,label:String(w.label||`Wall ${n}`),displayLabel:`WALL ${n}\n${String(w.label||`Wall ${n}`)}`,nodeImage:wallImage(w,n),summary:"",documentPath:`aipp_calculation.assembly.walls[${i}]`},classes:"aipp-wall"});["left_connection","right_connection"].forEach(side=>{const c=w&&w[side],label=side==="left_connection"?"left boundary":"right boundary";if(c&&c.type==="WALL"){const target=Number(c.wall_index);if(Number.isInteger(target)&&target>0&&target!==n)edges.push({data:{id:`wall-${n}-${side}`,kind:"association",relationshipLabel:label,source:id,target:`wall-${target}`},classes:"aipp-association"});}else{const target=Number(c&&c.chamber_index);if(Number.isInteger(target)&&target>0)edges.push({data:{id:`wall-${n}-${side}`,kind:"association",relationshipLabel:label,source:id,target:`chamber-${target}`},classes:"aipp-association"});}})});
  return {nodes,edges,elements:nodes.concat(edges),counts:{chambers:(a.chambers||[]).length,orifices:(a.orifices||[]).length,walls:(a.walls||[]).length,pistons:(a.pistons||[]).length}};
 }
 P2.application.aippTopologyGraphAdapter={build};
})();
