"use strict";
(function(){
 const defaults=Object.freeze({
  direction:"leftward",avoidOverlap:true,directed:false,circle:false,grid:true,
  spacingFactor:0.55,maximal:true,fit:true,padding:100,animate:true,
  animationDuration:350,nodeDimensionsIncludeLabels:true,tankRight:true,
  tankRightMargin:260,wallYOffset:230,wallXSpread:115,wallRowGap:70,
  componentGap:150,collisionGap:24,collisionPasses:12,crossingSweeps:4,parallelGap:110
 });
 let last={status:"idle",rootId:"",tankId:"",wallCount:0,usedFallback:false,error:"",collisionCount:0};
 const copy=v=>JSON.parse(JSON.stringify(v));
 function nativeOf(input){return input&&input.aipp_calculation?input:P2.application.aippDeckDocument.snapshot().native;}
 function tankNodeId(native,graph){const a=nativeOf(native)?.aipp_calculation?.assembly||{},n=Number(a.tank_id),id=Number.isInteger(n)&&n>0?`chamber-${n}`:"";return id&&graph.nodes.some(x=>x.data.id===id)?id:"";}
 function chamberIds(graph){return graph.nodes.filter(x=>x.data.kind==="chamber").sort((a,b)=>a.data.nativeIndex-b.data.nativeIndex).map(x=>x.data.id);}
 function flowDegree(graph,id){return graph.edges.filter(e=>e.data.kind==="flow"&&(e.data.source===id||e.data.target===id)).length;}
 function rootId(graph,native){const tank=tankNodeId(native,graph);if(tank)return tank;const ids=chamberIds(graph);return ids.find(id=>flowDegree(graph,id)<=1)||ids[0]||"";}
 function options(graph,native,overrides={}){const cfg=Object.assign({},defaults,overrides),root=rootId(graph,native);return {name:"breadthfirst",roots:root?`#${root}`:undefined,avoidOverlap:cfg.avoidOverlap,directed:cfg.directed,circle:cfg.circle,grid:cfg.grid,spacingFactor:cfg.spacingFactor,maximal:cfg.maximal,fit:false,padding:cfg.padding,animate:cfg.animate,animationDuration:cfg.animate?cfg.animationDuration:0,nodeDimensionsIncludeLabels:cfg.nodeDimensionsIncludeLabels,direction:cfg.direction,depthSort:(a,b)=>String(a.data("documentPath")||a.id()).localeCompare(String(b.data("documentPath")||b.id()))};}
 function slot(i){if(i===0)return 0;const n=Math.ceil(i/2);return i%2?-n:n;}
 function wallAnchors(graph,positions){const chamberPos=id=>positions[id]||null;return graph.nodes.filter(n=>n.data.kind==="wall").sort((a,b)=>a.data.nativeIndex-b.data.nativeIndex).map(w=>{const linked=graph.edges.filter(e=>e.data.kind==="association"&&e.data.source===w.data.id).map(e=>chamberPos(e.data.target)).filter(Boolean);let x=0,y=0;if(linked.length){x=linked.reduce((s,p)=>s+p.x,0)/linked.length;y=Math.max(...linked.map(p=>p.y));}return{id:w.data.id,x,y,linked:linked.length};});}
 function connectorChamberPairs(graph){const map=new Map();graph.edges.forEach(e=>{if(e.data.kind!=="flow"&&e.data.kind!=="piston-link")return;const s=e.data.source,t=e.data.target,chamberSide=s.startsWith("chamber-")?s:t.startsWith("chamber-")?t:null,connectorSide=s.startsWith("chamber-")?t:s;if(!chamberSide)return;if(!map.has(connectorSide))map.set(connectorSide,new Set());map.get(connectorSide).add(chamberSide);});return map;}
 function alignParallelConnectors(cy,graph,cfg){const pairs=connectorChamberPairs(graph),groups=new Map();pairs.forEach((chambers,connectorId)=>{if(chambers.size!==2)return;const key=[...chambers].sort().join("|");if(!groups.has(key))groups.set(key,[]);groups.get(key).push(connectorId);});groups.forEach(ids=>{if(ids.length<2)return;const nodes=ids.map(id=>cy.getElementById(id)).filter(n=>!n.empty());if(nodes.length<2)return;nodes.sort((a,b)=>`${a.data("kind")}-${String(a.data("nativeIndex")).padStart(4,"0")}`.localeCompare(`${b.data("kind")}-${String(b.data("nativeIndex")).padStart(4,"0")}`));const avgX=nodes.reduce((s,n)=>s+n.position("x"),0)/nodes.length,avgY=nodes.reduce((s,n)=>s+n.position("y"),0)/nodes.length,gap=cfg.parallelGap,startY=avgY-((nodes.length-1)*gap)/2;nodes.forEach((n,i)=>n.position({x:avgX,y:startY+i*gap}));});}
 function forceTankRight(cy,id,cfg){if(!cfg.tankRight||!id)return;const tank=cy.getElementById(id);if(tank.empty())return;let maxRight=-Infinity;cy.nodes().not(".aipp-wall").forEach(n=>{if(n.id()!==id){const b=n.boundingBox({includeLabels:true,includeOverlays:false});maxRight=Math.max(maxRight,b.x2);}});if(Number.isFinite(maxRight)){const tb=tank.boundingBox({includeLabels:true,includeOverlays:false}),required=maxRight+cfg.tankRightMargin+tb.w/2;if(tank.position("x")<required)tank.position({x:required,y:tank.position("y")});}}
 function positionWalls(cy,graph,cfg){const positions={};cy.nodes().forEach(n=>positions[n.id()]={x:n.position("x"),y:n.position("y")});const groups=new Map(),anchors=wallAnchors(graph,positions);anchors.forEach(a=>{const key=a.linked?`${Math.round(a.x)}:${Math.round(a.y)}`:"unassociated";if(!groups.has(key))groups.set(key,[]);groups.get(key).push(a);});const flowPositions=cy.nodes().not(".aipp-wall").map(n=>({x:n.position("x"),y:n.position("y")})),maxY=flowPositions.length?Math.max(...flowPositions.map(p=>p.y)):0,minX=flowPositions.length?Math.min(...flowPositions.map(p=>p.x)):0;groups.forEach((items,key)=>items.forEach((a,i)=>{const node=cy.getElementById(a.id);if(node.empty())return;const col=slot(i%5),row=Math.floor(i/5);if(key==="unassociated")node.position({x:minX+col*cfg.wallXSpread,y:maxY+cfg.wallYOffset*1.5+row*cfg.wallRowGap});else node.position({x:a.x+col*cfg.wallXSpread,y:a.y+cfg.wallYOffset+row*cfg.wallRowGap});}));}
 function boxesOverlap(a,b,gap){return a.x1-gap<b.x2&&a.x2+gap>b.x1&&a.y1-gap<b.y2&&a.y2+gap>b.y1;}
 function resolveNodeCollisions(cy,cfg,onlyFlow){const base=onlyFlow?cy.nodes().not(".aipp-wall"):cy.nodes(),gap=onlyFlow?cfg.collisionGap+cfg.wallYOffset:cfg.collisionGap;let remaining=0;for(let pass=0;pass<cfg.collisionPasses;pass++){let moved=false;const nodes=base.sort((a,b)=>a.id().localeCompare(b.id()));for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],ab=a.boundingBox({includeLabels:true,includeOverlays:false}),bb=b.boundingBox({includeLabels:true,includeOverlays:false});if(!boxesOverlap(ab,bb,gap))continue;const aWall=a.hasClass("aipp-wall"),bWall=b.hasClass("aipp-wall"),target=bWall?b:aWall?a:b;const delta=(Math.min(ab.y2,bb.y2)-Math.max(ab.y1,bb.y1))+gap;target.position({x:target.position("x"),y:target.position("y")+Math.max(cfg.wallRowGap,delta)});moved=true;}if(!moved)break;}
 const nodes=base.sort((a,b)=>a.id().localeCompare(b.id()));for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)if(boxesOverlap(nodes[i].boundingBox({includeLabels:true,includeOverlays:false}),nodes[j].boundingBox({includeLabels:true,includeOverlays:false}),gap))remaining++;return remaining;}
 function fallbackPositions(graph,native,overrides={}){const cfg=Object.assign({},defaults,overrides),positions={},ids=chamberIds(graph),tank=tankNodeId(native,graph),ordered=ids.filter(x=>x!==tank);if(tank)ordered.push(tank);ordered.forEach((id,i)=>positions[id]={x:180+i*320,y:260});graph.nodes.filter(n=>n.data.kind==="orifice").sort((a,b)=>a.data.nativeIndex-b.data.nativeIndex).forEach((n,i)=>{const edges=graph.edges.filter(e=>e.data.kind==="flow"&&(e.data.source===n.data.id||e.data.target===n.data.id)),ch=edges.map(e=>e.data.source===n.data.id?e.data.target:e.data.source).filter(id=>positions[id]),p=ch.map(id=>positions[id]);positions[n.data.id]=p.length?{x:p.reduce((s,q)=>s+q.x,0)/p.length,y:110-slot(i)*55}:{x:180+i*200,y:110};});const grouped=new Map();wallAnchors(graph,positions).forEach(a=>{const key=a.linked?`${Math.round(a.x)}:${Math.round(a.y)}`:"unassociated";if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(a);});grouped.forEach((items,key)=>items.forEach((a,i)=>{const row=Math.floor(i/5),col=slot(i%5);positions[a.id]={x:a.linked?a.x+col*cfg.wallXSpread:80+col*cfg.wallXSpread,y:a.linked?a.y+cfg.wallYOffset+row*cfg.wallRowGap:520+row*cfg.wallRowGap};}));return positions;}
 function levelsOf(cy){const nodes=cy.nodes().not(".aipp-wall"),groups=new Map();nodes.forEach(n=>{const x=Math.round(n.position("x"));if(!groups.has(x))groups.set(x,[]);groups.get(x).push(n.id());});return [...groups.entries()].sort((a,b)=>a[0]-b[0]).map(([,ids])=>ids);}
 function neighborYs(cy,id,positions){const n=cy.getElementById(id),ys=[];n.connectedEdges().forEach(e=>{if(!e.hasClass("aipp-flow")&&!e.hasClass("aipp-piston-link"))return;const other=e.source().id()===id?e.target():e.source();if(other.hasClass("aipp-wall"))return;const p=positions[other.id()];if(p)ys.push(p.y);});return ys;}
 function countCrossings(edgePairs,positions){let crossings=0;for(let i=0;i<edgePairs.length;i++)for(let j=i+1;j<edgePairs.length;j++){const a=edgePairs[i],b=edgePairs[j];if(a.s===b.s||a.s===b.t||a.t===b.s||a.t===b.t)continue;const p1=positions[a.s],p2=positions[a.t],p3=positions[b.s],p4=positions[b.t];if(!p1||!p2||!p3||!p4)continue;const d=(p2.x-p1.x)*(p4.y-p3.y)-(p2.y-p1.y)*(p4.x-p3.x);if(d===0)continue;const t=((p3.x-p1.x)*(p4.y-p3.y)-(p3.y-p1.y)*(p4.x-p3.x))/d,u=((p3.x-p1.x)*(p2.y-p1.y)-(p3.y-p1.y)*(p2.x-p1.x))/d;if(t>0.001&&t<0.999&&u>0.001&&u<0.999)crossings++;}return crossings;}
 function reduceCrossings(cy,cfg){const levels=levelsOf(cy);if(levels.length<2)return;const edgePairs=cy.edges(".aipp-flow,.aipp-piston-link").map(e=>({s:e.source().id(),t:e.target().id()}));if(!edgePairs.length)return;const original={};cy.nodes().not(".aipp-wall").forEach(n=>original[n.id()]={x:n.position("x"),y:n.position("y")});const positions={};Object.keys(original).forEach(k=>positions[k]={x:original[k].x,y:original[k].y});for(let s=0;s<cfg.crossingSweeps;s++){const order=s%2===0?levels.slice(1):levels.slice(0,-1).reverse();order.forEach(ids=>{const ySlots=ids.map(id=>positions[id].y).sort((a,b)=>a-b),scored=ids.map((id,i)=>{const ys=neighborYs(cy,id,positions),bary=ys.length?ys.reduce((a,b)=>a+b,0)/ys.length:positions[id].y;return{id,i,bary};});scored.sort((a,b)=>a.bary-b.bary||a.i-b.i);scored.forEach((item,i)=>{positions[item.id].y=ySlots[i];});});}const before=countCrossings(edgePairs,original),after=countCrossings(edgePairs,positions),final=after<before?positions:original;cy.nodes().not(".aipp-wall").forEach(n=>{const p=final[n.id()];if(p)n.position({x:p.x,y:p.y});});}
 function finalize(cy,graph,tank,cfg,fit){forceTankRight(cy,tank,cfg);reduceCrossings(cy,cfg);resolveNodeCollisions(cy,cfg,true);alignParallelConnectors(cy,graph,cfg);positionWalls(cy,graph,cfg);last.collisionCount=resolveNodeCollisions(cy,cfg);if(fit&&cy.elements().length)cy.fit(cy.elements(),cfg.padding);last.status="complete";}
 function apply(cy,graph,{native,animate=true,fit=true,...overrides}={}){if(!cy)throw new P2.ProtocolError("AIPP_LAYOUT_CANVAS_REQUIRED","A Cytoscape instance is required.");const cfg=Object.assign({},defaults,overrides,{animate}),root=rootId(graph,native),tank=tankNodeId(native,graph),flow=cy.nodes().not(".aipp-wall").union(cy.edges(".aipp-flow, .aipp-piston-link"));last={status:"running",rootId:root,tankId:tank,wallCount:graph.counts.walls,usedFallback:false,error:"",collisionCount:0};try{if(flow.length){const opts=options(graph,native,cfg);opts.stop=()=>finalize(cy,graph,tank,cfg,fit);flow.layout(opts).run();}else{const pos=fallbackPositions(graph,native,cfg);cy.nodes().forEach(n=>{if(pos[n.id()])n.position(pos[n.id()]);});last.collisionCount=resolveNodeCollisions(cy,cfg);if(fit&&cy.elements().length)cy.fit(cy.elements(),cfg.padding);last.status="complete";}return copy(last);}catch(error){const pos=fallbackPositions(graph,native,cfg);cy.nodes().forEach(n=>{if(pos[n.id()])n.position(pos[n.id()]);});last.collisionCount=resolveNodeCollisions(cy,cfg);if(fit&&cy.elements().length)cy.fit(cy.elements(),cfg.padding);last={status:"complete",rootId:root,tankId:tank,wallCount:graph.counts.walls,usedFallback:true,error:String(error&&error.message||error),collisionCount:last.collisionCount};return copy(last);}}
 function diagnostics(){return copy(last);}
 P2.application.aippTopologyLayout={defaults,options,apply,fallbackPositions,tankNodeId,rootId,wallAnchors,resolveNodeCollisions,reduceCrossings,alignParallelConnectors,diagnostics};
})();
