"use strict";
(function(){
 let card=null,cy=null,currentNode=null,currentRecord=null,currentKind="",closeTimer=0,bound=false,unsubscribe=null,openCount=0,closeCount=0;
 const esc=v=>String(v==null||v===""?"—":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const title=v=>String(v||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
 const quantity=p=>p.mass||p.number||p.amount||"—";
 const ignition=p=>{const v=p&&p.ignition_time;if(v&&typeof v==="object")return `${v.triggering_event||"event"} + ${v.time_delay||"0 s"}`;return v||"—"};
 const shape=p=>{const v=p&&p.shape;if(!v||typeof v!=="object")return "—";return [v.geometry,Object.keys(v).filter(k=>k!=="geometry").slice(0,2).map(k=>`${k.replaceAll("_"," ")}: ${v[k]}`).join(", ")].filter(Boolean).join(" · ")};
 const dl=rows=>`<dl>${rows.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join("")}</dl>`;
 function assembly(){return P2.application.aippDeckDocument.snapshot().native.aipp_calculation.assembly||{}}
 function record(kind,index){const a=assembly(),key=kind==="chamber"?"chambers":kind==="orifice"?"orifices":"walls";return (a[key]||[])[index-1]||null}
 function chamberLabel(index){const c=(assembly().chambers||[])[Number(index)-1];return c?`Chamber ${index}: ${c.label||`Chamber ${index}`}`:`Chamber ${index}`}
 function wallLabel(index){const w=(assembly().walls||[])[Number(index)-1];return w?`Wall ${index}: ${w.label||`Wall ${index}`}`:`Wall ${index}`}
 function ensure(){if(card&&card.isConnected)return card;card=document.createElement("div");card.id="aippTopologyHoverCard";card.className="aipp-chamber-hover-card";card.setAttribute("role","dialog");card.setAttribute("aria-label","Topology entity details");card.hidden=true;document.body.appendChild(card);card.addEventListener("mouseenter",cancelClose);card.addEventListener("mouseleave",scheduleClose);card.addEventListener("mouseover",showRow);card.addEventListener("focusin",showRow);return card}
 function rowIcon(kind,index){return `<span class="aipp-hover-row-icon ${kind}">${kind==="pyro"?`P${index+1}`:"F"}</span>`}
 function chamberContent(c,index){const pyros=Array.isArray(c.pyro)?c.pyro:[],filter=c.filter&&typeof c.filter==="object"?c.filter:null,label=esc(c.label||`Chamber ${index}`);let rows=pyros.map((p,i)=>`<button type="button" class="aipp-hover-row" data-kind="pyro" data-index="${i}">${rowIcon("pyro",i)}<span><strong>${esc(p.label||`Pyro ${i+1}`)}</strong><small>${esc(p.formulation)} · ${esc(quantity(p))}</small></span><i>›</i></button>`).join("");if(filter)rows+=`<button type="button" class="aipp-hover-row" data-kind="filter" data-index="0">${rowIcon("filter",0)}<span><strong>${esc(filter.label||"Filter")}</strong><small>${esc(filter.material)} · ${esc(filter.mass)}</small></span><i>›</i></button>`;if(!rows)rows='<p class="aipp-hover-empty">No Pyros or Filter are defined in this Chamber.</p>';return `<header class="chamber"><small>CHAMBER ${index}</small><strong>${label}</strong></header><div class="aipp-hover-body"><div class="aipp-hover-rows">${rows}</div><div class="aipp-hover-detail"><strong>Hover over a row</strong><span>Individual Pyro or Filter properties will appear here.</span></div></div><footer>Read-only preview. Select the Chamber to edit.</footer>`}
 function detail(kind,index){if(!currentRecord)return "";if(kind==="pyro"){const p=(currentRecord.pyro||[])[index]||{};return `<strong>${esc(p.label||`Pyro ${index+1}`)}</strong>${dl([["Formulation",p.formulation],["Quantity",quantity(p)],["Piles",p.piles],["Ignition",ignition(p)],["Shape",shape(p)]])}`}const f=currentRecord.filter||{};return `<strong>${esc(f.label||"Filter")}</strong>${dl([["Material",f.material],["Mass",f.mass],["Method",f.method],["Orifices",Array.isArray(f.orifices)?f.orifices.join(", "):f.orifices]])}`}
 function showRow(e){const row=e.target.closest&&e.target.closest(".aipp-hover-row");if(!row||!card||currentKind!=="chamber")return;const box=card.querySelector(".aipp-hover-detail");if(box)box.innerHTML=detail(row.dataset.kind,Number(row.dataset.index))}
 function coefficientSummary(dc){if(!dc||typeof dc!=="object")return [["Discharge coefficient","—"]];const basis=dc.basis||"constant",rows=[["Cd basis",title(basis)]];if(String(basis).toLowerCase()==="constant")rows.push(["Cd value",dc.Cd_value]);else{const keys=Object.keys(dc).filter(k=>Array.isArray(dc[k])),points=keys.length?dc[keys[0]].length:0;rows.push(["Table points",points]);for(const key of keys.slice(0,2)){const values=dc[key];if(values.length)rows.push([title(key)+" range",`${values[0]} to ${values[values.length-1]}`])}}return rows}
 function orificeContent(o,index){const rows=[["From",chamberLabel(o.from)],["To",chamberLabel(o.to)],["Diameter",o.diameter],["Quantity",o.num_orif],["Initial state",o.open?"Open":"Closed"],["One way",o.one_way?"Yes":"No"],["Opening condition",o.opens_at],["Viscous-flow factor",o.viscous_flow_factor],...coefficientSummary(o.discharge_coefficient)];return `<header class="orifice"><small>ORIFICE ${index}</small><strong>${esc(o.label||`Orifice ${index}`)}</strong></header><div class="aipp-hover-body"><div class="aipp-hover-detail aipp-hover-summary">${dl(rows)}</div></div><footer>Read-only preview. Select the Orifice to edit.</footer>`}
 function boundary(c){if(!c||typeof c!=="object")return "—";const type=String(c.type||"").toUpperCase();if(c.chamber_index)return `${title(type)} · ${chamberLabel(c.chamber_index)}${c.scale_factor!=null?` · Scale ${c.scale_factor}`:""}${c.heat_transfer_coefficient?` · ${c.heat_transfer_coefficient}`:""}`;if(c.wall_index)return `${title(type)} · ${wallLabel(c.wall_index)}`;if(type==="CONSTANT_TEMPERATURE")return `${title(type)} · ${c.temperature||"—"}`;if(type==="CONSTANT_HEAT")return `${title(type)} · ${c.heat||"—"}`;return title(type)||"—"}
 function wallContent(w,index){const rows=[["Material",w.material],["Initial temperature",w.temperature],["Area",w.area],["Thickness",w.thickness],["Left boundary",boundary(w.left_connection)],["Right boundary",boundary(w.right_connection)]];return `<header class="wall"><small>WALL ${index}</small><strong>${esc(w.label||`Wall ${index}`)}</strong></header><div class="aipp-hover-body"><div class="aipp-hover-detail aipp-hover-summary">${dl(rows)}</div></div><footer>Read-only preview. Select the Wall to edit.</footer>`}
 function content(kind,value,index){return kind==="chamber"?chamberContent(value,index):kind==="orifice"?orificeContent(value,index):wallContent(value,index)}
 function place(){if(!card||!currentNode||!cy)return;const box=currentNode.renderedBoundingBox(),host=cy.container().getBoundingClientRect(),w=card.offsetWidth||390,h=card.offsetHeight||390;let left=host.left+box.x2+14,top=host.top+box.y1;if(left+w>window.innerWidth-12)left=host.left+box.x1-w-14;if(top+h>window.innerHeight-12)top=window.innerHeight-h-12;card.style.left=Math.max(12,left)+"px";card.style.top=Math.max(12,top)+"px"}
 function open(node){if(P2.application.aippTopologyCanvas.presentation!=="phase05b")return;cancelClose();const kind=node.data("kind"),index=Number(node.data("nativeIndex"));if(!["chamber","orifice","wall"].includes(kind))return;const value=record(kind,index);if(!value)return;currentNode=node;currentRecord=value;currentKind=kind;const el=ensure();el.innerHTML=content(kind,value,index);el.hidden=false;el.classList.add("is-visible");openCount++;requestAnimationFrame(place)}
 function close(){if(!card)return;const wasVisible=!card.hidden;card.classList.remove("is-visible");card.hidden=true;currentNode=null;currentRecord=null;currentKind="";if(wasVisible)closeCount++}
 function cancelClose(){clearTimeout(closeTimer)}
 function scheduleClose(){clearTimeout(closeTimer);closeTimer=setTimeout(close,180)}
 function bind(){cy=P2.application.aippTopologyCanvas&&P2.application.aippTopologyCanvas.instance;if(!cy||bound)return false;bound=true;cy.on("mouseover","node",e=>open(e.target));cy.on("mouseout","node",scheduleClose);["pan","zoom","resize"].forEach(name=>cy.on(name,close));cy.on("tap",e=>{if(e.target===cy)close()});window.addEventListener("resize",close);window.addEventListener("aipp:topology-presentation-changed",close);if(P2.application.aippDeckDocument&&P2.application.aippDeckDocument.subscribe)unsubscribe=P2.application.aippDeckDocument.subscribe(close);return true}
 function start(){let attempts=0;const timer=setInterval(()=>{attempts++;if(bind()||attempts>50)clearInterval(timer)},50)}
 function diagnostics(){return{bound,visible:!!card&&!card.hidden,currentKind,cardCount:document.querySelectorAll("#aippTopologyHoverCard").length,openCount,closeCount}}
 P2.application.aippTopologyHoverCard={bind,open,close,content,boundary,coefficientSummary,diagnostics};
 P2.application.aippChamberHoverCard=P2.application.aippTopologyHoverCard;
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();
