"use strict";
(function(){
 const q=id=>document.getElementById(id),M=()=>P2.application.aippNativePropertyInspector,esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
 function title(s){return String(s).replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
 function inputFor(key,value,s){const id=`aippInspectorField-${key}`,common=`id="${esc(id)}" data-aipp-inspector-key="${esc(key)}"`;if(s.selection.kind==="orifice"&&(key==="from"||key==="to")){const n=P2.application.aippDeckDocument.snapshot().native?.aipp_calculation?.assembly?.chambers||[];return `<select ${common}>${n.map((c,i)=>`<option value="${i+1}" ${Number(value)===i+1?"selected":""}>${esc(c.label||`Chamber ${i+1}`)}</option>`).join("")}</select>`;}if(typeof value==="boolean")return `<select ${common}><option value="true" ${value?"selected":""}>True</option><option value="false" ${!value?"selected":""}>False</option></select>`;if(typeof value==="number")return `<input ${common} type="number" step="any" value="${esc(value)}">`;return `<input ${common} type="text" value="${esc(value??"")}">`;}
 function render(s){const host=q("aippInspectorBody"),raw=q("aippInspectorJson");if(!host)return;if(s?.selection?.kind==="piston")return;if(!s.selection){host.innerHTML='<div class="aipp-inspector-empty"><strong>No topology record selected</strong><span>Select a chamber, orifice, or wall.</span></div>';if(raw)raw.textContent="";return;}const scalars=Object.entries(s.working).filter(([,v])=>v===null||["string","number","boolean"].includes(typeof v));host.innerHTML=`<div class="aipp-inspector-head"><span class="aipp-inspector-kind">${esc(s.selection.kind)}</span><strong>${esc(s.selection.label||title(s.selection.kind))}</strong><code>${esc(s.selection.path)}</code></div><div class="aipp-inspector-fields">${scalars.map(([k,v])=>`<label><span>${esc(title(k))}</span>${inputFor(k,v,s)}</label>`).join("")||'<p class="aipp-empty">No scalar properties are available.</p>'}</div><div id="aippInspectorErrors" class="aipp-inspector-errors" ${(s.errors||[]).length?"":"hidden"}>${(s.errors||[]).map(esc).join("<br>")}</div><div class="aipp-inspector-actions"><button id="aippInspectorApply" type="button" ${!s.dirty||(s.errors||[]).length?"disabled":""}>Apply</button><button id="aippInspectorRevert" type="button" class="secondary" ${!s.dirty?"disabled":""}>Revert</button><span class="aipp-inspector-state ${s.dirty?"modified":"clean"}">${s.dirty?"Modified":"Unmodified"}</span></div>`;if(raw)raw.textContent=JSON.stringify(s.working,null,2);host.querySelectorAll("[data-aipp-inspector-key]").forEach(el=>el.addEventListener("input",()=>{const key=el.dataset.aippInspectorKey,old=M().snapshot().working[key];let val=el.value;if(typeof old==="number")val=Number(val);else if(typeof old==="boolean")val=val==="true";M().set(key,val);}));q("aippInspectorApply")?.addEventListener("click",()=>{try{M().apply();P2.application.aippTopologyNavigation.selectPath(s.selection.path);}catch(_){}});q("aippInspectorRevert")?.addEventListener("click",()=>M().revert());}
 function bind(){P2.application.aippTopologyCanvas.subscribeSelection(detail=>{if(detail?.selection?.kind!=="piston")M().load(detail);});M().subscribe(render);render(M().snapshot());}
 P2.application.aippNativePropertyInspectorView={render,bind};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
