"use strict";
(function(){
 const q=id=>document.getElementById(id),qa=s=>Array.from(document.querySelectorAll(s));let detail=null,active="properties";
 const inspector=()=>P2.application.aippNativePropertyInspector,chamberEditor=()=>P2.application.aippChamberEditor,orificeEditor=()=>P2.application.aippOrificeEditor,wallEditor=()=>P2.application.aippWallEditor,pistonEditor=()=>P2.application.aippPistonEditor;
 function selectedKind(){return detail?.selection?.kind||inspector().snapshot().selection?.kind||"";}
 function dirty(){if(selectedKind()==="chamber"&&chamberEditor())return !!chamberEditor().snapshot().dirty;if(selectedKind()==="orifice"&&orificeEditor())return !!orificeEditor().snapshot().dirty;if(selectedKind()==="wall"&&wallEditor())return !!wallEditor().snapshot().dirty;if(selectedKind()==="piston"&&pistonEditor())return !!pistonEditor().snapshot().dirty;return !!inspector().snapshot().dirty;}
 function setTab(name){active=name;if(selectedKind()==="chamber"&&chamberEditor())chamberEditor().setTab(name);if(selectedKind()==="orifice"&&orificeEditor())orificeEditor().setTab(name);qa("[data-context-tab]").forEach(b=>{const on=b.dataset.contextTab===name;b.classList.toggle("is-active",on);b.setAttribute("aria-selected",String(on));});qa("[data-context-pane]").forEach(p=>p.hidden=p.dataset.contextPane!==name);}
 function configure(d){if(!d)return;detail=d;const s=d.selection||{},kind=s.kind||"";q("aippContextEditor")?.classList.toggle("is-wall-mode",kind==="wall");q("aippContextEditor")?.classList.toggle("is-piston-mode",kind==="piston");q("aippContextKind").textContent=kind||"Entity";q("aippContextTitle").textContent=kind==="orifice"?"Orifice editor":kind==="piston"?"Piston editor":(s.label||kind||"Editor");q("aippContextPath").textContent=kind==="orifice"?`${s.label||`Orifice ${s.nativeIndex||s.index||""}`} · ${s.path||""}`:(s.path||"");qa('[data-context-tab="pyros"],[data-context-tab="filters"]').forEach(b=>b.hidden=kind!=="chamber");qa('[data-context-tab="opening"],[data-context-tab="discharge"]').forEach(b=>b.hidden=kind!=="orifice");if((kind!=="chamber"&&(active==="pyros"||active==="filters"))||(kind!=="orifice"&&(active==="opening"||active==="discharge")))active="properties";setTab(active);if(kind==="orifice"&&orificeEditor())orificeEditor().load(d);if(kind==="wall"&&wallEditor())wallEditor().load(d);if(kind==="piston"&&pistonEditor()){pistonEditor().load(d);safeRender(()=>P2.application.aippPistonEditorView?.render());}q("aippEditSelected").disabled=false;}
 function safeRender(fn){try{fn?.();}catch(error){try{P7?.logger?.error?.("render","Production entity editor render failed",{message:error?.message||String(error)});}catch(_){}}}
 function open(){if(!detail)return;const kind=selectedKind();if(kind==="chamber"&&chamberEditor())active=chamberEditor().snapshot().activeTab||"properties";if(kind==="orifice"&&orificeEditor())active=orificeEditor().snapshot().activeTab||"properties";q("aippContextEditor").classList.add("is-open");q("aippContextEditor").setAttribute("aria-hidden","false");q("aippEditorBackdrop").hidden=false;setTab(active);q("aippContextClose").focus();if(kind==="orifice"&&orificeEditor())safeRender(()=>P2.application.aippOrificeEditorView?.render(orificeEditor().snapshot()));if(kind==="wall"&&wallEditor())safeRender(()=>P2.application.aippWallEditorView?.render(wallEditor().snapshot()));if(kind==="chamber"&&chamberEditor()){safeRender(()=>P2.application.aippChamberEditorView?.render(chamberEditor().snapshot()));safeRender(()=>P2.application.aippChamberPyroView?.render());safeRender(()=>P2.application.aippChamberFilterView?.render());}}
 function close(force){if(!force&&dirty()&&!window.confirm("Discard unapplied entity changes?"))return false;if(force||dirty()){if(selectedKind()==="chamber"&&chamberEditor())chamberEditor().revert();else if(selectedKind()==="orifice"&&orificeEditor())orificeEditor().revert();else if(selectedKind()==="wall"&&wallEditor())wallEditor().revert();else if(selectedKind()==="piston"&&pistonEditor())pistonEditor().revert();else inspector().revert();}q("aippContextEditor").classList.remove("is-open");q("aippContextEditor").setAttribute("aria-hidden","true");q("aippEditorBackdrop").hidden=true;return true;}
 function switchView(name){qa("[data-aipp-view]").forEach(b=>b.classList.toggle("is-selected",b.dataset.aippView===name));const frame=q("aippEditorFrame"),top=document.querySelector(".aipp-topology-workbench"),alt=q("aippAlternateView");frame?.classList.toggle("is-raw-view",name==="raw");top.hidden=name!=="topology";alt.hidden=name==="topology";if(name==="raw")P2.application.aippRawJsonEditorView?.open(alt);else if(name==="topology"){const redraw=()=>{const canvas=P2.application.aippTopologyCanvas;if(!canvas||top.hidden)return;void frame?.offsetWidth;canvas.render?.(true);const cy=canvas.instance;if(cy){cy.resize();canvas.fit?.();}};redraw();window.setTimeout(redraw,0);window.setTimeout(redraw,120);}else alt.innerHTML=`<h2>${name[0].toUpperCase()+name.slice(1)}</h2><p>This is a single active workspace surface. Entity editors open in the contextual drawer and are not stacked below the topology.</p>`;}
 function bind(){const frame=q("aippEditorFrame"),toggle=q("aippDeckNavigatorToggle");if(!frame||!toggle)return;toggle.addEventListener("click",()=>{const on=frame.classList.toggle("is-nav-open");toggle.setAttribute("aria-expanded",String(on));});q("aippDeckNavigatorClose").addEventListener("click",()=>{frame.classList.remove("is-nav-open");toggle.setAttribute("aria-expanded","false");});q("aippEditSelected").addEventListener("click",open);q("aippContextClose").addEventListener("click",()=>close(false));q("aippEditorBackdrop").addEventListener("click",()=>close(false));qa("[data-context-tab]").forEach(b=>b.addEventListener("click",()=>setTab(b.dataset.contextTab)));qa("[data-aipp-view]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.aippView)));P2.application.aippTopologyCanvas.subscribeSelection(configure);q("aippTopologyCanvas").addEventListener("dblclick",open);document.addEventListener("keydown",e=>{if(e.key==="Escape"&&q("aippContextEditor").classList.contains("is-open"))close(false);});}
 P2.application.aippContextualWorkspace={open,close,setTab};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
