"use strict";
(function(){
 const copy=v=>JSON.parse(JSON.stringify(v));
 const P=()=>P2.application.aippChamberPyros,F=()=>P2.application.aippChamberFilters,E=()=>P2.application.aippChamberEditor,D=()=>P2.application.aippDeckDocument;
 let hydrating=false,lastSelectionKey="",lastMasterRevision=-1,lastChamberToken="";
 function parseQuantity(text,fallbackUnit){const q=P().parseQuantity(text);return q||{value:0,unit:fallbackUnit};}
 function pyroFromNative(native,index){const n=copy(native||{}),mass=parseQuantity(n.mass,"g"),delay=parseQuantity(n.ignition_time?.time_delay,"s"),shape=copy(n.shape||{}),shapeType=P().canonicalText(shape.geometry||n.shape_type||"sphere");delete shape.geometry;return Object.assign(n,{id:`native-pyro-${String(index+1).padStart(4,"0")}`,name:n.name||`Pyro ${index+1}`,formulation:P().canonicalText(n.formulation),quantity_type:n.quantity_type||("number" in n?"number":"mass"),mass_g:Number(mass.value),mass_unit:mass.unit||"g",number:Number(n.number||1),piles:Number(n.piles||1),ignition:{triggering_event:P().canonicalText(n.ignition_time?.triggering_event||n.ignition?.triggering_event||"SimStart"),delay_s:Number(delay.value),delay_unit:delay.unit||"s"},shape_type:shapeType,shape,formulation_working_copy:copy(n.formulation_working_copy||{}),burn_rate_modifications:copy(n.burn_rate_modifications||{})});}
 function pyroToNative(editor){const n=copy(editor||{});["id","name","formulation_working_copy","quantity_type","mass_g","mass_unit","number","ignition","shape_type","unsupported_imported_shape"].forEach(k=>delete n[k]);if(editor.quantity_type==="number"){n.number=Number(editor.number||1);delete n.mass;}else{n.mass=`${Number(editor.mass_g||0)} ${editor.mass_unit||"g"}`;delete n.number;}n.ignition_time={...(n.ignition_time||{}),triggering_event:editor.ignition?.triggering_event||"SimStart",time_delay:`${Number(editor.ignition?.delay_s||0)} ${editor.ignition?.delay_unit||"s"}`};n.shape={...(editor.shape||{}),geometry:editor.shape_type||"sphere"};return n;}
 function installProjectionAdapters(){const pm=P(),fm=F();if(!pm.hydrateFromNative){pm.hydrateFromNative=function(chamberId,nativePyros){const rows=(Array.isArray(nativePyros)?nativePyros:[]).map(pyroFromNative);pm.reset();const internal=pm.snapshot();if(!rows.length)return internal;/* Replace through supported creation-independent state adapter below. */return pm.replaceProjection(rows,chamberId);};pm.exportNative=()=>pm.snapshot().pyros.map(pyroToNative);}if(!fm.exportNative)fm.exportNative=()=>{const f=fm.selected();if(!f)return null;const n=copy(f);delete n.id;delete n.name;return n;};}
 function replacePyroProjection(rows,chamberId){const pm=P();pm.reset();const state=pm.snapshot();/* Model has closure state, so import rows through a guarded adapter exposed by the source patch. */return pm.replaceProjection(rows,chamberId);}
 function hydrateFromMaster(force=false){const es=E()?.snapshot?.(),sel=es?.selection;if(!sel)return;const snap=D().snapshot(),key=`${sel.index}:${sel.path||""}`;if(!force&&key===lastSelectionKey&&snap.meta.revision===lastMasterRevision)return;const chamber=snap.native.aipp_calculation.assembly.chambers[sel.index-1];if(!chamber)return;const chamberToken=JSON.stringify(chamber);hydrating=true;try{P().replaceProjection((Array.isArray(chamber.pyro)?chamber.pyro:[]).map(pyroFromNative),sel.id||`chamber-${sel.index}`);F().replaceProjection(chamber.filter,sel.id||`chamber-${sel.index}`,sel.index,snap.native.aipp_calculation.assembly.orifices);lastSelectionKey=key;lastMasterRevision=snap.meta.revision;lastChamberToken=chamberToken;P2.application.aippChamberPyroView?.render?.();P2.application.aippChamberFilterView?.render?.();}finally{hydrating=false;}}
 function syncWorkingProjection(){if(hydrating)return;const e=E(),s=e?.snapshot?.();if(!s?.selection)return;e.set("pyro",P().snapshot().pyros.map(pyroToNative));const filter=F().exportNative();e.set("filter",filter===null?undefined:filter);}
 function wrapWorkingMutations(model,names){for(const name of names){const original=model[name];if(typeof original!=="function"||original.__workingProjectionWrapped)continue;const wrapped=function(){const result=original.apply(model,arguments);syncWorkingProjection();return result;};wrapped.__workingProjectionWrapped=true;model[name]=wrapped;}}
 function install(){installProjectionAdapters();E().subscribe(s=>{const key=s.selection?`${s.selection.index}:${s.selection.path||""}`:"";if(key!==lastSelectionKey)hydrateFromMaster(true);});D().subscribe(s=>{if(s.meta.revision===lastMasterRevision)return;lastMasterRevision=s.meta.revision;const sel=E()?.snapshot?.()?.selection;if(!sel)return;const chamber=s.native?.aipp_calculation?.assembly?.chambers?.[sel.index-1];const token=chamber?JSON.stringify(chamber):"";if(token!==lastChamberToken)hydrateFromMaster(true);});hydrateFromMaster(true);P2.application.aippMasterJsonWorkingProjection={hydrateFromMaster,syncWorkingProjection,canonicalSource:"P2.application.aippDeckDocument.native"};}
 install();
})();
