"use strict";
(function(){
 const q=id=>document.getElementById(id),M=()=>P2.application.aippChamberEditor,esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const labels={volume:"Volume",temperature:"Temperature",pressure:"Pressure",mass:"Mass",density:"Density",moles:"Moles"};
 let showAllSpecies=false;
 function quantityField(key,s){const x=M().quantity(key),U=P2.application.aippQuaffUnits,displayUnit=U.canonicalSymbol(x.unit),units=M().unitCatalog()[key]||[];return `<label class="aipp-chamber-state-field"><span>${labels[key]}</span><div class="aipp-m88-quantity"><input type="number" step="any" min="0" data-chamber-quantity-value="${key}" value="${esc(x.valueText)}"><select data-chamber-quantity-unit="${key}" aria-label="${labels[key]} unit">${units.map(u=>`<option value="${esc(u)}" ${u===displayUnit?"selected":""}>${esc(u)}</option>`).join("")}</select></div><small>Original: <code>${esc(s.original?.[key]??"")}</code></small></label>`;}
 function mixtureEditor(s){
  const mf=s.working.mol_fractions||{},catalog=M().speciesCatalog(),allNames=[...new Set([...catalog,...Object.keys(mf)])],names=showAllSpecies?allNames:allNames.filter(k=>Math.abs(Number(mf[k]||0))>0),total=Object.values(mf).reduce((a,v)=>a+Number(v||0),0),presetMap=M().presets(),presets=Object.keys(presetMap).filter(k=>k!=="air"),same=(a,b)=>{const keys=[...new Set([...Object.keys(a),...Object.keys(b)])];return keys.every(k=>Math.abs(Number(a[k]||0)-Number(b[k]||0))<=1e-10);},selected=presets.find(k=>same(mf,presetMap[k]))||"";
  const row=(k,i)=>{const standard=catalog.includes(k),species=standard?`<select data-mixture-species aria-label="Species ${i+1}">${catalog.map(x=>`<option value="${esc(x)}" ${x===k?"selected":""}>${esc(x)}</option>`).join("")}</select>`:`<input data-mixture-species value="${esc(k)}" aria-label="Custom species ${i+1}">`;return `<div class="aipp-mixture-row ${standard?"":"is-custom"}" data-mixture-row data-original-species="${esc(k)}">${species}<input type="number" min="0" step="any" data-mixture-fraction value="${esc(mf[k]??0)}" aria-label="${esc(k)} mole fraction"><button type="button" data-mixture-remove="${esc(k)}" aria-label="Remove ${esc(k)}">×</button></div>`;};
  return `<section class="aipp-mixture-editor"><header class="aipp-mixture-header"><div><h3>Mixture composition</h3><p>The applied preset name is retained until the composition is changed.</p></div><span class="aipp-mixture-sum ${Math.abs(total-1)>1e-6?"bad":""}">Sum ${total.toFixed(6)}</span></header><div class="aipp-mixture-preset-card"><label><span>Named gas mixture</span><select id="aippMixturePreset"><option value="">Custom / current deck mixture</option>${presets.map(k=>`<option value="${esc(k)}" ${k===selected?"selected":""}>${esc(k)}</option>`).join("")}</select></label><button type="button" id="aippMixtureApplyPreset" class="primary">Apply preset</button></div><div class="aipp-mixture-secondary-actions"><button type="button" id="aippMixtureToggle">${showAllSpecies?"Show nonzero species":"Show all species"}</button><button type="button" id="aippMixtureNormalize">Normalize custom mixture</button><button type="button" id="aippMixtureAddCustom">Add custom species</button></div><div class="aipp-mixture-rows">${names.map(row).join("")}</div>${showAllSpecies?'':'<p class="aipp-mixture-hint">Only nonzero species are shown. Use “Show all species” to edit the complete species catalog.</p>'}</section>`;
 }
 function render(s){const actions=q("aippChamberActionsBar");if(!s.selection){if(actions)actions.innerHTML="";return;}const host=q("aippInspectorBody")||q("aippChamberProperties"),raw=q("aippInspectorJson");const isTank=s.tankId===s.selection.index,tankControl=isTank?'<span class="aipp-chamber-tank-badge">Tank chamber</span>':'<button type="button" id="aippChamberSetTank">Set as Tank</button>';if(host)host.innerHTML=`<div class="aipp-inspector-head"><span class="aipp-inspector-kind">chamber</span><strong>${esc(s.selection.label||"Chamber")}</strong><code>${esc(s.selection.path)}</code><span class="aipp-chamber-dirty ${s.dirty?"is-dirty":""}">${s.dirty?"Unapplied changes":"Clean"}</span></div><label class="aipp-chamber-label-field"><span>Chamber label</span><input type="text" data-chamber-text="label" value="${esc(s.working.label??s.working.name??"")}" aria-label="Chamber label"><small>This label is used in the topology and saved native deck.</small></label><div class="aipp-chamber-tank-field">${tankControl}</div><div class="aipp-chamber-state-grid">${M().quantityKeys().filter(k=>s.working[k]!==undefined).map(k=>quantityField(k,s)).join("")||'<p>No controlled chamber-state quantities are present in this record.</p>'}</div>${mixtureEditor(s)}`;if(raw)raw.textContent=JSON.stringify(s.working,null,2);const actionsHtml=`<div id="aippInspectorErrors" class="aipp-inspector-errors" ${s.errors.length?"":"hidden"}>${s.errors.map(esc).join("\n")}</div><div class="aipp-inspector-actions"><button type="button" id="aippInspectorApply" class="primary" ${s.dirty?"":"disabled"}>Apply</button><button type="button" id="aippInspectorRevert" ${s.dirty?"":"disabled"}>Revert</button><button type="button" id="aippInspectorValidate">Validate</button></div>`;if(actions)actions.innerHTML=actionsHtml;else if(host)host.insertAdjacentHTML("beforeend",actionsHtml);}
 function validationRoot(){return q("aippChamberValidationEnvironment");}
 function showValidationTab(name){
  const root=validationRoot();if(!root)return;
  root.querySelectorAll("[data-context-tab]").forEach(b=>{const on=b.dataset.contextTab===name;b.classList.toggle("is-active",on);b.setAttribute("aria-selected",String(on));b.tabIndex=on?0:-1;});
  root.querySelectorAll("[data-context-pane]").forEach(p=>{p.hidden=p.dataset.contextPane!==name;});if(name==="pyros"){const manager=q("aippChamberPyroManager");if(manager){manager.hidden=false;manager.style.removeProperty("display");const pane=manager.closest("[data-context-pane]");if(pane)pane.hidden=false;}}
 }
 function prepareValidationEnvironment(){
  const pyroMount=q("aippValidationPyroMount"),filterMount=q("aippValidationFilterMount"),pyro=q("aippChamberPyroManager"),filter=q("aippChamberFilterManager");
  if(pyroMount&&pyro&&pyro.parentElement!==pyroMount)pyroMount.appendChild(pyro);
  if(filterMount&&filter&&filter.parentElement!==filterMount)filterMount.appendChild(filter);
  showValidationTab(M().snapshot().activeTab||"properties");
 }
 function syncValidationSummary(s){
  const label=q("aippValidationChamberLabel"),path=q("aippValidationChamberPath"),chip=q("aippValidationState"),title=q("aippContextTitle"),contextPath=q("aippContextPath");
  if(label)label.textContent=s.selection?.label||"No chamber selected";
  if(path)path.textContent=s.selection?.path||"Waiting for chamber selection";
  if(title)title.textContent=s.selection?.label||"Chamber editor";
  if(contextPath)contextPath.textContent=s.selection?.path||"No chamber selected";
  if(chip){chip.textContent=s.dirty?"Modified":"Unmodified";chip.classList.toggle("modified",s.dirty);chip.classList.toggle("clean",!s.dirty);}
  showValidationTab(s.activeTab||"properties");
 }
 function loadFirstValidationChamber(){
  const snap=P2.application.aippDeckDocument.snapshot(),record=snap.native?.aipp_calculation?.assembly?.chambers?.[0];
  if(!record)return;
  M().load({kind:"chamber",index:1,label:String(record.label||"Chamber 1"),path:"aipp_calculation.assembly.chambers[0]"});
 }
 function bind(){
  prepareValidationEnvironment();
  document.addEventListener("input",e=>{if(!M().snapshot().selection)return;const textKey=e.target.dataset.chamberText;if(textKey){M().set(textKey,e.target.value);return;}const key=e.target.dataset.chamberQuantityValue;if(key){const unit=document.querySelector(`[data-chamber-quantity-unit="${key}"]`)?.value||"";try{M().setQuantity(key,e.target.value,unit);}catch(_){}return;}});
  document.addEventListener("click",e=>{const tab=e.target.closest?.("[data-context-tab]");if(tab){M().setTab(tab.dataset.contextTab);showValidationTab(tab.dataset.contextTab);document.querySelectorAll("[data-context-pane]").forEach(p=>p.hidden=p.dataset.contextPane!==tab.dataset.contextTab);if(tab.dataset.contextTab==="pyros"){const manager=q("aippChamberPyroManager");if(manager){manager.hidden=false;manager.style.display="block";let pane=manager.closest("[data-context-pane]");if(pane)pane.hidden=false;}}return;}if(e.target.closest?.("#aippValidationChamber")){loadFirstValidationChamber();return;}if(e.target.id==="aippChamberSetTank"){M().setAsTank();return;}if(e.target.dataset.mixturePreset)M().applyMixturePreset(e.target.dataset.mixturePreset);else if(e.target.id==="aippInspectorValidate")M().validate();else if(e.target.id==="aippInspectorRevert")M().revert();else if(e.target.id==="aippInspectorApply")M().apply();});
  document.addEventListener("change",e=>{const unit=e.target.dataset.chamberQuantityUnit;if(unit){try{M().changeQuantityUnit(unit,e.target.value);}catch(_){M().validate();}}});
  document.addEventListener("change",e=>{const row=e.target.closest?.("[data-mixture-row]");if(row){try{M().updateMixtureSpecies(row.dataset.originalSpecies,row.querySelector("[data-mixture-species]").value,row.querySelector("[data-mixture-fraction]").value);}catch(_){M().validate();}}});
  document.addEventListener("click",e=>{if(e.target.id==="aippMixtureToggle"){showAllSpecies=!showAllSpecies;render(M().snapshot());}else if(e.target.id==="aippMixtureApplyPreset"){const v=q("aippMixturePreset")?.value;if(v)M().applyMixturePreset(v);}else if(e.target.id==="aippMixtureNormalize"){try{M().normalizeMixture();}catch(_){M().validate();}}else if(e.target.id==="aippMixtureAddCustom")M().addMixtureSpecies("Custom species",0);else if(e.target.dataset.mixtureRemove)M().removeMixtureSpecies(e.target.dataset.mixtureRemove);});
  document.addEventListener("keydown",e=>{const tab=e.target.closest?.("#aippChamberValidationEnvironment [data-context-tab]");if(!tab||!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;const tabs=[...validationRoot().querySelectorAll("[data-context-tab]")];let i=tabs.indexOf(tab);if(e.key==="ArrowRight")i=(i+1)%tabs.length;else if(e.key==="ArrowLeft")i=(i-1+tabs.length)%tabs.length;else if(e.key==="Home")i=0;else i=tabs.length-1;e.preventDefault();tabs[i].click();tabs[i].focus();});
  M().subscribe(x=>{const active=document.activeElement,isActiveEdit=!!active?.matches?.("[data-chamber-text],[data-chamber-quantity-value],[data-mixture-fraction],[data-mixture-species]");if(isActiveEdit){const badge=document.querySelector(".aipp-chamber-dirty");if(badge){badge.classList.toggle("is-dirty",x.dirty);badge.textContent=x.dirty?"Unapplied changes":"Clean";}const apply=q("aippInspectorApply"),revert=q("aippInspectorRevert");if(apply)apply.disabled=!x.dirty;if(revert)revert.disabled=!x.dirty;const raw=q("aippInspectorJson");if(raw)raw.textContent=JSON.stringify(x.working,null,2);}else render(x);syncValidationSummary(x);});
  const initial=M().snapshot();render(initial);syncValidationSummary(initial);
 }
 P2.application.aippChamberEditorView={render};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
