"use strict";
(function(){
 const cp=v=>JSON.parse(JSON.stringify(v)),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),listeners=new Set();
 const C=()=>P2.application.aippOrifices;
 let state={selection:null,original:null,working:null,dirty:false,errors:[],impacts:[],activeTab:"properties"};
 function emit(){const s=snapshot();listeners.forEach(f=>{try{f(s);}catch(_){}});return s;} function snapshot(){return cp(state);}
 function assembly(){return P2.application.aippDeckDocument.snapshot().native.aipp_calculation.assembly;}
 function normalizeDischarge(r){if(!r||typeof r!=="object")return r;const d=r.discharge_coefficient||(r.discharge_coefficient={basis:"constant",Cd_value:.8}),b=d.basis||"constant";d.basis=b;if(b==="time"||b==="pressure"){if(!["discrete","interpolate"].includes(d.continuity))d.continuity="discrete";const uk=b+"_units",ak=b+"_array";if(!P2.application.aippQuaffUnits.isAllowed(b,d[uk]))d[uk]=P2.application.aippQuaffUnits.units(b)[0];if(!Array.isArray(d[ak])||!Array.isArray(d.Cd_array)||d[ak].length!==d.Cd_array.length||!d[ak].length){d[ak]=[0,1];d.Cd_array=[0,0];}}else if(!Number.isFinite(Number(d.Cd_value)))d.Cd_value=.8;return r;}
 function load(detail){if(!detail||detail.selection?.kind!=="orifice")return snapshot();const normalized=normalizeDischarge(cp(detail.value||{}));state={selection:cp(detail.selection),original:cp(normalized),working:cp(normalized),dirty:false,errors:[],impacts:[],activeTab:"properties"};return emit();}
 function set(path,value){let p=String(path).split("."),o=state.working;while(p.length>1){let k=p.shift();if(!o[k]||typeof o[k]!=="object")o[k]={};o=o[k];}o[p[0]]=value;if(path==="discharge_coefficient.basis")normalizeDischarge(state.working);return refresh();}
 function replace(path,value){return set(path,cp(value));} function setTab(t){state.activeTab=t;return emit();}
 function tableBasis(){const b=state.working?.discharge_coefficient?.basis;if(b!=="time"&&b!=="pressure")throw new P2.ProtocolError("AIPP_ORIFICE_CD_TABLE_REQUIRED",String(b));return b;}
 function tableCandidate(b,x,y){const d=cp(state.working.discharge_coefficient||{});d[b+"_array"]=x.map(Number);d.Cd_array=y.map(Number);const probe=cp(state.working);probe.discharge_coefficient=d;const errors=validate(probe);if(errors.length)throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_TABLE",errors.join(" "));return d;}
 function addTableRow(){const b=tableBasis(),d=state.working.discharge_coefficient,x=(d[b+"_array"]||[]).slice(),y=(d.Cd_array||[]).slice(),last=x.length?Number(x[x.length-1]):0;x.push(x.length?last+1:0);y.push(y.length?Number(y[y.length-1]):0);d[b+"_array"]=x;d.Cd_array=y;return refresh();}
 function removeTableRow(i){const b=tableBasis(),d=state.working.discharge_coefficient,x=(d[b+"_array"]||[]).slice(),y=(d.Cd_array||[]).slice();i=Number(i);if(i<0||i>=x.length)throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_ROW",String(i));x.splice(i,1);y.splice(i,1);d[b+"_array"]=x;d.Cd_array=y;return refresh();}
 function setTableCell(i,axis,value){const b=tableBasis(),d=state.working.discharge_coefficient,key=axis==="x"?b+"_array":"Cd_array",a=(d[key]||[]).slice();a[Number(i)]=Number(value);d[key]=a;return refresh();}
 function parseCsv(text){const b=tableBasis(),d=state.working.discharge_coefficient,unit=String(d[b+"_units"]||""),lines=String(text??"").replace(/^\uFEFF/,"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(lines.length<3)throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_CSV","CSV requires a units row and at least two data rows.");const cells=v=>v.split(",").map(x=>x.trim()),head=cells(lines.shift());if(head.length!==2)throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_CSV_COLUMNS","CSV must contain exactly two columns.");if(head[0]!==unit||head[1].toLowerCase()!=="cd")throw new P2.ProtocolError("AIPP_ORIFICE_CD_CSV_UNIT_MISMATCH",`CSV header must exactly match ${unit},Cd.`);const rows=lines.map((line,i)=>{const c=cells(line);if(c.length!==2)throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_CSV_COLUMNS",`Data row ${i+2} must contain exactly two columns.`);const x=Number(c[0]),y=Number(c[1]);if(!Number.isFinite(x)||!Number.isFinite(y))throw new P2.ProtocolError("AIPP_INVALID_ORIFICE_CD_CSV_VALUE",`Data row ${i+2} must be numeric.`);return [x,y];});tableCandidate(b,rows.map(r=>r[0]),rows.map(r=>r[1]));return {basis:b,unit,x:rows.map(r=>r[0]),y:rows.map(r=>r[1])};}
 function importCsvText(text){const c=parseCsv(text),d=state.working.discharge_coefficient;d[c.basis+"_array"]=c.x;d.Cd_array=c.y;return refresh();}
 function refresh(){state.dirty=!eq(state.working,state.original);state.errors=validate(state.working);state.impacts=impact(state.working);return emit();}
 function parseQty(v,type){return P2.application.aippQuaffUnits.parse(type,String(v||""));}
 function validate(r){const e=[],a=assembly(),n=(a.chambers||[]).length,from=Number(r.from),to=Number(r.to),num=Number(r.num_orif);
  if(!Number.isInteger(from)||from<1||from>n)e.push("From chamber must reference an existing chamber.");if(!Number.isInteger(to)||to<1||to>n)e.push("To chamber must reference an existing chamber.");if(from===to)e.push("From and To chambers must be different.");
  if(!Number.isInteger(num)||num<1)e.push("Number of orifices must be an integer of one or more.");try{const q=parseQty(r.diameter,"length");if(!(q.value>0))e.push("Diameter must be greater than zero.");}catch(x){e.push("Diameter must be a valid Quaff length.");}
  const vf=Number(r.viscous_flow_factor);if(!Number.isFinite(vf)||vf<0||vf>1.5)e.push("Viscous flow factor must be between 0 and 1.5.");
  if(typeof r.open!=="boolean")e.push("Initial open state must be true or false.");if(typeof r.one_way!=="boolean")e.push("One-way state must be true or false.");
  if(typeof r.opens_at==="string"){try{const q=parseQty(r.opens_at,"pressure");if(q.value<0)e.push("Opening pressure must be nonnegative.");}catch(x){e.push("Opening threshold must be a valid Quaff pressure.");}}
  else if(r.opens_at&&typeof r.opens_at==="object"){if(!String(r.opens_at.triggering_event||"").trim())e.push("Triggering event is required.");try{const q=parseQty(r.opens_at.time_delay,"time");if(q.value<0)e.push("Event time delay must be nonnegative.");}catch(x){e.push("Event time delay must be a valid Quaff time.");}}else e.push("Opening criterion must be pressure- or event-based.");
  const d=r.discharge_coefficient||{},basis=d.basis;if(!["constant","time","pressure"].includes(basis))e.push("Unsupported discharge-coefficient basis is available in Raw mode only.");
  if(basis==="constant"){const c=Number(d.Cd_value);if(!Number.isFinite(c)||c<0||c>1.5)e.push("Cd value must be between 0 and 1.5.");}
  if(basis==="time"||basis==="pressure"){const key=basis+"_array",u=basis+"_units",x=d[key],y=d.Cd_array;if(!["discrete","interpolate"].includes(d.continuity))e.push("Continuity must be discrete or interpolate.");try{if(!P2.application.aippQuaffUnits.isAllowed(basis,d[u]))throw 0;}catch(_){e.push(`${basis} units are not Quaff-safe.`);}if(!Array.isArray(x)||!Array.isArray(y)||!x.length||x.length!==y.length)e.push("Lookup arrays must be nonempty and have equal lengths.");else{x.forEach((v,i)=>{if(!Number.isFinite(Number(v))||i&&Number(v)<=Number(x[i-1]))e.push("Lookup coordinates must be finite and strictly increasing.");});y.forEach(v=>{const c=Number(v);if(!Number.isFinite(c)||c<0||c>1.5)e.push("Lookup Cd values must be between 0 and 1.5.");});}}
  return Array.from(new Set(e));}
 function impact(r){const out=[],idx=state.selection?.index,old=Number(state.original?.from),next=Number(r.from);if(idx&&old!==next)(assembly().chambers||[]).forEach((c,i)=>{const f=c.filter;if(f&&Array.isArray(f.orifices)&&f.orifices.includes(idx)&&i+1!==next)out.push({chamber:i+1,orifice:idx});});return out;}
 function apply(){state.errors=validate(state.working);if(state.errors.length){emit();throw new P2.ProtocolError("AIPP_INVALID_ORIFICE",state.errors.join("; "));}const path=state.selection.path,w=cp(state.working),imp=impact(w);P2.application.aippDeckDocument.mutate("orifice-editor-apply",d=>{const a=d.native.aipp_calculation.assembly;a.orifices[state.selection.index-1]=w;imp.forEach(x=>{const f=a.chambers[x.chamber-1].filter;f.orifices=f.orifices.filter(n=>n!==x.orifice);});});state.original=cp(w);state.dirty=false;state.impacts=[];emit();P2.application.aippTopologyCanvas.render(true);P2.application.aippTopologyNavigation.selectPath(path);return snapshot();}
 function revert(){state.working=cp(state.original);state.errors=[];state.impacts=[];state.dirty=false;return emit();} function subscribe(f){listeners.add(f);return()=>listeners.delete(f);}
 function events(){const a=assembly(),out=["SimStart"];(a.orifices||[]).forEach((_,i)=>out.push(`O${i+1}_opened`,`O${i+1}_closed`));(a.chambers||[]).forEach((c,i)=>(c.pyros||[]).forEach((_,j)=>out.push(`C${i+1}P${j+1}_ignited`,`C${i+1}P${j+1}_extinguished`)));return out;}
 function idAt(index){const item=C().snapshot().items[index-1];if(!item)throw new P2.ProtocolError("AIPP_UNKNOWN_TOPOLOGY_PATH",String(index));return item.id;}
 function loadIndex(index){const item=C().snapshot().items[index-1];if(!item)throw new P2.ProtocolError("AIPP_UNKNOWN_TOPOLOGY_PATH",String(index));return load({selection:{kind:"orifice",index,nativeIndex:index,label:item.name,path:`aipp_calculation.assembly.orifices[${index-1}]`},value:item.native});}
 function create(){const id=C().create();const index=C().snapshot().items.findIndex(x=>x.id===id)+1;return loadIndex(index);}
 function duplicate(){if(!state.selection)throw new P2.ProtocolError("AIPP_NO_ORIFICE_SELECTED","Select an orifice first.");const id=C().duplicate(idAt(state.selection.index));const index=C().snapshot().items.findIndex(x=>x.id===id)+1;return loadIndex(index);}
 function move(delta){if(!state.selection)throw new P2.ProtocolError("AIPP_NO_ORIFICE_SELECTED","Select an orifice first.");const id=idAt(state.selection.index);C().move(id,delta);const index=C().snapshot().items.findIndex(x=>x.id===id)+1;return loadIndex(index);}
 function remove(){if(!state.selection)throw new P2.ProtocolError("AIPP_NO_ORIFICE_SELECTED","Select an orifice first.");C().remove(idAt(state.selection.index));const items=C().snapshot().items;return items.length?loadIndex(1):load(null);}
 P2.application.aippOrificeEditor={addTableRow,removeTableRow,setTableCell,parseCsv,importCsvText,load,set,replace,setTab,validate,apply,revert,create,duplicate,move,remove,snapshot,subscribe,events};
})();
