"use strict";
(function(){
 const q=i=>document.getElementById(i),E=()=>P2.application.aippOrificeEditor,U=()=>P2.application.aippQuaffUnits;
 const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
 const options=(items,value,label=x=>x)=>items.map(x=>`<option value="${esc(x)}" ${String(x)===String(value)?"selected":""}>${esc(label(x))}</option>`).join("");
 function parse(type,text){try{return U().parse(type,text);}catch(_){return{value:String(text??""),unit:""};}}
 function quantity(type,text,key){const z=parse(type,text);return `<span class="aipp-quantity"><input data-orifice-quantity-value="${key}" data-quantity-type="${type}" value="${esc(z.value)}"><select data-orifice-quantity-unit="${key}" data-quantity-type="${type}">${options(U().units(type),z.unit)}</select></span>`;}
 function shell(title,description,content,s){return `<section class="aipp-orifice-section aipp-editor-surface"><header class="aipp-chamber-header"><div><span class="aipp-editor-kicker">ORIFICE CONFIGURATION</span><h3>${esc(title)}</h3><p>${esc(description)}</p></div></header>${content}${status(s)}</section>`;}
 function status(s){return `${s.errors.length?`<div class="aipp-inspector-errors" role="alert">${s.errors.map(esc).join("<br>")}</div>`:""}${s.impacts.length?`<div class="aipp-impact-warning">Apply will remove this orifice from invalid filter assignments in chamber(s): ${s.impacts.map(x=>x.chamber).join(", ")}.</div>`:""}<div class="aipp-inspector-actions"><button data-orifice-apply ${!s.dirty||s.errors.length?"disabled":""}>Apply</button><button data-orifice-revert class="secondary" ${!s.dirty?"disabled":""}>Revert</button><span class="aipp-inspector-state ${s.dirty?"modified":"clean"}">${s.dirty?"Modified":"Unmodified"}</span></div>`;}
 function renderProperties(s){const r=s.working,a=P2.application.aippDeckDocument.snapshot().native.aipp_calculation.assembly;const chamberOptions=(value)=>options([0,...(a.chambers||[]).map((c,i)=>i+1)],value,n=>n===0?"—":`${n}: ${a.chambers[n-1]?.label||`Chamber ${n}`}`);return shell("Orifice properties","Define connectivity, geometry, initial state, and flow restrictions.",`<div class="aipp-form-grid aipp-editor-grid"><label>From chamber<select data-orifice-field="from">${chamberOptions(r.from)}</select></label><label>To chamber<select data-orifice-field="to">${chamberOptions(r.to)}</select></label><label>Diameter${quantity("length",r.diameter,"diameter")}</label><label>Number of orifices<input type="number" min="1" step="1" data-orifice-field="num_orif" value="${esc(r.num_orif)}"></label><label>Initially open<select data-orifice-field="open">${options([true,false],r.open,x=>x?"Open at t = 0":"Closed at t = 0")}</select></label><label>One-way flow<select data-orifice-field="one_way">${options([true,false],r.one_way,x=>x?"From to To only":"Bidirectional")}</select></label><label>Viscous flow factor<input type="number" min="0" max="1.5" step="any" data-orifice-field="viscous_flow_factor" value="${esc(r.viscous_flow_factor)}"></label></div>`,s);}
 function renderOpening(s){const r=s.working,event=r.opens_at&&typeof r.opens_at==="object";return shell("Opening criterion","Choose a nonnegative pressure differential or a model event with time delay.",`<div class="aipp-form-grid aipp-editor-grid"><label>Opening mode<select data-orifice-opening-mode>${options(["pressure","event"],event?"event":"pressure",x=>x==="pressure"?"Pressure differential":"Triggering event")}</select></label>${event?`<label>Triggering event<select data-orifice-event>${options(E().events(),r.opens_at.triggering_event)}</select></label><label>Time delay${quantity("time",r.opens_at.time_delay,"opens_at.time_delay")}</label>`:`<label>Pressure threshold${quantity("pressure",r.opens_at,"opens_at")}</label>`}</div><p class="aipp-help">Pressure mode opens when P(from) - P(to) exceeds the threshold. An initially open orifice retains this criterion for round-trip fidelity.</p>`,s);}
 function table(b,d){const x=d[b+"_array"]||[],y=d.Cd_array||[],label=b==="time"?"Time":"Pressure",unit=d[b+"_units"]||U().units(b)[0],rows=x.map((v,i)=>`<tr><td><input type="number" step="any" data-orifice-cd-cell="x" data-index="${i}" value="${esc(v)}" aria-label="${label} row ${i+1}"></td><td><input type="number" min="0" max="1.5" step="any" data-orifice-cd-cell="cd" data-index="${i}" value="${esc(y[i])}" aria-label="Cd row ${i+1}"></td><td><button type="button" class="secondary" data-orifice-cd-remove="${i}" ${x.length<=1?"disabled":""}>Remove</button></td></tr>`).join("");return `<div class="aipp-form-grid aipp-editor-grid"><label>${label} units<select data-orifice-field="discharge_coefficient.${b}_units">${options(U().units(b),d[b+"_units"])}</select></label><label>Continuity<select data-orifice-field="discharge_coefficient.continuity">${options(["discrete","interpolate"],d.continuity,x=>x==="discrete"?"Discrete":"Interpolate")}</select></label></div><div class="aipp-cd-table-card aipp-tabular-editor"><div class="aipp-cd-table-head aipp-tabular-heading"><div><strong>${label} / Cd table</strong><small>Coordinates must increase strictly. Cd must be between 0 and 1.5.</small></div><div class="aipp-cd-table-tools aipp-m88-table-tools aipp-tabular-toolbar"><button type="button" class="secondary" data-orifice-cd-add>Add row</button><button type="button" class="secondary" data-orifice-cd-import>Import CSV</button><input type="file" data-orifice-cd-file accept=".csv,text/csv" hidden></div></div><div class="aipp-csv-error" data-orifice-cd-error role="alert" hidden></div><table class="aipp-m88-table aipp-cd-table aipp-tabular-table"><thead><tr><th>${label} (${esc(unit)})</th><th>Cd</th><th></th></tr></thead><tbody>${rows}</tbody></table><small class="aipp-cd-csv-help aipp-tabular-help">CSV row 1 must be exactly <code>${esc(unit)},Cd</code>. Numeric data begins on row 2 and replaces the table only after complete validation.</small></div>`;}
 function renderDischarge(s){const d=s.working.discharge_coefficient||{},b=d.basis||"constant";const body=`<div class="aipp-editor-grid aipp-editor-grid-single"><label>Basis<select data-orifice-field="discharge_coefficient.basis">${options(["constant","time","pressure"],b,x=>({constant:"Constant",time:"Time-dependent",pressure:"Pressure-dependent"})[x])}</select></label>${b==="constant"?`<label>Cd value<input type="number" min="0" max="1.5" step="any" data-orifice-field="discharge_coefficient.Cd_value" value="${esc(d.Cd_value)}"></label>`:table(b,d)}</div>`;return shell("Discharge coefficient","Configure a constant coefficient or a time/pressure lookup table.",body,s);}
 function render(s){if(s.selection?.kind!=="orifice")return;const prop=q("aippInspectorBody"),opening=q("aippOrificeOpeningPane"),discharge=q("aippOrificeDischargePane");if(prop)prop.innerHTML=renderProperties(s);if(opening)opening.innerHTML=renderOpening(s);if(discharge)discharge.innerHTML=renderDischarge(s);if(q("aippInspectorJson"))q("aippInspectorJson").textContent=JSON.stringify(s.working,null,2);bind();}
 function setField(path,raw){let v=raw;if(["from","to","num_orif"].includes(path))v=Number(raw);else if(["open","one_way"].includes(path))v=raw==="true";else if(["viscous_flow_factor","discharge_coefficient.Cd_value"].includes(path))v=Number(raw);E().set(path,v);}
 function quantityChange(el,isUnit){const key=isUnit?el.dataset.orificeQuantityUnit:el.dataset.orificeQuantityValue,type=el.dataset.quantityType,s=E().snapshot(),parts=key.split(".");let old=s.working;parts.forEach(k=>old=old?.[k]);const z=parse(type,old),valueEl=document.querySelector(`[data-orifice-quantity-value="${key}"]`),unitEl=document.querySelector(`[data-orifice-quantity-unit="${key}"]`);let value=Number(valueEl.value),unit=unitEl.value;if(isUnit&&z.unit&&z.unit!==unit&&Number.isFinite(z.value))value=U().convert(type,z.value,z.unit,unit);E().set(key,`${String(Number(value.toPrecision(12)))} ${unit}`);}
 function bind(){document.querySelectorAll("[data-orifice-field]").forEach(el=>el.onchange=()=>setField(el.dataset.orificeField,el.value));document.querySelectorAll("[data-orifice-quantity-value]").forEach(el=>el.onchange=()=>quantityChange(el,false));document.querySelectorAll("[data-orifice-quantity-unit]").forEach(el=>el.onchange=()=>quantityChange(el,true));document.querySelectorAll("[data-orifice-opening-mode]").forEach(el=>el.onchange=()=>E().replace("opens_at",el.value==="event"?{triggering_event:"SimStart",time_delay:"0 s"}:"0 Pa"));document.querySelectorAll("[data-orifice-event]").forEach(el=>el.onchange=()=>E().set("opens_at.triggering_event",el.value));document.querySelectorAll("[data-orifice-cd-cell]").forEach(el=>el.onchange=()=>E().setTableCell(el.dataset.index,el.dataset.orificeCdCell==="x"?"x":"cd",el.value));document.querySelectorAll("[data-orifice-cd-remove]").forEach(el=>el.onclick=()=>E().removeTableRow(el.dataset.orificeCdRemove));document.querySelectorAll("[data-orifice-cd-add]").forEach(el=>el.onclick=()=>E().addTableRow());document.querySelectorAll("[data-orifice-cd-import]").forEach(el=>el.onclick=()=>el.closest(".aipp-cd-table-card").querySelector("[data-orifice-cd-file]").click());document.querySelectorAll("[data-orifice-cd-file]").forEach(el=>el.onchange=()=>{const file=el.files&&el.files[0],box=el.closest(".aipp-cd-table-card").querySelector("[data-orifice-cd-error]");if(!file)return;const reader=new FileReader();reader.onload=()=>{try{E().importCsvText(reader.result);box.hidden=true;box.textContent="";}catch(err){box.textContent=err.message||String(err);box.hidden=false;}finally{el.value="";}};reader.onerror=()=>{box.textContent="The CSV file could not be read.";box.hidden=false;el.value="";};reader.readAsText(file);});document.querySelectorAll("[data-orifice-apply]").forEach(el=>el.onclick=()=>{try{E().apply();}catch(_){}});document.querySelectorAll("[data-orifice-revert]").forEach(el=>el.onclick=()=>E().revert());}
 function attach(){P2.application.aippTopologyCanvas.subscribeSelection(d=>{if(d?.selection?.kind==="orifice"){E().load(d);render(E().snapshot());}});E().subscribe(render);}
 P2.application.aippOrificeEditorView={render,attach};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",attach);else attach();
})();
