"use strict";
(function(){
 const A=P2.application,D=()=>A.aippDeckDocument,C=()=>A.aippPistons,copy=v=>v==null?v:JSON.parse(JSON.stringify(v));
 let selectedId="",original=null,working=null,dirty=false,errors=[],listeners=new Set(),csvPreviews={},selectedBodyForce=-1;
 const isObj=v=>v&&typeof v==="object"&&!Array.isArray(v), num=v=>Number(v), increasing=a=>Array.isArray(a)&&a.every((v,i)=>Number.isFinite(num(v))&&(!i||num(v)>num(a[i-1])));
 function chamberCount(){const d=D().snapshot().native;return d.aipp_calculation?.assembly?.chambers?.length||d.chambers?.length||0;}
 function validateLaw(law,name,y){if(!isObj(law)){errors.push(name+" must be an object.");return;}if(!["constant","displacement","time"].includes(law.basis))errors.push(name+" basis must be constant, displacement, or time.");if(law.basis!=="constant"&&!law.csv_file){const x=law.basis==="time"?law.time_array:law.displacement_array, a=law[y];if(!Array.isArray(x)||!Array.isArray(a)||x.length!==a.length||x.length<2)errors.push(name+" lookup arrays must have matching lengths of at least two.");else if(!increasing(x))errors.push(name+" independent values must increase strictly.");}if(name==="Mass law"&&law.basis!=="constant"&&law.continuity!=="interpolate")errors.push("Mass law continuity must be interpolate.");else if(law.continuity&&!['discrete','interpolate'].includes(law.continuity))errors.push(name+" continuity is invalid.");}
 function validate(){errors=[];if(!working)return errors;if(!isObj(working)){errors.push("Piston record must be an object.");return errors;}const n=chamberCount(),L=working.left_connection,R=working.right_connection;if(!isObj(L)||!isObj(R))errors.push("Left and right connections are required.");else{const li=num(L.chamber_idx),ri=num(R.chamber_idx);if(!Number.isInteger(li)||li<1||li>n)errors.push("Left chamber must reference an existing chamber.");if(!Number.isInteger(ri)||ri<1||ri>n)errors.push("Right chamber must reference an existing chamber.");if(li===ri)errors.push("Left and right chambers must be different.");if(!L.max_displacement)errors.push("Left maximum displacement is required.");if(!R.max_displacement)errors.push("Right maximum displacement is required.");validateLaw(L.area_law,"Left area law","area_array");validateLaw(R.area_law,"Right area law","area_array");}validateLaw(working.mass,"Mass law","mass_array");if(!working.travel_units)errors.push("Travel units are required.");if(!Array.isArray(working.travel_targets))errors.push("Travel targets must be an array.");else if(working.travel_targets.length&&!increasing(working.travel_targets))errors.push("Travel targets must be finite, unique, and increasing.");for(const k of ['left_damping_force','right_damping_force'])if(!isObj(working[k]))errors.push(k+" is required.");if(!Array.isArray(working.body_forces))errors.push("Body forces must be an array.");else working.body_forces.forEach((f,i)=>{const p="Body force "+(i+1)+": ";if(!isObj(f))return errors.push(p+"record must be an object.");if(!["constant","displacement","time"].includes(f.type))return errors.push(p+"type is invalid.");const d=f.body_force_details;if(!isObj(d))return errors.push(p+"details are required.");if(f.type==="constant"){let q=null;try{q=A.aippQuaffUnits.parse("force",d.magnitude||"");}catch(_){}if(!q)errors.push(p+"magnitude must be a QUAFF-safe force quantity.");return;}if(!["discrete","interpolate"].includes(d.continuity))errors.push(p+"continuity is invalid.");if(d.csv_file!==undefined){if(!String(d.csv_file).trim())errors.push(p+"CSV file is required.");return;}const xk=f.type==="time"?"time_array":"displacement_array",uk=f.type==="time"?"time_units":"displacement_units",ut=f.type==="time"?"time":"length",x=d[xk],y=d.force_array;if(!A.aippQuaffUnits.isAllowed(ut,d[uk]))errors.push(p+uk+" is invalid.");if(!A.aippQuaffUnits.isAllowed("force",d.force_units))errors.push(p+"force_units is invalid.");if(!Array.isArray(x)||!Array.isArray(y)||x.length!==y.length||x.length<2)errors.push(p+"lookup arrays must have matching lengths of at least two.");else{if(!increasing(x))errors.push(p+f.type+" values must increase strictly.");if(!y.every(v=>Number.isFinite(Number(v))))errors.push(p+"force values must be finite.");}});return errors;}
 function snapshot(){const list=C().snapshot();return{selectedId,selectedBodyForce,csvPreviews:copy(csvPreviews),items:list.items.map(x=>({id:x.id,index:x.index,name:x.name,native:copy(x.native)})),original:copy(original),working:copy(working),dirty,errors:errors.slice(),references:selectedId?C().dependencies(selectedId):[],chambers:(D().snapshot().native.aipp_calculation?.assembly?.chambers||D().snapshot().native.chambers||[]).map((x,i)=>({index:i+1,label:x.label||x.name||('Chamber '+(i+1))}))};}
 function notify(reason){const s=snapshot();listeners.forEach(fn=>{try{fn(s,reason);}catch(_){}});return s;}function reset(x){selectedId=x.id;C().select(x.id);original=copy(x.native);if(!Object.prototype.hasOwnProperty.call(original,"label"))original.label="";if(!Array.isArray(original.body_forces))original.body_forces=[];working=copy(original);csvPreviews={};selectedBodyForce=working.body_forces.length?0:-1;dirty=false;validate();return notify("load");}
 function load(selection){const i=Number(selection?.selection?.nativeIndex||selection?.nativeIndex||selection?.selection?.index||selection?.index),x=C().snapshot().items[i-1];if(!x)throw new P2.ProtocolError("AIPP_UNKNOWN_PISTON",String(i));return reset(x);}function loadId(id){const x=C().snapshot().items.find(v=>v.id===id);if(!x)throw new P2.ProtocolError("AIPP_UNKNOWN_PISTON",String(id));return reset(x);}
 function set(path,value){if(!working)throw new P2.ProtocolError("AIPP_NO_PISTON_SELECTED","No piston selected.");const p=String(path).split('.');let o=working;for(let i=0;i<p.length-1;i++)o=o[p[i]]||(o[p[i]]={});o[p[p.length-1]]=value;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("set");}
 function setJson(path,text){let v;try{v=JSON.parse(text);}catch(e){throw new P2.ProtocolError("AIPP_INVALID_PISTON_JSON",e.message);}return set(path,v);}

 function quantity(path,type,value,unit){const U=A.aippQuaffUnits;if(!U||!U.isAllowed(type,unit))throw new P2.ProtocolError("AIPP_INCOMPATIBLE_PISTON_UNIT",type+":"+unit);return set(path,String(value)+" "+unit);}
 function convertQuantity(path,type,toUnit){const p=String(path).split('.');let o=working;for(const k of p)o=o?.[k];const m=/^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s+(.+?)\s*$/.exec(String(o||""));if(!m)throw new P2.ProtocolError("AIPP_INVALID_PISTON_QUANTITY",path);const v=A.aippQuaffUnits.convert(type,Number(m[1]),m[2],toUnit);return set(path,A.aippQuaffUnits.format(v)+" "+toUnit);}
 function lawBasis(path,basis,dependent){const law={basis};if(basis==="constant"){law[dependent.constantKey]=dependent.defaultValue+" "+dependent.defaultUnit;}else{const x=basis==="time"?"time":"displacement";law[x+"_units"]=x==="time"?"ms":"mm";law[x+"_array"]=[0,1];law[dependent.unitsKey]=dependent.defaultUnit;law[dependent.arrayKey]=[dependent.defaultValue,dependent.defaultValue];law.continuity="interpolate";}if(path==="mass"&&basis!=="constant")law.continuity="interpolate";return set(path,law);}
 function lawSource(path,source,dependent){const p=String(path).split('.');let law=working;for(const k of p)law=law?.[k];law=copy(law||{});if(source==="csv"){const keep={basis:law.basis,csv_file:law.csv_file||"",continuity:path==="mass"?"interpolate":(law.continuity||"interpolate")};return set(path,keep);}return lawBasis(path,law.basis||"displacement",dependent);}
 function tableCell(path,key,index,value){const p=String(path).split('.');let law=working;for(const k of p)law=law?.[k];law=copy(law);law[key]=Array.isArray(law[key])?law[key]:[];law[key][Number(index)]=Number(value);return set(path,law);}
 function tableAdd(path,xkey,ykey){const p=String(path).split('.');let law=working;for(const k of p)law=law?.[k];law=copy(law);law[xkey]=Array.isArray(law[xkey])?law[xkey]:[];law[ykey]=Array.isArray(law[ykey])?law[ykey]:[];law[xkey].push(law[xkey].length?Number(law[xkey].at(-1))+1:0);law[ykey].push(law[ykey].length?law[ykey].at(-1):0);return set(path,law);}
 function tableRemove(path,xkey,ykey,index){const p=String(path).split('.');let law=working;for(const k of p)law=law?.[k];law=copy(law);law[xkey].splice(index,1);law[ykey].splice(index,1);return set(path,law);}
 function convertArray(path,key,type,fromUnit,toUnit,unitKey){const p=String(path).split('.');let law=working;for(const k of p)law=law?.[k];law=copy(law);law[key]=(law[key]||[]).map(v=>A.aippQuaffUnits.convert(type,v,fromUnit,toUnit));law[unitKey]=toUnit;return set(path,law);}

 function parseCsv(text){const rows=String(text||"").replace(/^\uFEFF/,"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>line.split(/[,;\t]/).map(x=>x.trim()));if(rows.length<2)throw new P2.ProtocolError("AIPP_PISTON_CSV_TOO_SHORT","CSV requires a header and at least one data row.");const first=rows[0],header=first.some(x=>!Number.isFinite(Number(x))),data=(header?rows.slice(1):rows);const values=data.map((r,i)=>{if(r.length<2||!Number.isFinite(Number(r[0]))||!Number.isFinite(Number(r[1])))throw new P2.ProtocolError("AIPP_INVALID_PISTON_CSV","Invalid numeric row "+(i+1));return[Number(r[0]),Number(r[1])];});if(!increasing(values.map(r=>r[0])))throw new P2.ProtocolError("AIPP_INVALID_PISTON_CSV","Independent values must increase strictly.");return{headers:header?first.slice(0,2):["Independent","Value"],values};}
 function importCsv(path,text,fileName,dependent){const parsed=parseCsv(text),parts=String(path).split('.');let law=working;for(const k of parts)law=law?.[k];if(!law||law.basis==="constant")throw new P2.ProtocolError("AIPP_INVALID_PISTON_CSV_BASIS",path);csvPreviews[path]={fileName:String(fileName||law.csv_file||"data.csv"),headers:parsed.headers,values:parsed.values,dependent:copy(dependent)};law=copy(law);law.csv_file=String(fileName||law.csv_file||"data.csv");set(path,law);return notify("csv-preview");}
 function editCsvLocally(path){const preview=csvPreviews[path];if(!preview)throw new P2.ProtocolError("AIPP_NO_PISTON_CSV_PREVIEW",path);const parts=String(path).split('.');let old=working;for(const k of parts)old=old?.[k];const d=preview.dependent,x=old.basis==="time"?"time":"displacement",law={basis:old.basis,continuity:old.continuity||"interpolate"};law[x+"_units"]=x==="time"?"ms":"mm";law[x+"_array"]=preview.values.map(r=>r[0]);law[d.unitsKey]=d.defaultUnit;law[d.arrayKey]=preview.values.map(r=>r[1]);delete csvPreviews[path];return set(path,law);}
 function travelCell(index,value){const a=copy(working.travel_targets||[]);a[Number(index)]=Number(value);return set("travel_targets",a);}
 function travelAdd(){const a=copy(working.travel_targets||[]);a.push(a.length?Number(a.at(-1))+1:0);return set("travel_targets",a);}
 function travelRemove(index){const a=copy(working.travel_targets||[]);a.splice(Number(index),1);return set("travel_targets",a);}
 function convertTravelUnits(toUnit){const from=working.travel_units||"mm",a=(working.travel_targets||[]).map(v=>A.aippQuaffUnits.convert("length",v,from,toUnit));working.travel_units=toUnit;working.travel_targets=a;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("travel-unit");}

 function bodyForceSelect(index){index=Number(index);if(!Array.isArray(working?.body_forces)||index<0||index>=working.body_forces.length)throw new P2.ProtocolError("AIPP_UNKNOWN_BODY_FORCE",String(index));selectedBodyForce=index;return notify("body-force-select");}
 function bodyForceAdd(){if(!Array.isArray(working.body_forces))working.body_forces=[];working.body_forces.push({type:"constant",body_force_details:{magnitude:"0 N"}});selectedBodyForce=working.body_forces.length-1;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-add");}
 function bodyForceRemove(index=selectedBodyForce){index=Number(index);if(index<0||index>=working.body_forces.length)throw new P2.ProtocolError("AIPP_UNKNOWN_BODY_FORCE",String(index));working.body_forces.splice(index,1);selectedBodyForce=working.body_forces.length?Math.min(index,working.body_forces.length-1):-1;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-remove");}
 function bodyForceSetMagnitude(value,unit){if(selectedBodyForce<0)throw new P2.ProtocolError("AIPP_NO_BODY_FORCE_SELECTED","No body force selected.");if(!A.aippQuaffUnits.isAllowed("force",unit))throw new P2.ProtocolError("AIPP_INCOMPATIBLE_PISTON_UNIT",unit);working.body_forces[selectedBodyForce].body_force_details.magnitude=String(value)+" "+unit;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-magnitude");}
 function bodyForceConvertUnit(toUnit){if(selectedBodyForce<0)throw new P2.ProtocolError("AIPP_NO_BODY_FORCE_SELECTED","No body force selected.");const f=working.body_forces[selectedBodyForce],q=A.aippQuaffUnits.parse("force",f.body_force_details.magnitude);const v=A.aippQuaffUnits.convert("force",q.value,q.unit,toUnit),formatted=Number(v.toPrecision(12)).toString();f.body_force_details.magnitude=formatted+" "+toUnit;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-unit");}

 function currentBodyForce(){if(selectedBodyForce<0||!working?.body_forces?.[selectedBodyForce])throw new P2.ProtocolError("AIPP_NO_BODY_FORCE_SELECTED","No body force selected.");return working.body_forces[selectedBodyForce];}
 function bodyForceType(type){if(!["constant","displacement","time"].includes(type))throw new P2.ProtocolError("AIPP_INVALID_BODY_FORCE_TYPE",type);const old=currentBodyForce(),top={...copy(old),type};if(type==="constant")top.body_force_details={magnitude:"0 N"};else{const x=type==="time"?"time":"displacement";top.body_force_details={[x+"_units"]:type==="time"?"ms":"mm",force_units:"N",[x+"_array"]:[0,1],force_array:[0,0],continuity:"interpolate"};}working.body_forces[selectedBodyForce]=top;delete csvPreviews["body_forces."+selectedBodyForce];dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-type");}
 function bodyForceSource(source){const f=currentBodyForce();if(f.type==="constant")throw new P2.ProtocolError("AIPP_INVALID_BODY_FORCE_SOURCE",source);const key="body_forces."+selectedBodyForce;if(source==="csv")f.body_force_details={csv_file:"",continuity:f.body_force_details.continuity||"interpolate"};else{const x=f.type==="time"?"time":"displacement";f.body_force_details={[x+"_units"]:f.type==="time"?"ms":"mm",force_units:"N",[x+"_array"]:[0,1],force_array:[0,0],continuity:f.body_force_details.continuity||"interpolate"};delete csvPreviews[key];}dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-source");}
 function bodyForceSet(path,value){const f=currentBodyForce(),parts=String(path).split("."),d=f.body_force_details;let o=d;for(let i=0;i<parts.length-1;i++)o=o[parts[i]]||(o[parts[i]]={});o[parts.at(-1)]=value;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-set");}
 function bodyForceCell(key,index,value){const d=currentBodyForce().body_force_details;d[key]=Array.isArray(d[key])?d[key]:[];d[key][Number(index)]=Number(value);dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-cell");}
 function bodyForceAddRow(){const f=currentBodyForce(),xk=f.type==="time"?"time_array":"displacement_array",d=f.body_force_details;d[xk]=d[xk]||[];d.force_array=d.force_array||[];d[xk].push(d[xk].length?Number(d[xk].at(-1))+1:0);d.force_array.push(d.force_array.length?d.force_array.at(-1):0);dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-row-add");}
 function bodyForceRemoveRow(index){const f=currentBodyForce(),xk=f.type==="time"?"time_array":"displacement_array",d=f.body_force_details;d[xk].splice(index,1);d.force_array.splice(index,1);dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-row-remove");}
 function bodyForceConvertColumn(key,type,toUnit,unitKey){const d=currentBodyForce().body_force_details,from=d[unitKey];d[key]=(d[key]||[]).map(v=>A.aippQuaffUnits.convert(type,v,from,toUnit));d[unitKey]=toUnit;dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-unit");}
 function parseBodyForceCsv(text,type){const rows=String(text||"").replace(/^\uFEFF/,"").split(/\r\n|\n|\r/).map(x=>x.trim()).filter(Boolean).map(x=>x.split(/[,;\t]/).map(y=>y.trim()));if(rows.length<2)throw new P2.ProtocolError("AIPP_BODY_FORCE_CSV_TOO_SHORT","CSV requires units and data rows.");const units=rows[0].slice(0,2),ut=type==="time"?"time":"length";if(!A.aippQuaffUnits.isAllowed(ut,units[0])||!A.aippQuaffUnits.isAllowed("force",units[1]))throw new P2.ProtocolError("AIPP_BODY_FORCE_CSV_UNITS","CSV units are incompatible.");const values=rows.slice(1).map((r,i)=>{if(r.length<2||!Number.isFinite(Number(r[0]))||!Number.isFinite(Number(r[1])))throw new P2.ProtocolError("AIPP_INVALID_BODY_FORCE_CSV","Invalid row "+(i+2));return[Number(r[0]),Number(r[1])];});if(!increasing(values.map(r=>r[0])))throw new P2.ProtocolError("AIPP_INVALID_BODY_FORCE_CSV","Independent values must increase strictly.");return{units,values};}
 function importBodyForceCsv(text,fileName){const f=currentBodyForce(),parsed=parseBodyForceCsv(text,f.type),key="body_forces."+selectedBodyForce;f.body_force_details.csv_file=String(fileName||"body_force.csv");csvPreviews[key]={fileName:f.body_force_details.csv_file,headers:parsed.units,values:parsed.values};dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-csv");}
 function bodyForceEditLocally(){const f=currentBodyForce(),key="body_forces."+selectedBodyForce,p=csvPreviews[key];if(!p)throw new P2.ProtocolError("AIPP_NO_BODY_FORCE_CSV_PREVIEW",key);const x=f.type==="time"?"time":"displacement";f.body_force_details={[x+"_units"]:p.headers[0],force_units:p.headers[1],[x+"_array"]:p.values.map(r=>r[0]),force_array:p.values.map(r=>r[1]),continuity:f.body_force_details.continuity||"interpolate"};delete csvPreviews[key];dirty=JSON.stringify(working)!==JSON.stringify(original);validate();return notify("body-force-local");}
 function apply(){validate();if(errors.length)throw new P2.ProtocolError("AIPP_PISTON_VALIDATION_FAILED",errors.join(" "));if(!dirty)return snapshot();const idx=C().snapshot().items.find(x=>x.id===selectedId).index;D().mutate("piston-editor-apply",d=>{const a=d.native.aipp_calculation?.assembly?.pistons;if(!Array.isArray(a)||!a[idx-1])throw new Error("Piston path unavailable.");a[idx-1]=copy(working);});const x=C().snapshot().items[idx-1];selectedId=x.id;C().select(selectedId);original=copy(x.native);working=copy(x.native);dirty=false;validate();return notify("apply");}
 function revert(){working=copy(original);dirty=false;validate();return notify("revert");}function create(){const id=C().create();return loadId(id);}function duplicate(){const id=C().duplicate(selectedId);return loadId(id);}function move(delta){C().move(selectedId,delta);return loadId(selectedId);}function remove(){C().remove(selectedId);const s=C().snapshot();if(s.selectedId)return loadId(s.selectedId);selectedId="";original=working=null;dirty=false;errors=[];return notify("remove");}
 function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}A.aippPistonEditor={load,loadId,set,setJson,quantity,convertQuantity,lawBasis,lawSource,tableCell,tableAdd,tableRemove,convertArray,parseCsv,importCsv,editCsvLocally,travelCell,travelAdd,travelRemove,convertTravelUnits,bodyForceSelect,bodyForceAdd,bodyForceRemove,bodyForceSetMagnitude,bodyForceConvertUnit,bodyForceType,bodyForceSource,bodyForceSet,bodyForceCell,bodyForceAddRow,bodyForceRemoveRow,bodyForceConvertColumn,parseBodyForceCsv,importBodyForceCsv,bodyForceEditLocally,apply,revert,create,duplicate,move,remove,validate,snapshot,subscribe};
})();