"use strict";
(function(){
 const A=P2.application,D=()=>A.aippDeckDocument,q=id=>document.getElementById(id),copy=v=>JSON.parse(JSON.stringify(v));
 let text="",dirty=false,query="",host=null,folded={};
 const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 function pretty(value,spaces=2){return JSON.stringify(value,null,spaces)+"\n";}
 function tokenized(value){
  let out=esc(value);
  out=out.replace(/(&quot;(?:\\.|[^&]|&(?!quot;))*?&quot;)(\s*:)/g,'<span class="aipp-json-key">$1</span>$2');
  out=out.replace(/(&quot;(?:\\.|[^&]|&(?!quot;))*?&quot;)/g,'<span class="aipp-json-string">$1</span>');
  out=out.replace(/\b(-?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)\b/g,'<span class="aipp-json-number">$1</span>');
  out=out.replace(/\b(true|false)\b/g,'<span class="aipp-json-bool">$1</span>');
  out=out.replace(/\b(null)\b/g,'<span class="aipp-json-null">$1</span>');
  if(query){const safe=esc(query).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");try{out=out.replace(new RegExp(safe,"ig"),'<mark class="aipp-json-hit">$&</mark>');}catch(_){} }
  return out||" ";
 }
 function status(message,kind=""){const s=q("aippRawJsonStatus");if(s){s.textContent=message;s.className="aipp-raw-status "+kind;}}
 function foldRanges(lines){const stack=[],ranges={};for(let i=0;i<lines.length;i++){let quote=false,escape=false;for(const char of lines[i]){if(escape){escape=false;continue;}if(char==="\\"&&quote){escape=true;continue;}if(char==='"'){quote=!quote;continue;}if(quote)continue;if(char==="{"||char==="[")stack.push({char,line:i});else if((char==="}"&&stack.at(-1)?.char==="{")||(char==="]"&&stack.at(-1)?.char==="[")){const open=stack.pop();if(i>open.line+1)ranges[open.line]=i;}}}return ranges;}
 function renderHighlight(){const ed=q("aippRawJsonEditor"),pre=q("aippRawJsonHighlight"),gutter=q("aippRawJsonGutter");if(!ed||!pre||!gutter)return;const lines=ed.value.split(/\r?\n/),ranges=foldRanges(lines),code=[],marks=[];for(let i=0;i<lines.length;i++){const end=ranges[i];marks.push(`<div class="aipp-raw-gutter-row"><button type="button" class="aipp-raw-fold" data-raw-fold="${i}" ${end===undefined?"disabled":""}>${end===undefined?"":(folded[i]?"▶":"▼")}</button></div>`);if(folded[i]&&end!==undefined){code.push(`<div class="aipp-raw-code-row">${tokenized(lines[i])}<span class="aipp-raw-fold-placeholder"> ... ${end-i-1} lines ...</span></div>`);i=end;continue;}code.push(`<div class="aipp-raw-code-row">${tokenized(lines[i])||" "}</div>`);}pre.innerHTML=code.join("");gutter.innerHTML=marks.join("");gutter.scrollTop=ed.scrollTop;}
 function syncHighlight(){const ed=q("aippRawJsonEditor"),pre=q("aippRawJsonHighlight");if(!ed||!pre)return;renderHighlight();pre.scrollTop=ed.scrollTop;pre.scrollLeft=ed.scrollLeft;}
 function pathOffsets(source){let i=0;const offsets={};const skip=()=>{while(/\s/.test(source[i]||""))i++;};const string=()=>{const start=i++;while(i<source.length){if(source[i]==="\\")i+=2;else if(source[i++]==='"')break;}return JSON.parse(source.slice(start,i));};const value=path=>{skip();const start=i;offsets[path]=start;if(source[i]==="{"){i++;skip();while(source[i]!=="}"&&i<source.length){const key=string();skip();i++;value(path?`${path}.${key}`:key);skip();if(source[i]===","){i++;skip();}}i++;return;}if(source[i]==="["){i++;skip();let index=0;while(source[i]!=="]"&&i<source.length){value(`${path}[${index++}]`);skip();if(source[i]===","){i++;skip();}}i++;return;}if(source[i]==='"'){string();return;}while(i<source.length&&!/[\s,}\]]/.test(source[i]))i++;};try{value("");}catch(_){return{};}return offsets;}
 function scrollToSelection(detail){const ed=q("aippRawJsonEditor");if(!ed||!detail?.selection?.path)return;const offsets=pathOffsets(ed.value),offset=offsets[detail.selection.path];if(offset===undefined)return;const line=ed.value.slice(0,offset).split(/\r?\n/).length-1,lines=ed.value.split(/\r?\n/),ranges=foldRanges(lines);Object.keys(ranges).forEach(start=>{const n=Number(start);if(n<line&&ranges[n]>=line)delete folded[start];});syncHighlight();const lineHeight=parseFloat(getComputedStyle(ed).lineHeight)||18;ed.scrollTop=Math.max(0,line*lineHeight-ed.clientHeight/2);const hi=q("aippRawJsonHighlight"),g=q("aippRawJsonGutter");if(hi)hi.scrollTop=ed.scrollTop;if(g)g.scrollTop=ed.scrollTop;status(`Showing ${detail.selection.kind||"entity"} at line ${line+1}.`,"success");}
 function setText(value,markDirty=false){text=String(value??"");dirty=markDirty;folded={};const ed=q("aippRawJsonEditor");if(ed)ed.value=text;syncHighlight();status(markDirty?"Unapplied RAW JSON changes":`${text.split(/\r?\n/).length} lines`);}
 function toolbar(){return `<div class="aipp-raw-toolbar"><label class="aipp-raw-search"><span>Search RAW JSON</span><input id="aippRawJsonSearch" type="search" placeholder="find in RAW JSON..." autocomplete="off"></label><button type="button" data-raw-action="apply">Apply JSON</button><button type="button" class="secondary" data-raw-action="undo">Undo</button><button type="button" class="secondary" data-raw-action="expand">Expand All</button><button type="button" class="secondary" data-raw-action="collapse">Collapse All</button><button type="button" class="secondary" data-raw-action="format">Format</button><span id="aippRawJsonStatus" class="aipp-raw-status"></span></div>`;}
 function view(){return `${toolbar()}<div class="aipp-raw-editor-shell"><div id="aippRawJsonGutter" aria-hidden="true"></div><pre id="aippRawJsonHighlight" aria-hidden="true"></pre><textarea id="aippRawJsonEditor" spellcheck="false" wrap="off" aria-label="RAW JSON editor"></textarea></div>`;}
 function apply(){const ed=q("aippRawJsonEditor");if(!ed)return false;const source=ed.value;let parsed;try{parsed=JSON.parse(source);}catch(e){status(`Invalid JSON: ${e.message}`,"error");return false;}try{A.aippNativeDeckImporter.validate(parsed);A.aippTopologyGraphAdapter.build(parsed);D().replace(parsed,{reason:"raw-json-apply"});setText(D().serialize());status("JSON applied; topology validated.","success");return true;}catch(e){status(e?.message||"JSON failed AIPP or topology validation.","error");return false;}}
 function format(spaces=2){const ed=q("aippRawJsonEditor");if(!ed)return;try{setText(pretty(JSON.parse(ed.value),spaces),true);status("JSON formatted; apply to save changes.","warning");}catch(e){status(`Cannot format invalid JSON: ${e.message}`,"error");}}
 function undo(){setText(D().serialize());status("Reverted to master JSON.","success");}
 function action(name){const ed=q("aippRawJsonEditor");if(!ed)return;if(name==="apply")apply();else if(name==="undo")undo();else if(name==="format")format(2);else if(name==="expand"){folded={};syncHighlight();status("All JSON sections expanded.","success");}else if(name==="collapse"){try{if(!foldRanges(ed.value.split(/\r?\n/))[0])format(2);const lines=ed.value.split(/\r?\n/),ranges=foldRanges(lines);folded={};Object.keys(ranges).forEach(i=>{if(Number(i)>0)folded[i]=true;});syncHighlight();status("JSON sections collapsed; apply to save changes.","warning");}catch(e){status(`Cannot collapse invalid JSON: ${e.message}`,"error");}}}
 function open(target){host=target;if(!target)return;target.className="aipp-raw-view";target.hidden=false;target.innerHTML=view();setText(dirty?text:D().serialize(),dirty);const ed=q("aippRawJsonEditor"),hi=q("aippRawJsonHighlight"),gutter=q("aippRawJsonGutter"),search=q("aippRawJsonSearch");ed.addEventListener("input",()=>{text=ed.value;dirty=true;folded={};syncHighlight();status("Unapplied RAW JSON changes","warning");});ed.addEventListener("scroll",()=>{hi.scrollTop=ed.scrollTop;hi.scrollLeft=ed.scrollLeft;gutter.scrollTop=ed.scrollTop;});target.addEventListener("click",e=>{const fold=e.target.closest("[data-raw-fold]");if(fold&&!fold.disabled){const i=fold.dataset.rawFold;folded[i]=!folded[i];syncHighlight();return;}const button=e.target.closest("[data-raw-action]");if(button)action(button.dataset.rawAction);});search.addEventListener("input",()=>{query=search.value;syncHighlight();});scrollToSelection(A.aippTopologyNavigation?.current?.());}
 function close(){host=null;}
 function onDeck(s){if(!dirty&&host&&q("aippRawJsonEditor"))setText(JSON.stringify(s.native,null,2)+"\n");}
 function bind(){D().subscribe(onDeck);document.addEventListener("aipp:topology-selection",event=>scrollToSelection(event.detail));}
 A.aippRawJsonEditorView={open,close,apply,undo,format};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
