"use strict";
(function(){
 const A=P2.application,D=()=>A.aippDeckDocument,q=id=>document.getElementById(id);
 const base="http:"+"//127.0.0.1:8765";let runId="",sequence=0,timer=0,startedAt=0,events=[],bound=false,currentState="IDLE";
 function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
 function formatTime(s){return Number.isFinite(s)?`${s.toFixed(1)} s`:"-";}
 function status(text,kind=""){const el=q("aippRuntimeStatus");if(el){el.textContent=text;el.className=`aipp-runtime-status ${kind}`;}}
 function locations(){const snapshot=D().snapshot(),input=snapshot.document?.path||"",field=q("aippRuntimeInputPath"),output=q("aippRuntimeOutputPath"),custom=q("aippRuntimeCustomOutput");if(field)field.value=input||"Not saved";if(output&&!custom?.checked){const name=(snapshot.document?.name||"input").replace(/\.json$/i,"");output.value=input?input.replace(/[^\\/]+$/,"" )+name+"_runtime_output.json":"Save the input deck first";}}
 function render(){const log=q("aippRuntimeConsole"),state=q("aippRuntimeRunState"),summary=q("aippRuntimeStateSummary"),elapsed=q("aippRuntimeElapsed"),exit=q("aippRuntimeExit");if(log){log.textContent=events.map(e=>`[${e.stream}] ${e.text}`).join("");if(q("aippRuntimeAutoScroll")?.checked)log.scrollTop=log.scrollHeight;}if(state)state.textContent=currentState;if(summary)summary.textContent=currentState;if(elapsed)elapsed.textContent=startedAt?formatTime((Date.now()-startedAt)/1000):"-";if(exit&&currentState==="IDLE")exit.textContent="-";}
 async function request(path,options){const response=await fetch(base+path,{...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});const value=await response.json();if(!response.ok)throw new Error(value.error||`Bridge request failed (${response.status})`);return value;}
 async function poll(){if(!runId)return;try{const packet=await request(`/runs/${encodeURIComponent(runId)}/events?since=${sequence}`);packet.events.forEach(e=>{events.push(e);sequence=e.sequence;});const current=await request(`/runs/${encodeURIComponent(runId)}`);currentState=current.state;const exit=q("aippRuntimeExit");if(exit)exit.textContent=current.exit_code??"-";if(current.state==="COMPLETED"||current.state==="FAILED"||current.state==="CANCELLED"){const list=await request(`/runs/${encodeURIComponent(runId)}/artifacts`);const art=q("aippRuntimeArtifacts");if(art)art.innerHTML=list.artifacts.map(x=>`<li>${esc(x.path)} <small>${x.bytes} bytes</small></li>`).join("");const output=q("aippRuntimeOutputPath"),sourcePath=D().snapshot().document?.path||"";if(output&&sourcePath&&current.output_file)output.value=sourcePath.replace(/[^\\/]+$/,"" )+current.output_file;clearInterval(timer);timer=0;q("aippRuntimeRun").disabled=false;q("aippRuntimeCancel").disabled=true;status(`Run ${current.state.toLowerCase()}`,current.state==="COMPLETED"?"success":"error");}render();}catch(error){status(error.message,"error");}}
 async function run(){if(runId&&timer){status("A run is already active.","warning");return;}try{const report=Number(q("aippRuntimeReport")?.value||1),snapshot=D().snapshot(),sourcePath=snapshot.document?.path||"",custom=q("aippRuntimeCustomOutput"),outputPath=custom?.checked?q("aippRuntimeOutputPath")?.value||"":null;if(!sourcePath)throw new Error("Save the input deck before running so its directory can be used for the container bind.");const result=await request("/runs",{method:"POST",body:JSON.stringify({deck:snapshot.native,sourcePath,outputPath,reportLevel:report})});runId=result.run_id;sequence=0;events=[];startedAt=Date.now();currentState="QUEUED";q("aippRuntimeArtifacts").innerHTML="";q("aippRuntimeRun").disabled=true;q("aippRuntimeCancel").disabled=false;status(`Run ${runId} started` ,"success");render();timer=window.setInterval(poll,250);await poll();}catch(error){status(error.message,"error");}}
 async function cancel(){if(!runId)return;try{await request(`/runs/${encodeURIComponent(runId)}/cancel`,{method:"POST",body:"{}"});status("Cancellation requested","warning");await poll();}catch(error){status(error.message,"error");}}
 function clearConsole(){events=[];render();status("Console cleared; persisted run log is unchanged.","success");}
 async function copyConsole(){try{await navigator.clipboard.writeText(events.map(e=>e.text).join(""));status("Console copied.","success");}catch(error){status("Clipboard access is unavailable.","error");}}
 async function preflight(){try{const health=await request("/health");if(health.version!=="rt9")throw new Error("Runtime Bridge is outdated; restart the bridge from Scilab.");status(`${health.service} ready`,"success");}catch(error){status(error.message==="Runtime Bridge is outdated; restart the bridge from Scilab."?error.message:"Runtime Bridge unavailable","warning");}}
 function bind(){if(bound)return;bound=true;q("aippRuntimeRun")?.addEventListener("click",run);q("aippRuntimeCancel")?.addEventListener("click",cancel);q("aippRuntimeClear")?.addEventListener("click",clearConsole);q("aippRuntimeCopy")?.addEventListener("click",copyConsole);q("aippRuntimeAutoScroll")?.addEventListener("change",render);q("aippRuntimeCustomOutput")?.addEventListener("change",()=>{locations();const output=q("aippRuntimeOutputPath");if(output)output.readOnly=!q("aippRuntimeCustomOutput").checked;});A.aippDeckDocument.subscribe(locations);preflight();locations();render();}
 A.aippRuntimeView={bind,run,cancel,clearConsole};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
