"use strict";
(function(){
 const A=P2.application,D=()=>A.aippDeckDocument,q=id=>document.getElementById(id),base="http:"+"//127.0.0.1:8765";
 const actions={full:{level:1,label:"full"},customer:{level:2,label:"customer"},match:{level:3,label:"match"},csv:{level:4,label:"CSV"}};
 let bound=false,timer=0,runId="",sequence=0;
 function esc(v){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));}
 function source(){return D().snapshot().document?.path||"";}
 async function request(path,options){const response=await fetch(base+path,{...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});const value=await response.json();if(!response.ok)throw new Error(value.error||`Bridge request failed (${response.status})`);return value;}
 function setStatus(text,kind=""){const el=q("aippOutputsStatus");if(el){el.textContent=text;el.className=`aipp-output-status ${kind}`;}}
 function renderReports(value){const list=q("aippOutputsList"),reports=value?.reports||[];if(!list)return;list.innerHTML=reports.length?reports.map(report=>`<li><button type="button" data-aipp-report-path="${esc(report.path)}">${esc(report.path)}</button><small>${report.kind.toUpperCase()} · ${report.bytes} bytes</small></li>`).join(""):"<li class=\"aipp-output-empty\">No HTML, XHTML, or CSV reports found.</li>";list.querySelectorAll("[data-aipp-report-path]").forEach(button=>button.addEventListener("click",()=>view(button.dataset.aippReportPath)));}
 async function refresh(){const path=source();if(!path){renderReports(null);setStatus("Save the input deck to inspect reports.","warning");return;}try{renderReports(await request(`/reports?sourcePath=${encodeURIComponent(path)}`));setStatus("Reports scanned","success");}catch(error){setStatus(error.message,"error");}}
 async function view(path){try{const response=await fetch(`${base}/report-content?sourcePath=${encodeURIComponent(source())}&path=${encodeURIComponent(path)}`);if(!response.ok)throw new Error("Report could not be opened");const frame=q("aippOutputsFrame"),empty=q("aippOutputsViewerEmpty"),download=q("aippOutputsDownload"),type=response.headers.get("Content-Type")||"",blob=await response.blob(),url=URL.createObjectURL(blob);if(frame){frame.src=url;frame.hidden=false;}if(download){download.href=url;download.download=path.split(/[\\/]/).pop();download.hidden=false;}if(empty)empty.hidden=true;setStatus(`Viewing ${path}`,"success");}catch(error){setStatus(error.message,"error");}}
 function setGenerateDisabled(disabled){Object.keys(actions).forEach(key=>{const button=q(`aippOutputs${key[0].toUpperCase()+key.slice(1)}`);if(button)button.disabled=disabled||button.dataset.unavailable==="true";});}
 async function generate(kind){const path=source(),action=actions[kind];if(!path){setStatus("Save the input deck before generating reports.","warning");return;}try{const snapshot=D().snapshot(),result=await request("/runs",{method:"POST",body:JSON.stringify({deck:snapshot.native,sourcePath:path,reportLevel:action.level})});runId=result.run_id;sequence=0;setGenerateDisabled(true);setStatus(`Generating ${action.label} report...`);timer=window.setInterval(poll,300);await poll();}catch(error){setGenerateDisabled(false);setStatus(error.message,"error");}}
 async function poll(){if(!runId)return;try{const packet=await request(`/runs/${encodeURIComponent(runId)}/events?since=${sequence}`);sequence=packet.next_sequence;const current=await request(`/runs/${encodeURIComponent(runId)}`);if(["COMPLETED","FAILED","CANCELLED"].includes(current.state)){clearInterval(timer);timer=0;setGenerateDisabled(false);setStatus(current.state==="COMPLETED"?"Report generated":"Report generation failed",current.state==="COMPLETED"?"success":"error");await refresh();}}catch(error){clearInterval(timer);timer=0;setGenerateDisabled(false);setStatus(error.message,"error");}}
 function bind(){if(bound)return;bound=true;q("aippOutputsRefresh")?.addEventListener("click",refresh);Object.keys(actions).forEach(key=>q(`aippOutputs${key[0].toUpperCase()+key.slice(1)}`)?.addEventListener("click",()=>generate(key)));A.aippDeckDocument.subscribe(refresh);refresh();}
 A.aippOutputsView={bind,refresh,generate};
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
