
function toScilabMsg(obj){window.toScilab(JSON.stringify(obj));}
function selectFile(){toScilabMsg({type:"select_file"});}
function selectCsvFile(){toScilabMsg({type:"select_csv"});}
function asciiToString(arr){return arr.map(c=>String.fromCharCode(c)).join('');}
let fullJson=null,currentTab="tree",treeOpenAll=false,treeUserOpen=new Set();
let simNodes=[],simEdges=[],popupNode=null,popupPath=null,popupWorkingCopy=null,popupOriginalCopy=null,pendingCdCsvImport=null;
let flowViewBox={x:0,y:0,w:1000,h:700,base:null},flowPan={active:false,x:0,y:0,start:null};
let popupDrag={active:false,dx:0,dy:0};
const AIPP_CD_BASIS_OPTIONS=["constant","time","pressure"],AIPP_PRESSURE_UNITS=["MPa","kPa","Pa"],AIPP_TIME_UNITS=["s","ms"],STANDARD_SPECIES=["Ar","CO","CO2","H2","H2O","He","N2","N2O","O2"];
const CHAMBER_INIT_TYPES=["mPT","PVT","mVT","nVT","rho_mVT"],CHAMBER_INIT_FIELDS={mPT:["mass","pressure","temperature"],PVT:["pressure","volume","temperature"],mVT:["mass","volume","temperature"],nVT:["moles","volume","temperature"],rho_mVT:["density","volume","temperature"]};
const CHAMBER_INIT_DEFAULTS={mass:"0.0 g",pressure:"0.101325 MPa",temperature:"300.0 K",volume:"1.0 L",density:"0.0 kg/m^3",moles:"0.0 mol"};
const AIPP_CD_TEMPLATES={constant:{basis:"constant",Cd_value:0.7},time:{basis:"time",time_units:"s",time_array:[0.0,0.01],Cd_array:[0.75,0.5],continuity:"interpolate"},pressure:{basis:"pressure",pressure_units:"MPa",pressure_array:[25.0,50.0],Cd_array:[0.75,0.5],continuity:"discrete"}};
function makeDischargeCoefficientTemplate(b){return deepCopy(AIPP_CD_TEMPLATES[b]||AIPP_CD_TEMPLATES.constant);}function normalizeUnit(s){return String(s||"").trim().replaceAll(" ","").toLowerCase();}
function canonicalPressureUnit(s){const u=normalizeUnit(s);return u==="mpa"?"MPa":u==="kpa"?"kPa":u==="pa"?"Pa":null;}function canonicalTimeUnit(s){const u=normalizeUnit(s);return u==="s"?"s":u==="ms"?"ms":null;}function canonicalCdUnit(s){const u=normalizeUnit(s);return (u===""||u==="cd"||u==="1"||u==="dimensionless"||u==="unitless")?"Cd":null;}
function parseQuantityString(s,allowed,def){const m=String(s||"").match(/^\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*([A-Za-z]+)\s*$/);let value=0,unit=def;if(m){value=Number(m[1]);for(const u of allowed)if(normalizeUnit(u)===normalizeUnit(m[2]))unit=u;}return{value,unit};}function formatQuantity(v,u){return String(v)+" "+u;}function formatDouble(v){const n=Number(v);if(!Number.isFinite(n))return String(v);return Number.isInteger(n)?n.toFixed(1):String(n);}function truncText(s,n){s=String(s||"");return s.length>n?s.slice(0,n-1)+"…":s;}
function getEventSuggestions(){const out=["SimStart"],a=getAssemblyInfo(fullJson).assembly;if(!a)return out;if(Array.isArray(a.orifices))for(let i=0;i<a.orifices.length;i++)out.push("O"+(i+1)+"_opened","O"+(i+1)+"_closed");if(Array.isArray(a.chambers))for(let c=0;c<a.chambers.length;c++){const ps=a.chambers[c].pyro;if(Array.isArray(ps))for(let p=0;p<ps.length;p++)out.push("C"+(c+1)+"P"+(p+1)+"_ignited","C"+(c+1)+"P"+(p+1)+"_extinguished");}return out;}
function deepCopy(x){return JSON.parse(JSON.stringify(x));}function escapeHtml(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function getJsonAtPath(path){let r=fullJson;for(const k of path){if(r==null)return undefined;r=r[k];}return r;}function setJsonAtPath(path,val){if(path.length===0)fullJson=val;else{let r=fullJson;for(let i=0;i<path.length-1;i++)r=r[path[i]];r[path[path.length-1]]=val;}refreshAllViews();}
function getPopupObjectAtPath(path){let r=popupWorkingCopy;for(const k of path){if(r==null)return null;r=r[k];}return r;}function getAssemblyInfo(j){if(j&&j.aipp_calculation&&j.aipp_calculation.assembly)return{assembly:j.aipp_calculation.assembly,basePath:["aipp_calculation","assembly"]};if(j&&j.assembly)return{assembly:j.assembly,basePath:["assembly"]};return{assembly:null,basePath:[]};}function refreshAllViews(){renderTree();updateCodeTextFromModel();buildGraph(fullJson);syncOpenPopupFromModel();}function setAtPath(path,val){let r=popupWorkingCopy;if(path.length===0){popupWorkingCopy=val;return;}for(let i=0;i<path.length-1;i++)r=r[path[i]];r[path[path.length-1]]=val;}function parseLoose(s){const t=String(s).trim();if(t==="null")return null;if(t==="true")return true;if(t==="false")return false;if(/^-?\d+(\.\d+)?([eE][+-]?\d+)?$/.test(t))return Number(t);return t;}
