function closeDependencyModal(){document.getElementById('dependencyModal').style.display='none'}
function scanOpenPopupDependencies(){if(!popupNode){setStatus('No open popup to scan.',false);return;}let idx=Number(popupPath[popupPath.length-1])+1;showDependencyReport(scanEntityDependencies(popupNode.type,idx,'delete'));}
function scanEntityDependencies(type,index,operation){if(type==='chamber')return scanChamberDependencies(index,operation);if(type==='orifice')return scanOrificeDependencies(index,operation);if(type==='wall')return scanWallDependencies(index,operation);return emptyReport(type,index,operation)}
function emptyReport(type,index,operation){return{entityType:type,entityIndex:index,operation,directReferences:[],shiftedReferences:[],eventReferences:[],warnings:[],summary:{directCount:0,shiftedCount:0,eventCount:0,canSafelyDelete:true}}}
function depPath(p){return(p||[]).map((x,i)=>typeof x==='number'?'['+x+']':(i===0?x:'.'+x)).join('').replace('.[','[')}
function ref(sev,kind,path,currentValue,proposedValue,message){return{severity:sev,kind,path,currentValue,proposedValue,message}}
function isInsertOperation(operation){return operation==='insert_before'||operation==='insert_after'||operation==='insert'}
function remapAfterDeleteOrInsert(v,index,operation){if(isInsertOperation(operation))return v>=index?v+1:v;return v>index?v-1:v}
function scanChamberDependencies(chamberIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('chamber',chamberIndex,operation);if(!a)return finishReport(r);
 (a.orifices||[]).forEach((o,i)=>['from','to'].forEach(k=>{let v=Number(o[k]),p=bp.concat(['orifices',i,k]);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===chamberIndex)r.directReferences.push(ref('blocker','orifice_connection',p,v,null,`Orifice ${i+1}.${k} points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&v>=chamberIndex)||(!isInsertOperation(operation)&&v>chamberIndex)){let nv=remapAfterDeleteOrInsert(v,chamberIndex,operation);r.shiftedReferences.push(ref('remap','chamber_index_shift',p,v,nv,`Orifice ${i+1}.${k} would remap from ${v} to ${nv}`));}}));
 (a.walls||[]).forEach((w,i)=>['left_connection','right_connection'].forEach(side=>{let c=w[side],v=Number(c&&c.chamber_index),p=bp.concat(['walls',i,side,'chamber_index']);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===chamberIndex)r.directReferences.push(ref('blocker','wall_chamber_connection',p,v,null,`Wall ${i+1}.${side}.chamber_index points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&v>=chamberIndex)||(!isInsertOperation(operation)&&v>chamberIndex)){let nv=remapAfterDeleteOrInsert(v,chamberIndex,operation);r.shiftedReferences.push(ref('remap','chamber_index_shift',p,v,nv,`Wall ${i+1}.${side}.chamber_index would remap from ${v} to ${nv}`));}}));
 findEventReferences(/C(\d+)P(\d+)_([A-Za-z0-9_]+)/g).forEach(e=>{let c=Number(e.match[1]);if(!isInsertOperation(operation)&&c===chamberIndex)r.eventReferences.push(ref('blocker','event_reference',e.path,e.value,null,`Event reference ${e.value} points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&c>=chamberIndex)||(!isInsertOperation(operation)&&c>chamberIndex)){let nc=remapAfterDeleteOrInsert(c,chamberIndex,operation);let proposed=e.value.replace('C'+c+'P','C'+nc+'P');r.eventReferences.push(ref('remap','event_reference_shift',e.path,e.value,proposed,`Event reference ${e.value} can be remapped to ${proposed} after ${operation}`));}});
 return finishReport(r)
}
function collectFilterOrificeReferences(a,bp){let refs=[];if(!a||!Array.isArray(a.chambers))return refs;function addFromFilterObject(f,path){if(f&&typeof f==='object'&&!Array.isArray(f)&&Array.isArray(f.orifices)){f.orifices.forEach((v,oi)=>refs.push({value:Number(v),path:path.concat(['orifices',oi])}));}}
 (a.chambers||[]).forEach((ch,ci)=>{if(ch&&typeof ch==='object'){
   if(Array.isArray(ch.filters))ch.filters.forEach((f,fi)=>addFromFilterObject(f,bp.concat(['chambers',ci,'filters',fi])));
   if(Array.isArray(ch.filter))ch.filter.forEach((f,fi)=>addFromFilterObject(f,bp.concat(['chambers',ci,'filter',fi])));
   else addFromFilterObject(ch.filter,bp.concat(['chambers',ci,'filter']));
 }});return refs;}
function scanOrificeDependencies(orificeIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('orifice',orificeIndex,operation);
 findEventReferences(/O(\d+)_([A-Za-z0-9_]+)/g).forEach(e=>{let o=Number(e.match[1]);if(!isInsertOperation(operation)&&o===orificeIndex)r.eventReferences.push(ref('blocker','event_reference',e.path,e.value,null,`Event reference ${e.value} points to Orifice ${orificeIndex}`));else if((isInsertOperation(operation)&&o>=orificeIndex)||(!isInsertOperation(operation)&&o>orificeIndex)){let no=remapAfterDeleteOrInsert(o,orificeIndex,operation);let proposed=e.value.replace('O'+o+'_','O'+no+'_');r.eventReferences.push(ref('remap','event_reference_shift',e.path,e.value,proposed,`Event reference ${e.value} can be remapped to ${proposed} after ${operation}`));}});
 collectFilterOrificeReferences(a,bp).forEach(fr=>{let v=Number(fr.value);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===orificeIndex)r.directReferences.push(ref('blocker','filter_orifice_reference',fr.path,v,null,`Filter orifices array references Orifice ${orificeIndex}`));else if((isInsertOperation(operation)&&v>=orificeIndex)||(!isInsertOperation(operation)&&v>orificeIndex)){let nv=remapAfterDeleteOrInsert(v,orificeIndex,operation);r.shiftedReferences.push(ref('remap','filter_orifice_index_shift',fr.path,v,nv,`Filter orifices entry would remap from ${v} to ${nv}`));}});
 return finishReport(r)
}
function scanWallDependencies(wallIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('wall',wallIndex,operation);if(!a)return finishReport(r);
 (a.walls||[]).forEach((w,i)=>['left_connection','right_connection'].forEach(side=>{let c=w[side],v=Number(c&&c.wall_index),p=bp.concat(['walls',i,side,'wall_index']);if(!(c&&c.type==='WALL')||!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===wallIndex)r.directReferences.push(ref('blocker','wall_wall_connection',p,v,null,`Wall ${i+1}.${side}.wall_index points to Wall ${wallIndex}`));else if((isInsertOperation(operation)&&v>=wallIndex)||(!isInsertOperation(operation)&&v>wallIndex)){let nv=remapAfterDeleteOrInsert(v,wallIndex,operation);r.shiftedReferences.push(ref('remap','wall_index_shift',p,v,nv,`Wall ${i+1}.${side}.wall_index would remap from ${v} to ${nv}`));}}));
 return finishReport(r)
}
function walkJson(v,path,cb){cb(v,path);if(v&&typeof v==='object'){if(Array.isArray(v))v.forEach((x,i)=>walkJson(x,path.concat([i]),cb));else Object.keys(v).forEach(k=>walkJson(v[k],path.concat([k]),cb));}}
function findEventReferences(regex){let out=[];walkJson(fullJson,[],(v,p)=>{if(typeof v==='string'){regex.lastIndex=0;let m;while((m=regex.exec(v))!==null)out.push({path:p,value:v,match:m});}});return out}
function finishReport(r){r.summary.directCount=r.directReferences.length;r.summary.shiftedCount=r.shiftedReferences.length;r.summary.eventCount=r.eventReferences.length;r.summary.canSafelyDelete=r.directReferences.length===0&&!r.eventReferences.some(e=>e.severity==='blocker');return r}
function showDependencyReport(r){let modal=document.getElementById('dependencyModal'),body=document.getElementById('dependencyModalBody'),title=document.getElementById('dependencyModalTitle');title.textContent=`Dependency Scan: ${r.entityType} ${r.entityIndex}`;body.innerHTML='';let sum=document.createElement('div');sum.className='depSummary';sum.textContent=`Direct: ${r.summary.directCount} | Shift/remap: ${r.summary.shiftedCount} | Event refs: ${r.summary.eventCount} | Conservative delete safe: ${r.summary.canSafelyDelete?'yes':'no'}`;body.appendChild(sum);renderDepSection(body,'Direct References',r.directReferences);renderDepSection(body,'Index Shift References',r.shiftedReferences);renderDepSection(body,'Event Remap References',r.eventReferences.filter(x=>x.severity==='remap'));renderDepSection(body,'Blocking Event References',r.eventReferences.filter(x=>x.severity==='blocker'));modal.style.display='flex'}
function renderDepSection(parent,title,items){let sec=document.createElement('div');sec.className='depSection';let h=document.createElement('div');h.className='depSectionTitle';h.textContent=title+' ('+items.length+')';sec.appendChild(h);if(!items.length){let n=document.createElement('div');n.className='depItem info';n.textContent='None found.';sec.appendChild(n)}items.forEach(it=>{let d=document.createElement('div');d.className='depItem '+(it.severity==='blocker'?'blocker':it.severity==='remap'?'remap':'info');d.innerHTML='<div>'+escapeHtml(it.message)+'</div><div class="depPath">'+escapeHtml(depPath(it.path||[]))+'</div><div>current: <span class="depValue">'+escapeHtml(JSON.stringify(it.currentValue))+'</span>'+((it.proposedValue!==undefined&&it.proposedValue!==null)?' proposed: <span class="depValue">'+escapeHtml(JSON.stringify(it.proposedValue))+'</span>':'')+'</div>';sec.appendChild(d)});parent.appendChild(sec)}
function closeRemoveModal(){let m=document.getElementById('removeModal');if(m)m.style.display='none';pendingRemovalPlan=null;}
function openRemovePreview(){if(!popupNode||!popupPath){setStatus('No selected entity to remove.',false);return;}let idx=Number(popupPath[popupPath.length-1])+1,report=scanEntityDependencies(popupNode.type,idx,'delete');pendingRemovalPlan=buildRemovalPlan(popupNode.type,idx,report);showRemovePreview(pendingRemovalPlan);}
function buildRemovalPlan(type,index,report){let blockers=[],warnings=[],actions=[],directEventRefs=(report.eventReferences||[]).filter(r=>r.severity==='blocker'),remapEventRefs=(report.eventReferences||[]).filter(r=>r.severity==='remap'&&r.proposedValue!==undefined&&r.proposedValue!==null);if(report.directReferences.length)blockers.push(...report.directReferences.map(r=>r.message));if(directEventRefs.length)blockers.push(...directEventRefs.map(r=>'Direct event reference requires manual reassignment before removal: '+r.message));actions.push('Remove assembly.'+(type==='chamber'?'chambers':type==='orifice'?'orifices':'walls')+'['+(index-1)+']');if((report.shiftedReferences||[]).length)warnings.push(report.shiftedReferences.length+' index reference(s) will be remapped automatically after removal.');if(remapEventRefs.length)warnings.push(remapEventRefs.length+' event reference(s) can be remapped automatically if the checkbox remains enabled.');return{type,index,report,blockers,warnings,actions,directEventRefs,remapEventRefs,allowed:blockers.length===0};}
function showRemovePreview(plan){let modal=document.getElementById('removeModal'),body=document.getElementById('removeModalBody'),title=document.getElementById('removeModalTitle'),btn=document.getElementById('applyRemoveBtn'),status=document.getElementById('removeModalStatus');title.textContent='Remove Preview: '+plan.type+' '+plan.index;body.innerHTML='';renderRemovalList(body,'Planned actions',plan.actions,'removeAllowed');renderRemovalList(body,'Blocking issues',plan.blockers,'removeBlocked');renderRemovalList(body,'Warnings',plan.warnings,'removeWarn');renderRemovalIndexPreview(body,plan);renderEventRemapPreview(body,plan);btn.disabled=!plan.allowed;status.textContent=plan.allowed?'Ready to apply removal.':'Resolve blockers before removal.';status.className=plan.allowed?'ok':'bad';modal.style.display='flex';}
function renderRemovalList(parent,title,items,cls){let box=document.createElement('div');box.className='removePlan '+cls;let h=document.createElement('div');h.className='removePlanTitle';h.textContent=title+' ('+items.length+')';box.appendChild(h);let b=document.createElement('div');b.className='removePlanBody';if(!items.length)b.textContent='None.';else{let ul=document.createElement('ul');ul.className='removeList';items.forEach(x=>{let li=document.createElement('li');li.textContent=x;ul.appendChild(li);});b.appendChild(ul);}box.appendChild(b);parent.appendChild(box);}
function renderRemovalIndexPreview(parent,plan){let refs=(plan.report&&plan.report.shiftedReferences)||[];let box=document.createElement('div');box.className='removePlan removeWarn';let h=document.createElement('div');h.className='removePlanTitle';h.textContent='Index remap preview ('+refs.length+')';box.appendChild(h);let b=document.createElement('div');b.className='removePlanBody';if(!refs.length)b.textContent='No index remaps found.';else{let table=document.createElement('table');table.className='eventRemapTable';table.innerHTML='<thead><tr><th>JSON path</th><th>Current</th><th>Proposed</th></tr></thead><tbody></tbody>';let tb=table.querySelector('tbody');refs.forEach(r=>{let tr=document.createElement('tr');tr.innerHTML='<td class="eventRemapPath">'+escapeHtml(depPath(r.path||[]))+'</td><td><span class="eventRemapValue">'+escapeHtml(String(r.currentValue))+'</span></td><td><span class="eventRemapValue">'+escapeHtml(String(r.proposedValue))+'</span></td>';tb.appendChild(tr);});b.appendChild(table);}box.appendChild(b);parent.appendChild(box)}
function renderEventRemapPreview(parent,plan){let box=document.createElement('div');box.className='removePlan removeWarn';let h=document.createElement('div');h.className='removePlanTitle';h.textContent='Event remap preview ('+plan.remapEventRefs.length+')';box.appendChild(h);let b=document.createElement('div');b.className='removePlanBody';if(!plan.remapEventRefs.length)b.textContent='No remappable event references found.';else{let label=document.createElement('label');label.className='eventRemapToggle';let chk=document.createElement('input');chk.type='checkbox';chk.checked=applyEventRemapsOnRemoval;chk.onchange=()=>applyEventRemapsOnRemoval=chk.checked;label.append(chk,document.createTextNode('Apply these event-string remaps during removal'));b.appendChild(label);let table=document.createElement('table');table.className='eventRemapTable';table.innerHTML='<thead><tr><th>JSON path</th><th>Current</th><th>Proposed</th></tr></thead><tbody></tbody>';let tb=table.querySelector('tbody');plan.remapEventRefs.forEach(r=>{let tr=document.createElement('tr');tr.innerHTML='<td class="eventRemapPath">'+escapeHtml(depPath(r.path||[]))+'</td><td><span class="eventRemapValue">'+escapeHtml(String(r.currentValue))+'</span></td><td><span class="eventRemapValue">'+escapeHtml(String(r.proposedValue))+'</span></td>';tb.appendChild(tr);});b.appendChild(table);}box.appendChild(b);parent.appendChild(box)}
function applyRemovalFromPreview(){if(!pendingRemovalPlan||!pendingRemovalPlan.allowed){setStatus('Removal is blocked.',false);return;}lastRemovalSnapshot=deepCopy(fullJson);let plan=pendingRemovalPlan,info=ensureAssembly(),a=info.assembly,idx0=plan.index-1;if(applyEventRemapsOnRemoval)applyEventReferenceRemaps(plan.remapEventRefs);if(plan.type==='chamber'){applyChamberIndexDeleteRemap(plan.index);a.chambers.splice(idx0,1)}else if(plan.type==='orifice'){applyOrificeIndexDeleteRemap(plan.index);a.orifices.splice(idx0,1)}else if(plan.type==='wall'){applyWallIndexDeleteRemap(plan.index);a.walls.splice(idx0,1)}closeRemoveModal();closeDependencyModal();closePopup();refreshAllViews();setStatus('Removed '+plan.type+' '+plan.index+'. Snapshot saved.',true)}
function applyEventReferenceRemaps(remaps){(remaps||[]).forEach(r=>{if(getJsonAtPath(r.path)===r.currentValue)setJsonAtPathNoRefresh(r.path,r.proposedValue);});}
function applyChamberIndexDeleteRemap(deletedIndex){let a=ensureAssembly().assembly;(a.orifices||[]).forEach(o=>{if(Number(o.from)>deletedIndex)o.from=Number(o.from)-1;if(Number(o.to)>deletedIndex)o.to=Number(o.to)-1;});(a.walls||[]).forEach(w=>['left_connection','right_connection'].forEach(side=>{let c=w&&w[side];if(c&&Number(c.chamber_index)>deletedIndex)c.chamber_index=Number(c.chamber_index)-1;}));}
function applyOrificeIndexDeleteRemap(deletedIndex){let a=ensureAssembly().assembly;if(!a||!Array.isArray(a.chambers))return;function remapFilter(f){if(f&&typeof f==='object'&&Array.isArray(f.orifices))f.orifices=f.orifices.map(v=>Number(v)>deletedIndex?Number(v)-1:Number(v));}(a.chambers||[]).forEach(ch=>{if(!ch||typeof ch!=='object')return;if(Array.isArray(ch.filters))ch.filters.forEach(remapFilter);if(Array.isArray(ch.filter))ch.filter.forEach(remapFilter);else remapFilter(ch.filter);});}
function applyWallIndexDeleteRemap(deletedIndex){let a=ensureAssembly().assembly;(a.walls||[]).forEach(w=>['left_connection','right_connection'].forEach(side=>{let c=w&&w[side];if(c&&c.type==='WALL'&&Number(c.wall_index)>deletedIndex)c.wall_index=Number(c.wall_index)-1;}));}
function undoLastRemovalSnapshot(){if(!lastRemovalSnapshot){setStatus('No removal snapshot available.',false);return;}fullJson=deepCopy(lastRemovalSnapshot);lastRemovalSnapshot=null;refreshAllViews();setStatus('Restored last removal snapshot.',true)}
