function buildGraph(j){
 simNodes=[];simEdges=[];clearSvg();const info=getAssemblyInfo(j),a=info.assembly,bp=info.basePath;if(!a||!a.chambers){setStatus("No assembly/chambers found for visualization.",false);return;}
 for(let i=0;i<a.chambers.length;i++)simNodes.push({id:"c"+(i+1),type:"chamber",label:"Ch "+(i+1),x:150+i*180,y:260+(i%2)*40,path:bp.concat(["chambers",i]),data:a.chambers[i]});
 if(a.orifices)for(let i=0;i<a.orifices.length;i++){const o=a.orifices[i],from=parseInt(o.from),to=parseInt(o.to);if(!from||!to)continue;const A=getNode("c"+from),B=getNode("c"+to),id="o"+(i+1);simNodes.push({id,type:"orifice",label:"Orf "+(i+1),x:(A.x+B.x)/2,y:(A.y+B.y)/2-70,path:bp.concat(["orifices",i]),data:o});simEdges.push({a:"c"+from,b:id,type:"flow"},{a:id,b:"c"+to,type:"flow"});}
 if(a.walls)for(let i=0;i<a.walls.length;i++){const w=a.walls[i],id="w"+(i+1);let anc=null;if(w.left_connection&&w.left_connection.chamber_index)anc=getNode("c"+w.left_connection.chamber_index);else if(w.right_connection&&w.right_connection.chamber_index)anc=getNode("c"+w.right_connection.chamber_index);simNodes.push({id,type:"wall",label:"Wall "+(i+1),x:anc?anc.x-70:120+i*90,y:anc?anc.y+120:460,path:bp.concat(["walls",i]),data:w});if(w.left_connection&&w.left_connection.chamber_index)simEdges.push({a:"c"+w.left_connection.chamber_index,b:id,type:"wall"});if(w.right_connection&&w.right_connection.chamber_index)simEdges.push({a:id,b:"c"+w.right_connection.chamber_index,type:"wall"});}
 drawSvg();setStatus(`Loaded ${simNodes.length} nodes, ${simEdges.length} links.`,true);
}
function getNode(id){return simNodes.find(n=>n.id===id)||{x:500,y:350};}function clearSvg(){const e=document.getElementById("edges"),n=document.getElementById("nodes");if(e)e.innerHTML="";if(n)n.innerHTML="";}
function drawSvg(){const eg=document.getElementById("edges"),ng=document.getElementById("nodes");if(!eg||!ng)return;for(const e of simEdges){const a=getNode(e.a),b=getNode(e.b),cls=e.type==="wall"?"edge edgeWall":"edge",arrow=e.type==="flow"?' marker-end="url(#arrow)" ':'';eg.insertAdjacentHTML("beforeend",`<line class="${cls}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" ${arrow}></line>`);}for(const n of simNodes){ng.insertAdjacentHTML("beforeend",nodeSvg(n));const el=document.getElementById("node_"+n.id);if(el)el.addEventListener("dblclick",ev=>{ev.preventDefault();openPopup(n);});}}
function nodeSvg(n){if(n.type==="chamber")return `<g id="node_${n.id}" style="cursor:pointer"><ellipse class="nodeChamber" cx="${n.x}" cy="${n.y}" rx="52" ry="26"></ellipse><text class="label" x="${n.x}" y="${n.y+4}" text-anchor="middle">${escapeHtml(n.label)}</text></g>`;if(n.type==="orifice")return `<g id="node_${n.id}" style="cursor:pointer"><rect class="nodeOrifice" x="${n.x-46}" y="${n.y-18}" width="92" height="36" rx="6"></rect><text class="label labelDark" x="${n.x}" y="${n.y+4}" text-anchor="middle">${escapeHtml(n.label)}</text></g>`;return `<g id="node_${n.id}" style="cursor:pointer"><path class="nodeWall" d="M ${n.x} ${n.y-24} L ${n.x+30} ${n.y} L ${n.x} ${n.y+24} L ${n.x-30} ${n.y} Z"></path><text class="label" x="${n.x}" y="${n.y+4}" text-anchor="middle">${escapeHtml(n.label)}</text></g>`;}
