function closeDependencyModal(){document.getElementById('dependencyModal').style.display='none'}
function scanOpenPopupDependencies(){if(!popupNode){setStatus('No open popup to scan.',false);return;}let idx=Number(popupPath[popupPath.length-1])+1;showDependencyReport(scanEntityDependencies(popupNode.type,idx,'delete'));}
function scanEntityDependencies(type,index,operation){if(type==='chamber')return scanChamberDependencies(index,operation);if(type==='orifice')return scanOrificeDependencies(index,operation);if(type==='wall')return scanWallDependencies(index,operation);return emptyReport(type,index,operation)}
function emptyReport(type,index,operation){return{entityType:type,entityIndex:index,operation,directReferences:[],shiftedReferences:[],eventReferences:[],warnings:[],summary:{directCount:0,shiftedCount:0,eventCount:0,canSafelyDelete:true}}}
function depPath(p){return(p||[]).map((x,i)=>typeof x==='number'?'['+x+']':(i===0?x:'.'+x)).join('').replace('.[','[')}
function ref(sev,kind,path,currentValue,proposedValue,message){return{severity:sev,kind,path,currentValue,proposedValue,message}}
function isInsertOperation(operation){return operation==='insert_before'||operation==='insert_after'||operation==='insert'}
function remapAfterDeleteOrInsert(v,index,operation){if(isInsertOperation(operation))return v>=index?v+1:v;return v>index?v-1:v}
function scanChamberDependencies(chamberIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('chamber',chamberIndex,operation);if(!a)return finishReport(r);
 (a.orifices||[]).forEach((o,i)=>['from','to'].forEach(k=>{let v=Number(o[k]),p=bp.concat(['orifices',i,k]);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===chamberIndex)r.directReferences.push(ref('blocker','orifice_connection',p,v,null,`Orifice ${i+1}.${k} points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&v>=chamberIndex)||(!isInsertOperation(operation)&&v>chamberIndex)){let nv=remapAfterDeleteOrInsert(v,chamberIndex,operation);r.shiftedReferences.push(ref('remap','chamber_index_shift',p,v,nv,`Orifice ${i+1}.${k} would remap from ${v} to ${nv}`));}}));
 (a.walls||[]).forEach((w,i)=>['left_connection','right_connection'].forEach(side=>{let c=w[side],v=Number(c&&c.chamber_index),p=bp.concat(['walls',i,side,'chamber_index']);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===chamberIndex)r.directReferences.push(ref('blocker','wall_chamber_connection',p,v,null,`Wall ${i+1}.${side}.chamber_index points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&v>=chamberIndex)||(!isInsertOperation(operation)&&v>chamberIndex)){let nv=remapAfterDeleteOrInsert(v,chamberIndex,operation);r.shiftedReferences.push(ref('remap','chamber_index_shift',p,v,nv,`Wall ${i+1}.${side}.chamber_index would remap from ${v} to ${nv}`));}}));
 findEventReferences(/C(\d+)P(\d+)_([A-Za-z0-9_]+)/g).forEach(e=>{let c=Number(e.match[1]);if(!isInsertOperation(operation)&&c===chamberIndex)r.eventReferences.push(ref('blocker','event_reference',e.path,e.value,null,`Event reference ${e.value} points to Chamber ${chamberIndex}`));else if((isInsertOperation(operation)&&c>=chamberIndex)||(!isInsertOperation(operation)&&c>chamberIndex)){let nc=remapAfterDeleteOrInsert(c,chamberIndex,operation);let proposed=e.value.replace('C'+c+'P','C'+nc+'P');r.eventReferences.push(ref('remap','event_reference_shift',e.path,e.value,proposed,`Event reference ${e.value} can be remapped to ${proposed} after ${operation}`));}});
 return finishReport(r)
}
function collectFilterOrificeReferences(a,bp){let refs=[];if(!a||!Array.isArray(a.chambers))return refs;function addFromFilterObject(f,path){if(f&&typeof f==='object'&&!Array.isArray(f)&&Array.isArray(f.orifices)){f.orifices.forEach((v,oi)=>refs.push({value:Number(v),path:path.concat(['orifices',oi])}));}}
 (a.chambers||[]).forEach((ch,ci)=>{if(ch&&typeof ch==='object'){
   if(Array.isArray(ch.filters))ch.filters.forEach((f,fi)=>addFromFilterObject(f,bp.concat(['chambers',ci,'filters',fi])));
   if(Array.isArray(ch.filter))ch.filter.forEach((f,fi)=>addFromFilterObject(f,bp.concat(['chambers',ci,'filter',fi])));
   else addFromFilterObject(ch.filter,bp.concat(['chambers',ci,'filter']));
 }});return refs;}
function scanOrificeDependencies(orificeIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('orifice',orificeIndex,operation);
 findEventReferences(/O(\d+)_([A-Za-z0-9_]+)/g).forEach(e=>{let o=Number(e.match[1]);if(!isInsertOperation(operation)&&o===orificeIndex)r.eventReferences.push(ref('blocker','event_reference',e.path,e.value,null,`Event reference ${e.value} points to Orifice ${orificeIndex}`));else if((isInsertOperation(operation)&&o>=orificeIndex)||(!isInsertOperation(operation)&&o>orificeIndex)){let no=remapAfterDeleteOrInsert(o,orificeIndex,operation);let proposed=e.value.replace('O'+o+'_','O'+no+'_');r.eventReferences.push(ref('remap','event_reference_shift',e.path,e.value,proposed,`Event reference ${e.value} can be remapped to ${proposed} after ${operation}`));}});
 collectFilterOrificeReferences(a,bp).forEach(fr=>{let v=Number(fr.value);if(!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===orificeIndex)r.directReferences.push(ref('blocker','filter_orifice_reference',fr.path,v,null,`Filter orifices array references Orifice ${orificeIndex}`));else if((isInsertOperation(operation)&&v>=orificeIndex)||(!isInsertOperation(operation)&&v>orificeIndex)){let nv=remapAfterDeleteOrInsert(v,orificeIndex,operation);r.shiftedReferences.push(ref('remap','filter_orifice_index_shift',fr.path,v,nv,`Filter orifices entry would remap from ${v} to ${nv}`));}});
 return finishReport(r)
}
function scanWallDependencies(wallIndex,operation='delete'){
 let info=getAssemblyInfo(fullJson),a=info.assembly,bp=info.basePath,r=emptyReport('wall',wallIndex,operation);if(!a)return finishReport(r);
 (a.walls||[]).forEach((w,i)=>['left_connection','right_connection'].forEach(side=>{let c=w[side],v=Number(c&&c.wall_index),p=bp.concat(['walls',i,side,'wall_index']);if(!(c&&c.type==='WALL')||!Number.isFinite(v))return;if(!isInsertOperation(operation)&&v===wallIndex)r.directReferences.push(ref('blocker','wall_wall_connection',p,v,null,`Wall ${i+1}.${side}.wall_index points to Wall ${wallIndex}`));else if((isInsertOperation(operation)&&v>=wallIndex)||(!isInsertOperation(operation)&&v>wallIndex)){let nv=remapAfterDeleteOrInsert(v,wallIndex,operation);r.shiftedReferences.push(ref('remap','wall_index_shift',p,v,nv,`Wall ${i+1}.${side}.wall_index would remap from ${v} to ${nv}`));}}));
 return finishReport(r)
}
function walkJson(v,path,cb){cb(v,path);if(v&&typeof v==='object'){if(Array.isArray(v))v.forEach((x,i)=>walkJson(x,path.concat([i]),cb));else Object.keys(v).forEach(k=>walkJson(v[k],path.concat([k]),cb));}}
function findEventReferences(regex){let out=[];walkJson(fullJson,[],(v,p)=>{if(typeof v==='string'){regex.lastIndex=0;let m;while((m=regex.exec(v))!==null)out.push({path:p,value:v,match:m});}});return out}
function finishReport(r){r.summary.directCount=r.directReferences.length;r.summary.shiftedCount=r.shiftedReferences.length;r.summary.eventCount=r.eventReferences.length;r.summary.canSafelyDelete=r.directReferences.length===0&&!r.eventReferences.some(e=>e.severity==='blocker');return r}
function showDependencyReport(r){let modal=document.getElementById('dependencyModal'),body=document.getElementById('dependencyModalBody'),title=document.getElementById('dependencyModalTitle');title.textContent=`Dependency Scan: ${r.entityType} ${r.entityIndex}`;body.innerHTML='';let sum=document.createElement('div');sum.className='depSummary';sum.textContent=`Direct: ${r.summary.directCount} | Shift/remap: ${r.summary.shiftedCount} | Event refs: ${r.summary.eventCount} | Conservative delete safe: ${r.summary.canSafelyDelete?'yes':'no'}`;body.appendChild(sum);renderDepSection(body,'Direct References',r.directReferences);renderDepSection(body,'Index Shift References',r.shiftedReferences);renderDepSection(body,'Event Remap References',r.eventReferences.filter(x=>x.severity==='remap'));renderDepSection(body,'Blocking Event References',r.eventReferences.filter(x=>x.severity==='blocker'));modal.style.display='flex'}
function renderDepSection(parent,title,items){let sec=document.createElement('div');sec.className='depSection';let h=document.createElement('div');h.className='depSectionTitle';h.textContent=title+' ('+items.length+')';sec.appendChild(h);if(!items.length){let n=document.createElement('div');n.className='depItem info';n.textContent='None found.';sec.appendChild(n)}items.forEach(it=>{let d=document.createElement('div');d.className='depItem '+(it.severity==='blocker'?'blocker':it.severity==='remap'?'remap':'info');d.innerHTML='<div>'+escapeHtml(it.message)+'</div><div class="depPath">'+escapeHtml(depPath(it.path||[]))+'</div><div>current: <span class="depValue">'+escapeHtml(JSON.stringify(it.currentValue))+'</span>'+((it.proposedValue!==undefined&&it.proposedValue!==null)?' proposed: <span class="depValue">'+escapeHtml(JSON.stringify(it.proposedValue))+'</span>':'')+'</div>';sec.appendChild(d)});parent.appendChild(sec)}
