function config = p52AppConfig(appRoot)
    config = struct( ...
        "application_name", "AIPP Inflator Model Viewer - Qualification", ...
        "application_version", "0.8.10-prep2-stabilization.candidate.6", ...
        "pillar7_implementation_version", "P7.5.0-0.1", ...
        "minimum_scilab_version", "2026.1.0", ...
        "build_mode", "test", ...
        "include_plotting", %t, ...
        "include_testing", %t, ...
        "jcef_debug", %t, ...
        "bundle_path", fullfile(appRoot, "browser_files", "dist", "bundle.test.html"));
endfunction

function config = p54StarterConfig(appRoot)
    config = struct( ...
        "application_name", "AIPP Inflator Model Viewer", ...
        "application_version", "0.8.10-prep2-stabilization.candidate.6", ...
        "pillar7_implementation_version", "P7.5.0-0.1", ...
        "minimum_scilab_version", "2026.1.0", ...
        "build_mode", "production", ...
        "include_plotting", %f, ...
        "include_testing", %f, ...
        "jcef_debug", %t, ...
        "bundle_path", fullfile(appRoot, "browser_files", "dist", "bundle.prod.html"));
endfunction
