function errorMessage = p2ProtocolError(requestId, code, message, retryable)
    global P2_PROTOCOL_NAME;
    global P2_PROTOCOL_VERSION;
    global P2_MIN_PROTOCOL_VERSION;
    global P2_MAX_PROTOCOL_VERSION;
    if argn(2) < 4 then retryable = %f; end
    errorMessage = struct("protocol", P2_PROTOCOL_NAME, ...
                          "protocol_version", P2_PROTOCOL_VERSION, ...
                          "type", "protocol.error", ...
                          "request_id", requestId, ...
                          "status", "error", ...
                          "error", struct("code", code, "message", message, "retryable", retryable));
endfunction
