global P2_PROTOCOL_NAME;
global P2_PROTOCOL_VERSION;
global P2_MIN_PROTOCOL_VERSION;
global P2_MAX_PROTOCOL_VERSION;
P2_PROTOCOL_NAME = "scilab-jcef";
P2_PROTOCOL_VERSION = 1;
P2_MIN_PROTOCOL_VERSION = 1;
P2_MAX_PROTOCOL_VERSION = 1;
