"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm"),crypto=require("crypto");
const root=path.resolve(__dirname,"..");let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log(`PASS ${name}`);}catch(error){failed++;console.error(`FAIL ${name}: ${error.message}`);}}
const context={window:{addEventListener(){},removeEventListener(){}},document:{readyState:"complete",addEventListener(){}},console,performance:{now:()=>0},TextEncoder,TextDecoder,ArrayBuffer,Uint8Array,Float64Array,Set,Map,Date,Math,JSON,Object,Number,String,Boolean,Error};context.window.window=context.window;vm.createContext(context);
for(const rel of ["browser_files/js/observability/00_startup_error_collector.js","browser_files/js/observability/01_observability_constants.js","browser_files/js/observability/02_payload_summary.js","browser_files/js/observability/03_observability_record.js","browser_files/js/observability/04_observability_logger.js","browser_files/js/observability/05_performance_registry.js","browser_files/js/observability/06_diagnostic_package_export.js","browser_files/js/observability/05_file_operation_events.js"]){vm.runInContext(fs.readFileSync(path.join(root,rel),"utf8"),context,{filename:rel});}
const P7=context.window.P7;
test("P7-CON-001 valid record",()=>{const r=P7.record.create("error","protocol","protocol.message_decode_failed",{request_id:"req-1"},{reason:"bad"});if(!P7.record.validate(r).pass)throw Error("valid record rejected");});
test("P7-CON-003 invalid level rejected",()=>{let ok=false;try{P7.record.create("fatal","protocol","x",{},{});}catch(_){ok=true;}if(!ok)throw Error("invalid level accepted");});
test("P7-LOG-002 request correlation",()=>{P7.logger.setLevel("debug");const r=P7.logger.info("transport","transport.request_started",{request_id:"req-2"},{type:"echo"});if(r.request_id!=="req-2")throw Error("request ID lost");});
test("P7-LOG-003 transfer correlation",()=>{const r=P7.logger.info("transport","transport.transfer_started",{transfer_id:"xfr-2"},{});if(r.transfer_id!=="xfr-2")throw Error("transfer ID lost");});
test("P7-PAY-002 100k array summarized",()=>{const s=P7.payloadSummary.summarize(new Float64Array(100000));if(s.count!==100000||s.estimated_bytes!==800000||s.full_payload_logged!==false||s.sample.length>6)throw Error(JSON.stringify(s));});
test("P7-PAY-003 1M array summarized",()=>{const s=P7.payloadSummary.summarize(new Float64Array(1000000));if(s.count!==1000000||s.sample.length>6||Object.prototype.hasOwnProperty.call(s,"values"))throw Error("large payload dumped");});
test("P7-FIO stage validation",()=>{let ok=false;try{P7.fileOperations.failed("open","invalid",new Error("x"));}catch(_){ok=true;}if(!ok)throw Error("invalid stage accepted");});
test("bounded browser logs",()=>{P7.logger.clear();for(let i=0;i<250;i++)P7.logger.info("test","test.case_completed",{}, {i});if(P7.logger.entries.length!==200)throw Error(String(P7.logger.entries.length));});
test("shared fixture manifest",()=>{const m=JSON.parse(fs.readFileSync(path.join(root,"tests/observability_fixtures/manifest.json"),"utf8"));if(m.observability_version!=="1.0")throw Error("wrong version");});
test("Scilab facade delegates",()=>{const t=fs.readFileSync(path.join(root,"scilab/protocol/protocol_log.sci"),"utf8");if(!t.includes("p7HostLog("))throw Error("facade missing");});
test("module loader orders observability before protocol log",()=>{const t=fs.readFileSync(path.join(root,"scilab/bootstrap/module_loader.sci"),"utf8"),a=t.indexOf('"observability" "observability_log.sci"'),b=t.indexOf('"protocol" "protocol_log.sci"');if(a<0||b<0||a>b)throw Error("bad order");});

test("P7-PERF-001 encode timing",()=>{P7.performance.clear();P7.performance.recordProtocol({request_encode_ms:1.2,transport_callback_ms:2.3,response_decode_ms:0.4},{request_id:"req-perf"});if(P7.performance.records.length!==3||P7.performance.records[0].request_id!=="req-perf")throw Error("protocol metrics missing");});
test("P7-PERF-004 calculation and reduction",()=>{P7.performance.recordPlot({source_generation_ms:3,reduction_ms:4,render_ms:5,pipeline_ms:12,source_point_count:1000,point_count:100,estimated_numeric_payload_bytes:1600},{request_id:"req-plot"});const names=new Set(P7.performance.records.map(x=>x.name));for(const n of ["calculation.duration_ms","plot.reduction.duration_ms","plot.render.duration_ms","plot.pipeline.duration_ms","plot.source_points.visible","plot.display_points.delivered","browser.dataset.estimated_bytes"])if(!names.has(n))throw Error(n);});
test("P7-PERF-008 gauges",()=>{P7.performance.gauge("request.pending.count",2);P7.performance.gauge("transfer.active.count",1);const snap=P7.performance.snapshot();if(snap.gauges["request.pending.count"]!==2||snap.gauges["transfer.active.count"]!==1)throw Error("gauge mismatch");});
test("P7-PERF-010 counters exactly accumulate",()=>{P7.performance.increment("request.failed.count");P7.performance.increment("request.failed.count");if(P7.performance.counters.get("request.failed.count")!==2)throw Error("counter mismatch");});
test("P7-PERF invalid values rejected",()=>{let ok=false;try{P7.performance.record("x",-1,"ms");}catch(_){ok=true;}if(!ok)throw Error("negative value accepted");});
test("P7-PERF bounded history",()=>{P7.performance.clear();for(let i=0;i<250;i++)P7.performance.record("test.metric",i,"count");if(P7.performance.records.length!==200)throw Error(String(P7.performance.records.length));});

test("P7-START-001 startup collector available",()=>{if(!P7.startup||!Array.isArray(P7.startup.records))throw Error("collector missing");});
test("P7-START-002 startup snapshot bounded",()=>{for(let i=0;i<120;i++)P7.startup.records.push({i});while(P7.startup.records.length>100)P7.startup.records.shift();if(P7.startup.snapshot().error_count!==100)throw Error("startup retention");P7.startup.clear();});
test("P7-PANEL-001 dev panel unified sources",()=>{const t=fs.readFileSync(path.join(root,"browser_files/js/diagnostics/01_dev_panel.js"),"utf8");for(const marker of ["P7.startup","P7.performance","P7.logger","P2.diagnostics"]){if(!t.includes(marker))throw Error(marker);}});
test("P7-PANEL-002 production excludes diagnostics",()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,"browser_files/build/dependency_manifest.json"),"utf8"));const panel=manifest.modules.find(x=>x.id==="diagnostics.dev.panel");if(!panel||panel.modes.includes("prod")||panel.modes.includes("test"))throw Error("profile leak");});
test("P7-PANEL-003 controls declared",()=>{const html=fs.readFileSync(path.join(root,"browser_files/components_dev/01_dev.html"),"utf8");for(const id of ["diagnosticLogLevel","diagnosticCategory","diagnosticClear","diagnosticRefresh","diagnosticExport"]){if(!html.includes(`id="${id}"`))throw Error(id);}});

test("P7-EXP-003 package source inventory",()=>{const names=["identity.json","compatibility.json","runtime_snapshot.json","browser_logs.jsonl","host_logs.jsonl","performance_metrics.jsonl","recent_operations.json","build_manifest.json","test_context.json","README.txt"];for(const n of names){if(!fs.readFileSync(path.join(root,"browser_files/js/observability/06_diagnostic_package_export.js"),"utf8").includes(n))throw Error(n);}});
test("P7-EXP-004 deterministic content hashes",()=>{const a=P7.diagnosticExport.fnv1a("same"),b=P7.diagnosticExport.fnv1a("same"),c=P7.diagnosticExport.fnv1a("different");if(a!==b||a===c||a.length!==8)throw Error("hash contract");});
test("P7-EXP-005 missing optional source explicit",()=>{const x=P7.diagnosticExport.source("host_logs.jsonl","","unavailable","missing");if(x.status!=="unavailable"||!x.note)throw Error("availability");});
test("P7-EXP-006 retention policy",()=>{const catalog=JSON.parse(fs.readFileSync(path.join(root,"protocol/observability/diagnostic_package_export.schema.json"),"utf8"));if(catalog.properties.retention_limit.maximum!==200)throw Error("retention");});
test("P7-EXP-007 atomic host commit",()=>{const t=fs.readFileSync(path.join(root,"scilab/observability/diagnostic_package_export.sci"),"utf8");for(const marker of [".tmp","movefile","PACKAGE_COMPLETE","rmdir(tempDir"])if(!t.includes(marker))throw Error(marker);});
test("P7-EXP-008 export cleanup",()=>{const t=fs.readFileSync(path.join(root,"browser_files/js/observability/06_diagnostic_package_export.js"),"utf8");if(!t.includes("finally{this.active=false"))throw Error("active cleanup");});

test("P7-CLOSE-001 closure deliverables complete",()=>{const base="Pillar07_Observability_Diagnostics";for(const name of ["Pillar7_Executive_Summary.md","Pillar7_Completion_Record.md","Pillar7_Detailed_Validation_Report.md","Pillar7_Requirements_Traceability.md","Pillar7_Test_Inventory.md","Pillar7_Event_Catalog.md","Pillar7_Metric_Catalog.md","Pillar7_Diagnostic_Package_Spec.md","Pillar7_Known_Limitations.md","Pillar7_Rollback_Instructions.md"]){if(!fs.existsSync(path.join(root,base,name)))throw Error(name);}});
test("P7-CLOSE-002 every OBS requirement indexed",()=>{const x=JSON.parse(fs.readFileSync(path.join(root,"Pillar07_Observability_Diagnostics/evidence/evidence_index.json"),"utf8"));const ids=new Set(x.requirements.map(r=>r.requirement));for(let i=1;i<=10;i++){const id=`OBS-${String(i).padStart(3,"0")}`;if(!ids.has(id))throw Error(id);}});
test("P7-CLOSE-003 accepted P7.4 evidence clean",()=>{const x=JSON.parse(fs.readFileSync(path.join(root,"Pillar07_Observability_Diagnostics/evidence/pillar7_results.json"),"utf8"));if(x.passed!==177||x.failed!==0||x.skipped!==0||x.final_state.active_requests!==0||x.final_state.active_transfers!==0)throw Error("P7.4 evidence");});
test("P7-CLOSE-004 completion is accepted",()=>{const t=fs.readFileSync(path.join(root,"Pillar07_Observability_Diagnostics/Pillar7_Completion_Record.md"),"utf8");if(!t.includes("COMPLETE AND ACCEPTED")||!t.includes("177 passed"))throw Error("acceptance record");});
const report={suite:"P7.0-P7.5 closure candidate validation",generated_at:new Date().toISOString(),passed,failed,result:failed?"FAIL":"PASS"};fs.mkdirSync(path.join(root,"evidence/p7.1"),{recursive:true});fs.writeFileSync(path.join(root,"evidence/p7.1/validation_results.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify(report));process.exitCode=failed?1:0;
